/*****************************************************************************
 *
 * Copyright (C) 2008-2022 Advanced Micro Devices, Inc. All rights reserved.
 *
 *******************************************************************************
 */

#include "CbsSetupSmm.h"

EFI_HANDLE mCbsSetupSmmCommHandle;

//External decalration, the code is auto generated by AmdCbsPkg/Tools/CBSgenerate.pl
//Build\Resource<Program>\ApcbSetData<Program>.c
EFI_STATUS
UpdateCbsApcbTokens (
  VOID *CbsVariable,
  AMD_APCB_SERVICE_PROTOCOL *ApcbProtocol
  );

/**
 * @brief SMM communication handler used to handle the SMM service request from normal world
 *        Used for updating APCB.
 *
 * @param DispatchHandle
 * @param Context
 * @param CommBuffer
 * @param CommBufferSize
 * @return EFI_STATUS
 */
EFI_STATUS
EFIAPI
CbsSetupSmmCommunicateHandler (
  IN       EFI_HANDLE  DispatchHandle,
  IN       CONST VOID  *Context,
  IN OUT   VOID    *CommBuffer,
  IN OUT   UINTN   *CommBufferSize
  )
{
  EFI_STATUS                Status;
  AMD_APCB_SERVICE_PROTOCOL *ApcbSmmProtocol;
  CBS_SMM_COMMUNICATION_CMN  *SmmCommParameterCmn;
  CBS_SMM_COMM_UPDATE_APCB  *SmmCommParameterUpdateApcb;

  if (!SmmIsBufferOutsideSmmValid ((UINTN)CommBuffer, *CommBufferSize)) {
    DEBUG ((EFI_D_ERROR,"SMM communication data buffer in SMRAM or overflow!\n"));
    return EFI_INVALID_PARAMETER;
  }

  Status = EFI_UNSUPPORTED;
  SmmCommParameterCmn = (CBS_SMM_COMMUNICATION_CMN *) CommBuffer;
  DEBUG ((EFI_D_ERROR, "CbsSetupSmmCommunicateHandler ID %x\n", SmmCommParameterCmn->id));

  if (SmmCommParameterCmn->id == CBS_SMM_COMM_ID_UPDATE_APCB) {
    SmmCommParameterUpdateApcb = (CBS_SMM_COMM_UPDATE_APCB *) CommBuffer;
    Status = gSmst->SmmLocateProtocol(&gAmdApcbSmmServiceProtocolGuid, NULL, (VOID **)&ApcbSmmProtocol);
    ASSERT (!EFI_ERROR(Status));
    if (EFI_ERROR (Status)) {
      DEBUG ((EFI_D_ERROR, "gAmdApcbSmmServiceProtocolGuid Locate fail, exit\n"));
      return Status;
    }

    DEBUG ((EFI_D_ERROR, "SMM UpdateCbsApcbToken\n"));
    Status = UpdateCbsApcbTokens (
                    (VOID *) &SmmCommParameterUpdateApcb->CbsVariable[0],
                    ApcbSmmProtocol
                    );
    DEBUG ((EFI_D_ERROR, "SMM UpdateCbsApcbToken : %r\n", Status));
  }

  return Status;
}


/**
  Main entry for this driver.

  @details  Allocate RT DATA used for SMM communication
            Register SMM communication handler used to update APCB, as

  @param ImageHandle     Image handle this driver.
  @param SystemTable     Pointer to SystemTable.

  @retval EFI_SUCESS     This function always complete successfully.

**/
EFI_STATUS
EFIAPI
CbsSetupSmmInit (
  IN EFI_HANDLE                   ImageHandle,
  IN EFI_SYSTEM_TABLE             *SystemTable
  )
{
  EFI_STATUS                      Status;
  VOID                            *SmmCommBuffer;

  DEBUG ((EFI_D_INFO, "CbsSetupSmmInit Enter\n"));

  //Allocate RT buffer for Smm communication before EndOfDxe Event to satisfie WSMT test
  SmmCommBuffer = NULL;
  Status = gBS->AllocatePool (EfiRuntimeServicesData, PcdGet64 (PcdCbsSmmCommunicationBufferSize), &SmmCommBuffer);

  ASSERT_EFI_ERROR(Status);
  ASSERT (SmmCommBuffer != NULL);
  if (EFI_ERROR (Status)) {
    DEBUG ((EFI_D_ERROR, "AllocateRtDataPool fail, Exit\n"));
    goto Exit;
  }
  //Save to PCD database
  PcdSet64S (PcdCbsSmmCommunicationAddress, (UINT64) (UINTN) SmmCommBuffer);

  DEBUG ((EFI_D_ERROR, "Register CbsSetupSmmCommunicateHandler\n"));
  mCbsSetupSmmCommHandle = NULL;
  Status = gSmst->SmiHandlerRegister (CbsSetupSmmCommunicateHandler, &gCbsSmmCommHandleGuid, &mCbsSetupSmmCommHandle);
  ASSERT_EFI_ERROR(Status);

Exit:
  DEBUG ((EFI_D_INFO, "CbsSetupSmmInit Exit %r\n", Status));

  return Status;
}

