/*****************************************************************************
 * Copyright (C) 2008-2022 Advanced Micro Devices, Inc. All rights reserved.
 *
*****************************************************************************
*/
/**
 * @file
 *
 * IOMMU init tables
 *
 *
 *
 * @xrefitem bom "File Content Label" "Release Content"
 * @e project:     AGESA
 * @e sub-project: GNB
 * @e \$Revision: 309090 $   @e \$Date: 2014-12-09 12:28:05 -0600 (Tue, 09 Dec 2014) $
 *
 */
/*----------------------------------------------------------------------------------------
 *                             M O D U L E S    U S E D
 *----------------------------------------------------------------------------------------
 */
#include  <Library/NbioTableBlastLib.h>
#include  <GnbRegistersRMB.h>
#include  <Filecode.h>

#define FILECODE        NBIO_NBIOBASE_RMB_PEI_GNBIOMMUTABLES_FILECODE

/*----------------------------------------------------------------------------------------
 *                   D E F I N I T I O N S    A N D    M A C R O S
 *----------------------------------------------------------------------------------------
 */


/*----------------------------------------------------------------------------------------
 *                  T Y P E D E F S     A N D     S T R U C T U  R E S
 *----------------------------------------------------------------------------------------
 */


/*----------------------------------------------------------------------------------------
 *           P R O T O T Y P E S     O F     L O C A L     F U  N C T I O N S
 *----------------------------------------------------------------------------------------
 */


/*----------------------------------------------------------------------------------------
 *           T A B L E S
 *----------------------------------------------------------------------------------------
 */


/*----------------------------------------------------------------------------------------
 *           P R O T O T Y P E S     O F     L O C A L     F U  N C T I O N S
 *----------------------------------------------------------------------------------------
 */

//
// PPR 14.3.1.2.2 : This table initializes IOMMU
//
GNB_TABLE ROMDATA GnbIommuEnvInitTable [] = {
//---------------------------------------------------------------------------
// Disable INTx in IOMMU
  GNB_ENTRY_RMW (
    ALL_NBIO_TYPE,
    SMN_IOMMU_CONTROL_W_ADDRESS,
    IOMMU_CONTROL_W_INTERRUPT_PIN_W_MASK,
    0x0 << IOMMU_CONTROL_W_INTERRUPT_PIN_W_OFFSET
    ),
  //
  // IOMMU L1 Initialization
  //
  // Program IOMMUL1::L1_FEATURE_CNTRL[EXE_lock_bit] = 1h.
  // Program IOMMUL1::L1_FEATURE_CNTRL[PMR_lock_bit] = 1h.
  GNB_ENTRY_RMW (
    ALL_NBIO_TYPE,
    SMN_IOAGR_L1_FEATURE_CNTRL_ADDRESS,
    L1_FEATURE_CNTRL_EXE_lock_bit_MASK |
    L1_FEATURE_CNTRL_PMR_lock_bit_MASK,
    1 << L1_FEATURE_CNTRL_EXE_lock_bit_OFFSET |
    1 << L1_FEATURE_CNTRL_PMR_lock_bit_OFFSET
    ),
  GNB_ENTRY_RMW (
    ALL_NBIO_TYPE,
    SMN_PCIE0_L1_FEATURE_CNTRL_ADDRESS,
    L1_FEATURE_CNTRL_EXE_lock_bit_MASK |
    L1_FEATURE_CNTRL_PMR_lock_bit_MASK,
    1 << L1_FEATURE_CNTRL_EXE_lock_bit_OFFSET |
    1 << L1_FEATURE_CNTRL_PMR_lock_bit_OFFSET
    ),
  GNB_ENTRY_RMW (
    ALL_NBIO_TYPE,
    SMN_IOAGR_L1_SDP_DMA_DATA_CREDIT_0_ADDRESS,
    L1_SDP_DMA_DATA_CREDIT_0_VC0_DMA_DATA_CREDIT_MASK |
    L1_SDP_DMA_DATA_CREDIT_0_VC1_DMA_DATA_CREDIT_MASK |
    L1_SDP_DMA_DATA_CREDIT_0_VC2_DMA_DATA_CREDIT_MASK |
    L1_SDP_DMA_DATA_CREDIT_0_VC3_DMA_DATA_CREDIT_MASK,
    0x2000202 << L1_SDP_DMA_DATA_CREDIT_0_VC0_DMA_DATA_CREDIT_OFFSET
    ),
  GNB_ENTRY_RMW (
    ALL_NBIO_TYPE,
    SMN_IOAGR_L1_SDP_DMA_DATA_CREDIT_1_ADDRESS,
    L1_SDP_DMA_DATA_CREDIT_1_VC4_DMA_DATA_CREDIT_MASK |
    L1_SDP_DMA_DATA_CREDIT_1_VC5_DMA_DATA_CREDIT_MASK |
    L1_SDP_DMA_DATA_CREDIT_1_VC6_DMA_DATA_CREDIT_MASK |
    L1_SDP_DMA_DATA_CREDIT_1_VC7_DMA_DATA_CREDIT_MASK,
    0x400 << L1_SDP_DMA_DATA_CREDIT_1_VC4_DMA_DATA_CREDIT_OFFSET
    ),
  GNB_ENTRY_RMW (
    ALL_NBIO_TYPE,
    SMN_IOAGR_L1_SDP_DMA_REQ_CREDIT_0_ADDRESS,
    L1_SDP_DMA_REQ_CREDIT_0_VC0_DMA_REQ_CREDIT_MASK |
    L1_SDP_DMA_REQ_CREDIT_0_VC1_DMA_REQ_CREDIT_MASK |
    L1_SDP_DMA_REQ_CREDIT_0_VC2_DMA_REQ_CREDIT_MASK |
    L1_SDP_DMA_REQ_CREDIT_0_VC3_DMA_REQ_CREDIT_MASK,
    0x1000101 << L1_SDP_DMA_REQ_CREDIT_0_VC0_DMA_REQ_CREDIT_OFFSET
    ),
  GNB_ENTRY_RMW (
    ALL_NBIO_TYPE,
    SMN_IOAGR_L1_SDP_DMA_REQ_CREDIT_1_ADDRESS,
    L1_SDP_DMA_REQ_CREDIT_1_VC4_DMA_REQ_CREDIT_MASK |
    L1_SDP_DMA_REQ_CREDIT_1_VC5_DMA_REQ_CREDIT_MASK |
    L1_SDP_DMA_REQ_CREDIT_1_VC6_DMA_REQ_CREDIT_MASK |
    L1_SDP_DMA_REQ_CREDIT_1_VC7_DMA_REQ_CREDIT_MASK,
    0x500 << L1_SDP_DMA_REQ_CREDIT_1_VC4_DMA_REQ_CREDIT_OFFSET
    ),
  //
  // IOMMU L2 Initialization
  //
  // Program IOMMUL2::L2_ERR_RULE_CONTROL_0[ERRRuleLock0] = 1h
  GNB_ENTRY_RMW (
    ALL_NBIO_TYPE,
    SMN_L2_ERR_RULE_CONTROL_0_ADDRESS,
    L2_ERR_RULE_CONTROL_0_ERRRuleLock0_MASK,
    0x1 << L2_ERR_RULE_CONTROL_0_ERRRuleLock0_OFFSET
    ),
  // Program IOMMUL2::L2_ERR_RULE_CONTROL_3[ERRRuleLock1] = 1h.
  GNB_ENTRY_RMW (
    ALL_NBIO_TYPE,
    SMN_L2_ERR_RULE_CONTROL_3_ADDRESS,
    L2_ERR_RULE_CONTROL_3_ERRRuleLock1_MASK,
    0x1 << L2_ERR_RULE_CONTROL_3_ERRRuleLock1_OFFSET
    ),
  GNB_ENTRY_RMW ( 
    ALL_NBIO_TYPE, 
    SMN_RIOMMU_CP_CNTRL_0_ADDRESS, 
    RIOMMU_CP_CNTRL_0_CONVERT_TO_INV_ALL_MASK, 
    (1 << RIOMMU_CP_CNTRL_0_CONVERT_TO_INV_ALL_OFFSET)
    ),      
  // Program IOMMUL2::RIOMMU_MULTI_INVACK_LIM = 1Fh.
  // Program IOMMUL2::RIOMMU_MULTI_INV_LIM=1Fh.
  GNB_ENTRY_RMW (
    ALL_NBIO_TYPE,
    SMN_L2_RIOMMU_INV_CNTRL_ADDRESS,
    L2_RIOMMU_INV_CNTRL_RIOMMU_MULTI_INVACK_LIM_MASK |
    L2_RIOMMU_INV_CNTRL_RIOMMU_MULTI_INV_LIM_MASK,
    (0x0 << L2_RIOMMU_INV_CNTRL_RIOMMU_MULTI_INVACK_LIM_OFFSET) |
    (0x0 << L2_RIOMMU_INV_CNTRL_RIOMMU_MULTI_INV_LIM_OFFSET)
    ),
  //
  // PPR 14.3.1.2.4 : IOMMU Clock Gating
  //
  GNB_ENTRY_RMW_IF_PCD_EQUAL (
    ALL_NBIO_TYPE,
    PcdToken(PcdIommuL2ClockGatingEnable),
    TRUE,
    SMN_L2_L2A_CK_GATE_CONTROL_ADDRESS,
    L2_L2A_CK_GATE_CONTROL_CKGateL2ARegsDisable_MASK | L2_L2A_CK_GATE_CONTROL_CKGateL2ADynamicDisable_MASK | L2_L2A_CK_GATE_CONTROL_CKGateL2ACacheDisable_MASK,
    (0x0 << L2_L2A_CK_GATE_CONTROL_CKGateL2ARegsDisable_OFFSET) |
    (0x0 << L2_L2A_CK_GATE_CONTROL_CKGateL2ADynamicDisable_OFFSET) |
    (0x0 << L2_L2A_CK_GATE_CONTROL_CKGateL2ACacheDisable_OFFSET)
    ),
  // set default of L2_L2B_CK_GATE_CONTROL_CKGateL2BCacheDisable to 1
  GNB_ENTRY_RMW (
    ALL_NBIO_TYPE,
    SMN_L2_L2B_CK_GATE_CONTROL_ADDRESS,
    L2_L2B_CK_GATE_CONTROL_CKGateL2BCacheDisable_MASK,
    (0x1 << L2_L2B_CK_GATE_CONTROL_CKGateL2BCacheDisable_OFFSET)
    ),
  GNB_ENTRY_RMW_IF_PCD_EQUAL (
    ALL_NBIO_TYPE,
    PcdToken(PcdIommuL2ClockGatingEnable),
    TRUE,
    SMN_L2_L2B_CK_GATE_CONTROL_ADDRESS,
    L2_L2B_CK_GATE_CONTROL_CKGateL2BRegsDisable_MASK | L2_L2B_CK_GATE_CONTROL_CKGateL2BDynamicDisable_MASK |
    L2_L2B_CK_GATE_CONTROL_CKGateL2BMiscDisable_MASK | L2_L2B_CK_GATE_CONTROL_CKGateL2BCacheDisable_MASK,
    (0x0 << L2_L2B_CK_GATE_CONTROL_CKGateL2BRegsDisable_OFFSET) |
    (0x0 << L2_L2B_CK_GATE_CONTROL_CKGateL2BDynamicDisable_OFFSET) |
    (0x0 << L2_L2B_CK_GATE_CONTROL_CKGateL2BMiscDisable_OFFSET) |
    (0x0 << L2_L2B_CK_GATE_CONTROL_CKGateL2BCacheDisable_OFFSET)
    ),
// IOMMU L1 clock gating
  // IOAGR
  GNB_ENTRY_RMW_IF_PCD_EQUAL (
    ALL_NBIO_TYPE,
    PcdToken(PcdIommuL1ClockGatingEnable),
    TRUE,
    SMN_IOAGR_L1_CLKCNTRL_0_ADDRESS,
    L1_CLKCNTRL_0_L1_CLKGATE_HYSTERESIS_MASK |
    L1_CLKCNTRL_0_L1_DMA_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_CACHE_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_CPSLV_CLKGATE_EN_MASK |
    L1_CLKCNTRL_0_L1_PERF_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_MEMORY_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_REG_CLKGATE_EN_MASK |
    L1_CLKCNTRL_0_L1_HOSTREQ_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_DMARSP_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_HOSTRSP_CLKGATE_EN_MASK |
    L1_CLKCNTRL_0_L1_L2_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_SION_PERF_CLKGATE_EN_MASK,
    (0x20 << L1_CLKCNTRL_0_L1_CLKGATE_HYSTERESIS_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_DMA_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_CACHE_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_CPSLV_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_PERF_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_MEMORY_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_REG_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_HOSTREQ_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_DMARSP_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_HOSTRSP_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_L2_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_SION_PERF_CLKGATE_EN_OFFSET)
    ),
// IOAGR IOMMUL1::L1_SDP-CLKREQ_CNTRL::HW_PG_WAKEUP_EN_DMA  = 0x1
// IOAGR IOMMUL1::L1_SDP-CLKREQ_CNTRL::HW_PG_WAKEUP_EN_HOST  = 0x1
  GNB_ENTRY_RMW (
    ALL_NBIO_TYPE,
    SMN_IOAGR_L1_SDP_CLKREQ_CNTRL_ADDRESS,
    L1_SDP_CLKREQ_CNTRL_HW_PG_WAKEUP_EN_DMA_MASK | L1_SDP_CLKREQ_CNTRL_HW_PG_WAKEUP_EN_HOST_MASK,
    (1 << L1_SDP_CLKREQ_CNTRL_HW_PG_WAKEUP_EN_DMA_OFFSET) |
    (1 << L1_SDP_CLKREQ_CNTRL_HW_PG_WAKEUP_EN_HOST_OFFSET)
    ),
//
  // PCIE0
  GNB_ENTRY_RMW_IF_PCD_EQUAL (
    ALL_NBIO_TYPE,
    PcdToken(PcdIommuL1ClockGatingEnable),
    TRUE,
    SMN_PCIE0_L1_CLKCNTRL_0_ADDRESS,
    L1_CLKCNTRL_0_L1_CLKGATE_HYSTERESIS_MASK |
    L1_CLKCNTRL_0_L1_DMA_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_CACHE_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_CPSLV_CLKGATE_EN_MASK |
    L1_CLKCNTRL_0_L1_PERF_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_MEMORY_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_REG_CLKGATE_EN_MASK |
    L1_CLKCNTRL_0_L1_HOSTREQ_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_DMARSP_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_HOSTRSP_CLKGATE_EN_MASK |
    L1_CLKCNTRL_0_L1_L2_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_SION_PERF_CLKGATE_EN_MASK,
    (0x20 << L1_CLKCNTRL_0_L1_CLKGATE_HYSTERESIS_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_DMA_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_CACHE_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_CPSLV_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_PERF_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_MEMORY_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_REG_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_HOSTREQ_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_DMARSP_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_HOSTRSP_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_L2_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_SION_PERF_CLKGATE_EN_OFFSET)
    ),
  // PCIE0 IOMMUL1::L1_SDP-CLKREQ_CNTRL::HW_PG_WAKEUP_EN_DMA  = 0x1
  GNB_ENTRY_RMW (
    ALL_NBIO_TYPE,
    SMN_PCIE0_L1_SDP_CLKREQ_CNTRL_ADDRESS,
    L1_SDP_CLKREQ_CNTRL_HW_PG_WAKEUP_EN_DMA_MASK,
    (1 << L1_SDP_CLKREQ_CNTRL_HW_PG_WAKEUP_EN_DMA_OFFSET)
    ),
//
  //
  // PPR 14.3.1.2.5 : IOMMU SMI Filtering
  //
  // Implement at a platform level

  // Configure IOMMU Power Island
  // Hide IOMMU function if disabled
  GNB_ENTRY_PROPERTY_RMW (
    TABLE_PROPERTY_IOMMU_DISABLED,
    ONE_ADDR_TYPE,
    SMN_CFG_IOHC_PCI_ADDRESS,
    CFG_IOHC_PCI_CFG_IOHC_PCI_Dev0Fn2RegEn_MASK,
    (0x0 << CFG_IOHC_PCI_CFG_IOHC_PCI_Dev0Fn2RegEn_OFFSET)
    ),

  //
  // PPR 14.3.1.2.6 : IOMMU L2 Dynamic Power Gating
  //
  // Program IOMMUL2::L2_PWRGATE_CNTRL_REG_0[IP_PG_thres] = 800h.
  GNB_ENTRY_RMW_IF_PCD_EQUAL (
    ALL_NBIO_TYPE,
    PcdToken(PcdCfgIOMMUDynamicPgEnable),
    TRUE,
    SMN_L2_PWRGATE_CNTRL_REG_0_ADDRESS,
    L2_PWRGATE_CNTRL_REG_0_IP_PG_thres_MASK,
    (0x800 << L2_PWRGATE_CNTRL_REG_0_IP_PG_thres_OFFSET)
    ),
  // Program IOMMUL2::L2_PWRGATE_CNTRL_REG_3[IP_PG_en] = 1h.
  GNB_ENTRY_RMW_IF_PCD_EQUAL (
    ALL_NBIO_TYPE,
    PcdToken(PcdCfgIOMMUDynamicPgEnable),
    TRUE,
    SMN_L2_PWRGATE_CNTRL_REG_3_ADDRESS,
    L2_PWRGATE_CNTRL_REG_3_IP_PG_en_MASK,
    (0x1 << L2_PWRGATE_CNTRL_REG_3_IP_PG_en_OFFSET)
    ),
  // Program IOMMUL2::L2_L2A_MEMPWR_GATE_1[L2AREG_CACHE_PGMEM_SEL] = 1h.
  GNB_ENTRY_RMW_IF_PCD_EQUAL (
    ALL_NBIO_TYPE,
    PcdToken(PcdCfgIOMMUDynamicPgEnable),
    TRUE,
    SMN_L2_L2A_MEMPWR_GATE_1_ADDRESS,
    L2_L2A_MEMPWR_GATE_1_L2AREG_CACHE_PGMEM_SEL_MASK,
    (0x1 << L2_L2A_MEMPWR_GATE_1_L2AREG_CACHE_PGMEM_SEL_OFFSET)
    ),
  // Program IOMMUL2::L2_L2B_MEMPWR_GATE_1[L2BREG_CACHE_PGMEM_SEL] = 1h.
  GNB_ENTRY_RMW_IF_PCD_EQUAL (
    ALL_NBIO_TYPE,
    PcdToken(PcdCfgIOMMUDynamicPgEnable),
    TRUE,
    SMN_L2_L2B_MEMPWR_GATE_1_ADDRESS,
    L2_L2B_MEMPWR_GATE_1_L2BREG_CACHE_PGMEM_SEL_MASK,
    (0x1 << L2_L2B_MEMPWR_GATE_1_L2BREG_CACHE_PGMEM_SEL_OFFSET)
    ),

  //
  // PPR 14.3.1.2.7 : IOMMU L2 Memory Power Gating
  //
  // Program IOMMUL2::L2_L2A_MEMPWR_GATE_1[L2AREG_LS_EN] = 1h.
  // Program IOMMUL2::L2_L2A_MEMPWR_GATE_1[L2AREG_DS_EN] = 1h.
  // Program IOMMUL2::L2_L2A_MEMPWR_GATE_1[L2AREG_SD_EN] = 1h.
  GNB_ENTRY_RMW_IF_PCD_EQUAL (
    ALL_NBIO_TYPE,
    PcdToken(PcdCfgIOMMUL2MemoryPGEnable),
    TRUE,
    SMN_L2_L2A_MEMPWR_GATE_1_ADDRESS,
    L2_L2A_MEMPWR_GATE_1_L2AREG_LS_EN_MASK |
    L2_L2A_MEMPWR_GATE_1_L2AREG_DS_EN_MASK |
    L2_L2A_MEMPWR_GATE_1_L2AREG_SD_EN_MASK,
    (0x1 << L2_L2A_MEMPWR_GATE_1_L2AREG_LS_EN_OFFSET) |
    (0x1 << L2_L2A_MEMPWR_GATE_1_L2AREG_DS_EN_OFFSET) |
    (0x1 << L2_L2A_MEMPWR_GATE_1_L2AREG_SD_EN_OFFSET)
    ),
  // Program IOMMUL2::L2_L2B_MEMPWR_GATE_1[L2BREG_LS_EN] = 1h.
  // Program IOMMUL2::L2_L2B_MEMPWR_GATE_1[L2BREG_DS_EN] = 1h.
  // Program IOMMUL2::L2_L2B_MEMPWR_GATE_1[L2BREG_SD_EN] = 1h.
  GNB_ENTRY_RMW_IF_PCD_EQUAL (
    ALL_NBIO_TYPE,
    PcdToken(PcdCfgIOMMUL2MemoryPGEnable),
    TRUE,
    SMN_L2_L2B_MEMPWR_GATE_1_ADDRESS,
    L2_L2B_MEMPWR_GATE_1_L2BREG_LS_EN_MASK |
    L2_L2B_MEMPWR_GATE_1_L2BREG_DS_EN_MASK |
    L2_L2B_MEMPWR_GATE_1_L2BREG_SD_EN_MASK,
    (0x1 << L2_L2B_MEMPWR_GATE_1_L2BREG_LS_EN_OFFSET) |
    (0x1 << L2_L2B_MEMPWR_GATE_1_L2BREG_DS_EN_OFFSET) |
    (0x1 << L2_L2B_MEMPWR_GATE_1_L2BREG_SD_EN_OFFSET)
    ),
  // Program IOMMUL2::L2_TW_CONTROL[TWForceCoherent] = 1h.
  GNB_ENTRY_RMW (
    ALL_NBIO_TYPE,
    SMN_L2_TW_CONTROL_ADDRESS,
    L2_TW_CONTROL_TWForceCoherent_MASK,
    (1 << L2_TW_CONTROL_TWForceCoherent_OFFSET)
    ),
  GNB_ENTRY_TERMINATE
};

GNB_TABLE ROMDATA GnbIommuEnvInitTableBx [] = {
  GNB_ENTRY_RMW_IF_PCD_EQUAL (
    ALL_NBIO_TYPE,
    PcdToken(PcdIommuL1ClockGatingEnable),
    TRUE,
    SMN_PCIE2_L1_CLKCNTRL_0_ADDRESS,
    L1_CLKCNTRL_0_L1_CLKGATE_HYSTERESIS_MASK |
    L1_CLKCNTRL_0_L1_DMA_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_CACHE_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_CPSLV_CLKGATE_EN_MASK |
    L1_CLKCNTRL_0_L1_PERF_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_MEMORY_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_REG_CLKGATE_EN_MASK |
    L1_CLKCNTRL_0_L1_HOSTREQ_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_DMARSP_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_HOSTRSP_CLKGATE_EN_MASK |
    L1_CLKCNTRL_0_L1_L2_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_SION_PERF_CLKGATE_EN_MASK,
    (0x20 << L1_CLKCNTRL_0_L1_CLKGATE_HYSTERESIS_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_DMA_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_CACHE_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_CPSLV_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_PERF_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_MEMORY_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_REG_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_HOSTREQ_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_DMARSP_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_HOSTRSP_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_L2_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_SION_PERF_CLKGATE_EN_OFFSET)
    ),
  GNB_ENTRY_RMW_IF_PCD_EQUAL (
    ALL_NBIO_TYPE,
    PcdToken(PcdIommuL1ClockGatingEnable),
    TRUE,
    SMN_PCIE3_L1_CLKCNTRL_0_ADDRESS,
    L1_CLKCNTRL_0_L1_CLKGATE_HYSTERESIS_MASK |
    L1_CLKCNTRL_0_L1_DMA_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_CACHE_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_CPSLV_CLKGATE_EN_MASK |
    L1_CLKCNTRL_0_L1_PERF_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_MEMORY_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_REG_CLKGATE_EN_MASK |
    L1_CLKCNTRL_0_L1_HOSTREQ_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_DMARSP_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_HOSTRSP_CLKGATE_EN_MASK |
    L1_CLKCNTRL_0_L1_L2_CLKGATE_EN_MASK | L1_CLKCNTRL_0_L1_SION_PERF_CLKGATE_EN_MASK,
    (0x20 << L1_CLKCNTRL_0_L1_CLKGATE_HYSTERESIS_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_DMA_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_CACHE_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_CPSLV_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_PERF_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_MEMORY_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_REG_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_HOSTREQ_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_DMARSP_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_HOSTRSP_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_L2_CLKGATE_EN_OFFSET) |
    (0x1 << L1_CLKCNTRL_0_L1_SION_PERF_CLKGATE_EN_OFFSET)
    ),
  GNB_ENTRY_TERMINATE
};
