/*****************************************************************************
 *
 * Copyright (C) 2008-2022 Advanced Micro Devices, Inc. All rights reserved.
 *
 *******************************************************************************
 **/

#ifndef _NBIO_IOHC_TABLE_H_
#define _NBIO_IOHC_TABLE_H_

// --------------------------------------------------
// 14.1.4.4 Enabling Peer-to-Peer
// --------------------------------------------------

  // IOHC::IOHC_FEATURE_CNTL[P2P_mode] = 1
  // IOHC::PCIE_VDM_CNTL2[VdmP2pMode] = 1
  #define NBIO_IOHC_P2P_TBL \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_IOHC_FEATURE_CNTL_ADDRESS, \
      IOHC_FEATURE_CNTL_P2P_mode_MASK, \
      (0x1 << IOHC_FEATURE_CNTL_P2P_mode_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_PCIE_VDM_CNTL2_ADDRESS, \
      PCIE_VDM_CNTL2_VdmP2pMode_MASK, \
      (0x1 << PCIE_VDM_CNTL2_VdmP2pMode_OFFSET) \
      ),
  // End of NBIO_IOHC_P2P_TBL


// --------------------------------------------------
// 14.1.4.6 PCI Express Configuration Cycle Hardware Retry on CRS
// --------------------------------------------------

  //IOHC::IOHC_PCIE_CRS_Count[CrsDelayCount] = 0x6
  //For Hot-plug slots only: IOHC::IOHC_PCIE_CRS_Count[CrsLimitCount] = 0x262 (Configured later)
  //For non-Hot-plug slots: IOHC::IOHC_PCIE_CRS_Count[CrsLimitCount] = 0x6
  //For each bridge, IOHC::IOHC_Bridge_CNTL[CrsEnable] must be set. (a part of PcieControlPorts function)
  #define NBIO_IOHC_CRS_TBL \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_IOHC_PCIE_CRS_Count_ADDRESS, \
      IOHC_PCIE_CRS_Count_CrsDelayCount_MASK, \
      0x6 << IOHC_PCIE_CRS_Count_CrsDelayCount_OFFSET \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_IOHC_PCIE_CRS_Count_ADDRESS, \
      IOHC_PCIE_CRS_Count_CrsLimitCount_MASK, \
      0x6 << IOHC_PCIE_CRS_Count_CrsLimitCount_OFFSET \
      ), \
  // End of NBIO_IOHC_P2P_TBL

// --------------------------------------------------
// 14.1.4.9 IOHC Clock Gating
// --------------------------------------------------

  // IOHC::SMN_IOHC_GLUE_CG_LCLK_CTRL_0[SOFT_OVERRIDE_CLK9~0]=0h
  // IOHC::SMN_IOHC_GLUE_CG_LCLK_CTRL_1[SOFT_OVERRIDE_CLK9~0]=0h
  // IOAGR::IOAGR_GLUE_CG_LCLK_CTRL_0[[SOFT_OVERRIDE_CLK9~0]=0h
  // IOAGR::IOAGR_GLUE_CG_LCLK_CTRL_1[SOFT_OVERRIDE_CLK3~0]=0h
  // IOAPIC::IOAPIC_GLUE_CG_LCLK_CTRL_0[SOFT_OVERRIDE_CLK1~0]=0h
  // SST::SST(x)_CLOCK_CTRL[RXCLKGATEEn] = 1h
  // SST::SST(x)_CLOCK_CTRL[TXCLKGATEEn] = 1h
  // SST::SST(x)_CLOCK_CTRL[PCTRL_IDLE_TIME] = 0xF0h
  // SST(x)::SION_WRAPPER_CFG_SSTSION_GLUE_CG_LCLK_CTRL_SOFT_OVERRIDE_CLK[CFG_SSTSION_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK4] = 1h
  #define NBIO_IOHC_CLOCK_GATING_TBL \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdIOHCClkGatingSupport), \
      TRUE, \
      SMN_IOHC_GLUE_CG_LCLK_CTRL_0_ADDRESS, \
      IOHC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK9_MASK | \
      IOHC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK8_MASK | \
      IOHC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK7_MASK | \
      IOHC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK6_MASK | \
      IOHC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK5_MASK | \
      IOHC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK4_MASK | \
      IOHC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK3_MASK | \
      IOHC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK2_MASK | \
      IOHC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK1_MASK | \
      IOHC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK0_MASK, \
      (0x0 << IOHC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK9_OFFSET) | \
      (0x0 << IOHC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK8_OFFSET) | \
      (0x0 << IOHC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK7_OFFSET) | \
      (0x0 << IOHC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK6_OFFSET) | \
      (0x0 << IOHC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK5_OFFSET) | \
      (0x0 << IOHC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK4_OFFSET) | \
      (0x0 << IOHC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK3_OFFSET) | \
      (0x0 << IOHC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK2_OFFSET) | \
      (0x0 << IOHC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK1_OFFSET) | \
      (0x0 << IOHC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK0_OFFSET) \
      ), \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdIOHCClkGatingSupport), \
      TRUE, \
      SMN_IOHC_GLUE_CG_LCLK_CTRL_1_ADDRESS, \
      IOHC_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK9_MASK | \
      IOHC_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK8_MASK | \
      IOHC_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK7_MASK | \
      IOHC_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK6_MASK | \
      IOHC_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK5_MASK | \
      IOHC_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK4_MASK | \
      IOHC_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK3_MASK | \
      IOHC_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK2_MASK | \
      IOHC_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK1_MASK | \
      IOHC_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK0_MASK, \
      (0x0 << IOHC_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK9_OFFSET) | \
      (0x0 << IOHC_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK8_OFFSET) | \
      (0x0 << IOHC_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK7_OFFSET) | \
      (0x0 << IOHC_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK6_OFFSET) | \
      (0x0 << IOHC_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK5_OFFSET) | \
      (0x0 << IOHC_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK4_OFFSET) | \
      (0x0 << IOHC_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK3_OFFSET) | \
      (0x0 << IOHC_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK2_OFFSET) | \
      (0x0 << IOHC_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK1_OFFSET) | \
      (0x0 << IOHC_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK0_OFFSET) \
      ), \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdIOHCClkGatingSupport), \
      TRUE, \
      SMN_IOAGR_GLUE_CG_LCLK_CTRL_0_ADDRESS, \
      IOAGR_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK9_MASK | \
      IOAGR_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK8_MASK | \
      IOAGR_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK7_MASK | \
      IOAGR_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK6_MASK | \
      IOAGR_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK5_MASK | \
      IOAGR_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK4_MASK | \
      IOAGR_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK3_MASK | \
      IOAGR_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK2_MASK | \
      IOAGR_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK1_MASK | \
      IOAGR_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK0_MASK, \
      (0x0 << IOAGR_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK9_OFFSET) | \
      (0x0 << IOAGR_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK8_OFFSET) | \
      (0x0 << IOAGR_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK7_OFFSET) | \
      (0x0 << IOAGR_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK6_OFFSET) | \
      (0x0 << IOAGR_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK5_OFFSET) | \
      (0x0 << IOAGR_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK4_OFFSET) | \
      (0x0 << IOAGR_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK3_OFFSET) | \
      (0x0 << IOAGR_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK2_OFFSET) | \
      (0x0 << IOAGR_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK1_OFFSET) | \
      (0x0 << IOAGR_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK0_OFFSET) \
      ), \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdIOHCClkGatingSupport), \
      TRUE, \
      SMN_IOAGR_GLUE_CG_LCLK_CTRL_1_ADDRESS, \
      IOAGR_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK3_MASK | \
      IOAGR_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK2_MASK | \
      IOAGR_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK1_MASK | \
      IOAGR_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK0_MASK, \
      (0x0 << IOAGR_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK3_OFFSET) | \
      (0x0 << IOAGR_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK2_OFFSET) | \
      (0x0 << IOAGR_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK1_OFFSET) | \
      (0x0 << IOAGR_GLUE_CG_LCLK_CTRL_1_SOFT_OVERRIDE_CLK0_OFFSET) \
      ), \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdIOHCClkGatingSupport), \
      TRUE, \
      SMN_IOAPIC_GLUE_CG_LCLK_CTRL_0_ADDRESS, \
      IOAPIC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK1_MASK | \
      IOAPIC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK0_MASK, \
      (0x0 << IOAPIC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK1_OFFSET) | \
      (0x0 << IOAPIC_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK0_OFFSET) \
      ), \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdCfgSstunlClkGating), \
      TRUE, \
      SMN_SST0_SST_CLOCK_CTRL_ADDRESS, \
      SST_CLOCK_CTRL_TXCLKGATEEn_MASK | \
      SST_CLOCK_CTRL_RXCLKGATEEn_MASK | \
      SST_CLOCK_CTRL_PCTRL_IDLE_TIME_MASK, \
      (0x1 << SST_CLOCK_CTRL_TXCLKGATEEn_OFFSET) | \
      (0x1 << SST_CLOCK_CTRL_RXCLKGATEEn_OFFSET) | \
      (0xF0 << SST_CLOCK_CTRL_PCTRL_IDLE_TIME_OFFSET) \
      ), \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdCfgSstunlClkGating), \
      TRUE, \
      SMN_SST1_SST_CLOCK_CTRL_ADDRESS, \
      SST_CLOCK_CTRL_TXCLKGATEEn_MASK | \
      SST_CLOCK_CTRL_RXCLKGATEEn_MASK | \
      SST_CLOCK_CTRL_PCTRL_IDLE_TIME_MASK, \
      (0x1 << SST_CLOCK_CTRL_TXCLKGATEEn_OFFSET) | \
      (0x1 << SST_CLOCK_CTRL_RXCLKGATEEn_OFFSET) | \
      (0xF0 << SST_CLOCK_CTRL_PCTRL_IDLE_TIME_OFFSET) \
      ), \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdCfgSstunlClkGating), \
      TRUE, \
      SMN_SST0_SION_WRAPPER_CFG_SSTSION_GLUE_CG_LCLK_CTRL_SOFT_OVERRIDE_CLK_ADDRESS, \
      SION_WRAPPER_CFG_SSTSION_GLUE_CG_LCLK_CTRL_SOFT_OVERRIDE_CLK_CFG_SSTSION_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK4_MASK, \
      (0x1 << SION_WRAPPER_CFG_SSTSION_GLUE_CG_LCLK_CTRL_SOFT_OVERRIDE_CLK_CFG_SSTSION_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK4_OFFSET) \
      ), \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdCfgSstunlClkGating), \
      TRUE, \
      SMN_SST1_SION_WRAPPER_CFG_SSTSION_GLUE_CG_LCLK_CTRL_SOFT_OVERRIDE_CLK_ADDRESS, \
      SION_WRAPPER_CFG_SSTSION_GLUE_CG_LCLK_CTRL_SOFT_OVERRIDE_CLK_CFG_SSTSION_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK4_MASK, \
      (0x1 << SION_WRAPPER_CFG_SSTSION_GLUE_CG_LCLK_CTRL_SOFT_OVERRIDE_CLK_CFG_SSTSION_GLUE_CG_LCLK_CTRL_0_SOFT_OVERRIDE_CLK4_OFFSET) \
      ),
  // End of NBIO_IOHC_CLOCK_GATING_TBL


// --------------------------------------------------
// 14.1.4.10 IOHC Power Gating
// --------------------------------------------------

  // IOHC::IOHC_PGMST_CNTL[CFG_PG_EN] = 0x1
  // IOAGR::IOAGR_PGMST_CNTL[CFG_PG_EN] = 0x1
  // IOHC::IOHC_EARLY_WAKE_UP_EN[DMAEnableEarlyClkReq] = 0x1
  // IOAGR::IOAGR_EARLY_WAKE_UP_EN[DMAEnableEarlyClkReq] = 0x1
  // This is not expected to affect APU though, not need to update following registers.
  // IOHC::IOHC_PGMST_CNTL[CFG_FW_PG_EXIT_EN] = 0x3
  // IOAGR::IOAGR_PGMST_CNTL[CFG_FW_PG_EXIT_EN] = 0x3
  #define NBIO_IOHC_POWER_GATING_TBL \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdIOHCPgEnable), \
      TRUE, \
      SMN_IOHC_PGMST_CNTL_ADDRESS, \
      IOHC_PGMST_CNTL_CFG_PG_EN_MASK, \
      (0x1 << IOHC_PGMST_CNTL_CFG_PG_EN_OFFSET) \
      ), \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdIOAGRPgEnable), \
      TRUE, \
      SMN_IOAGR_PGMST_CNTL_ADDRESS, \
      IOAGR_PGMST_CNTL_CFG_PG_EN_MASK, \
      (0x1 << IOAGR_PGMST_CNTL_CFG_PG_EN_OFFSET) \
      ), \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdIOHCPgEnable), \
      TRUE, \
      SMN_IOHC_EARLY_WAKE_UP_EN_ADDRESS, \
      IOHC_EARLY_WAKE_UP_EN_DMAEnableEarlyClkReq_MASK, \
      (0x1 << IOHC_EARLY_WAKE_UP_EN_DMAEnableEarlyClkReq_OFFSET) \
      ), \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdIOAGRPgEnable), \
      TRUE, \
      SMN_IOAGR_EARLY_WAKE_UP_EN_ADDRESS, \
      IOAGR_EARLY_WAKE_UP_EN_DMAEnableEarlyClkReq_MASK, \
      (0x1 << IOAGR_EARLY_WAKE_UP_EN_DMAEnableEarlyClkReq_OFFSET) \
      ),
  // End of NBIO_IOHC_POWER_GATING_TBL


// --------------------------------------------------
// 14.1.4.11 IOHC Arbitration Control
// --------------------------------------------------

  // IOHC::IOHC_QOS_CONTROL[VC0QoSPriority] = 0x0
  // IOHC::IOHC_QOS_CONTROL[VC1QoSPriority] = 0x0
  // IOHC::IOHC_QOS_CONTROL[VC2QoSPriority] = 0x0
  // IOHC::IOHC_QOS_CONTROL[VC3QoSPriority] = 0x0
  // IOHC::IOHC_QOS_CONTROL[VC4QoSPriority] = 0x0
  // IOHC::IOHC_QOS_CONTROL[VC5QoSPriority] = 0x7
  // IOHC::IOHC_QOS_CONTROL[VC6QoSPriority] = 0x0
  // IOHC::IOHC_QOS_CONTROL[VC7QoSPriority] = 0x0
  #define NBIO_IOHC_ARBITRATION_TBL \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_IOHC_QOS_CONTROL_ADDRESS, \
      IOHC_QOS_CONTROL_VC0QoSPriority_MASK | \
      IOHC_QOS_CONTROL_VC1QoSPriority_MASK | \
      IOHC_QOS_CONTROL_VC2QoSPriority_MASK | \
      IOHC_QOS_CONTROL_VC3QoSPriority_MASK | \
      IOHC_QOS_CONTROL_VC4QoSPriority_MASK | \
      IOHC_QOS_CONTROL_VC5QoSPriority_MASK | \
      IOHC_QOS_CONTROL_VC6QoSPriority_MASK | \
      IOHC_QOS_CONTROL_VC7QoSPriority_MASK, \
      (0x0 << IOHC_QOS_CONTROL_VC0QoSPriority_OFFSET) | \
      (0x0 << IOHC_QOS_CONTROL_VC1QoSPriority_OFFSET) | \
      (0x0 << IOHC_QOS_CONTROL_VC2QoSPriority_OFFSET) | \
      (0x0 << IOHC_QOS_CONTROL_VC3QoSPriority_OFFSET) | \
      (0x0 << IOHC_QOS_CONTROL_VC4QoSPriority_OFFSET) | \
      (0x7 << IOHC_QOS_CONTROL_VC5QoSPriority_OFFSET) | \
      (0x0 << IOHC_QOS_CONTROL_VC6QoSPriority_OFFSET) | \
      (0x0 << IOHC_QOS_CONTROL_VC7QoSPriority_OFFSET) \
      ),
  // End of NBIO_IOHC_ARBITRATION_TBL


// --------------------------------------------------
// IOHC POISON_ACTION_CONTROL
// --------------------------------------------------

  // IOHC::POISON_ACTION_CONTROL
  #define NBIO_IOHC_POISON_ACTION_TBL \
    GNB_ENTRY_RMW ( \
      ONE_ADDR_TYPE, \
      SMN_POISON_ACTION_CONTROL_ADDRESS, \
      POISON_ACTION_CONTROL_IntPoisonAPMLErrEn_MASK | \
      POISON_ACTION_CONTROL_IntPoisonLinkDisEn_MASK | \
      POISON_ACTION_CONTROL_IntPoisonSyncFloodEn_MASK, \
      (0x1 << POISON_ACTION_CONTROL_IntPoisonAPMLErrEn_OFFSET) | \
      (0x1 << POISON_ACTION_CONTROL_IntPoisonLinkDisEn_OFFSET) | \
      (0x1 << POISON_ACTION_CONTROL_IntPoisonSyncFloodEn_OFFSET) \
      ),
  // End of NBIO_IOHC_POISON_ACTION

  // IOAGR::IOAGR_SION_Client_DataPoolCredit_Alloc_Lower_n0[IOAGR_SION_Client_DataPoolCredit_Alloc_Lower~0]=2000202h
  // IOAGR::IOAGR_SION_Client_DataPoolCredit_Alloc_Upper_n0[IOAGR_SION_Client_DataPoolCredit_Alloc_Upper~0]=104000h
  // IOAGR::IOAGR_SION_Client_ReqPoolCredit_Alloc_Lower_n0[IOAGR_SION_Client_ReqPoolCredit_Alloc_Lower~0]=1000101h
  // IOAGR::IOAGR_SION_Client_ReqPoolCredit_Alloc_Upper_n0[IOAGR_SION_Client_ReqPoolCredit_Alloc_Upper~0]=104000h
  // IOAGR::IOAGR_SION_S0_Client_Req_TimeSlot_Lower_n4[IOAGR_SION_S0_Client_Req_TimeSlot_Lower~0]=60606h
  // IOAGR::IOAGR_SION_S0_Client_Req_TimeSlot_Upper_n4[IOAGR_SION_S0_Client_Req_TimeSlot_Upper~0]=7060606h
  // IOAGR::IOAGR_SION_S1_Client_Req_TimeSlot_Lower_n0[IOAGR_SION_S1_Client_Req_TimeSlot_Lower~0]=55005000h
  // IOAGR::IOAGR_SION_S1_Client_Req_TimeSlot_Upper_n0[IOAGR_SION_S1_Client_Req_TimeSlot_Upper~0]=55005500h
  // IOHC::IOHC_SION_CLIENT_DATAPOOLCREDIT_ALLOC_LOWER_n0[IOHC_SION_CLIENT_DATAPOOLCREDIT_ALLOC_LOWER~0]=1000101h
  // IOHC::IOHC_SION_CLIENT_DATAPOOLCREDIT_ALLOC_UPPER_n0[IOHC_SION_CLIENT_DATAPOOLCREDIT_ALLOC_UPPER~0]=1000701h
  // IOHC::IOHC_SION_CLIENT_REQPOOLCREDIT_ALLOC_LOWER_n0[IOHC_SION_CLIENT_REQPOOLCREDIT_ALLOC_LOWER~0]=1000101h
  // IOHC::IOHC_SION_CLIENT_REQPOOLCREDIT_ALLOC_UPPER_n0[IOHC_SION_CLIENT_REQPOOLCREDIT_ALLOC_UPPER~0]=1000601h
  // IOHC::IOHC_SION_S0_CLIENT_REQ_TIMESLOT_LOWER_n2[IOHC_SION_S0_CLIENT_REQ_TIMESLOT_LOWER~0]=66000000h
  // IOHC::IOHC_SION_S0_CLIENT_REQ_TIMESLOT_UPPER_n2[IOHC_SION_S0_CLIENT_REQ_TIMESLOT_UPPER~0]=66006600h
  // IOHC::IOHC_SION_S1_CLIENT_REQ_TIMESLOT_LOWER_n0[IOHC_SION_S1_CLIENT_REQ_TIMESLOT_LOWER~0]=35205435h
  // IOHC::IOHC_SION_S1_CLIENT_REQ_TIMESLOT_UPPER_n0[IOHC_SION_S1_CLIENT_REQ_TIMESLOT_UPPER~0]=54352054h
  // IOHC::IOHC_SION_S0_CLIENT_REQ_TIMESLOT_LOWER_n4[IOHC_SION_S0_CLIENT_REQ_TIMESLOT_LOWER~0]=66000000h
  // IOHC::IOHC_SION_S0_CLIENT_REQ_TIMESLOT_UPPER_n4[IOHC_SION_S0_CLIENT_REQ_TIMESLOT_UPPER~0]=66006600h
  // IOHC::IOHC_SION_LiveLock_WatchDog_Threshold[IOHC_SION_LiveLock_WatchDog_Threshold]=F0h
  // IOAGR::IOAGR_SION_LiveLock_WatchDog_Threshold[IOAGR_SION_LiveLock_WatchDog_Threshold]=F0h
  // CL# 1403823 - NBIO
  #define NBIO_SION_CLIENT_TBL \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_N0_IOAGR_SION_Client_DataPoolCredit_Alloc_Lower_ADDRESS, \
      IOAGR_SION_Client_DataPoolCredit_Alloc_Lower_IOAGR_SION_Client_DataPoolCredit_Alloc_Lower_MASK, \
      (0x2000202 << IOAGR_SION_Client_DataPoolCredit_Alloc_Lower_IOAGR_SION_Client_DataPoolCredit_Alloc_Lower_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_N0_IOAGR_SION_Client_DataPoolCredit_Alloc_Upper_ADDRESS, \
      IOAGR_SION_Client_DataPoolCredit_Alloc_Upper_IOAGR_SION_Client_DataPoolCredit_Alloc_Upper_MASK, \
      (0x4000 << IOAGR_SION_Client_DataPoolCredit_Alloc_Upper_IOAGR_SION_Client_DataPoolCredit_Alloc_Upper_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_N0_IOAGR_SION_Client_ReqPoolCredit_Alloc_Lower_ADDRESS, \
      IOAGR_SION_Client_ReqPoolCredit_Alloc_Lower_IOAGR_SION_Client_ReqPoolCredit_Alloc_Lower_MASK, \
      (0x1000101 << IOAGR_SION_Client_ReqPoolCredit_Alloc_Lower_IOAGR_SION_Client_ReqPoolCredit_Alloc_Lower_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_N0_IOAGR_SION_Client_ReqPoolCredit_Alloc_Upper_ADDRESS, \
      IOAGR_SION_Client_ReqPoolCredit_Alloc_Upper_IOAGR_SION_Client_ReqPoolCredit_Alloc_Upper_MASK, \
      (0x104000 << IOAGR_SION_Client_ReqPoolCredit_Alloc_Upper_IOAGR_SION_Client_ReqPoolCredit_Alloc_Upper_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_N4_IOAGR_SION_S0_Client_Req_TimeSlot_Lower_ADDRESS, \
      IOAGR_SION_S0_Client_Req_TimeSlot_Lower_IOAGR_SION_S0_Client_Req_TimeSlot_Lower_MASK, \
      (0x60606 << IOAGR_SION_S0_Client_Req_TimeSlot_Lower_IOAGR_SION_S0_Client_Req_TimeSlot_Lower_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_N4_IOAGR_SION_S0_Client_Req_TimeSlot_Upper_ADDRESS, \
      IOAGR_SION_S0_Client_Req_TimeSlot_Upper_IOAGR_SION_S0_Client_Req_TimeSlot_Upper_MASK, \
      (0x7060606 << IOAGR_SION_S0_Client_Req_TimeSlot_Upper_IOAGR_SION_S0_Client_Req_TimeSlot_Upper_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_N0_IOAGR_SION_S1_Client_Req_TimeSlot_Lower_ADDRESS, \
      IOAGR_SION_S1_Client_Req_TimeSlot_Lower_IOAGR_SION_S1_Client_Req_TimeSlot_Lower_MASK, \
      (0x55005500 << IOAGR_SION_S1_Client_Req_TimeSlot_Lower_IOAGR_SION_S1_Client_Req_TimeSlot_Lower_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_N0_IOAGR_SION_S1_Client_Req_TimeSlot_Upper_ADDRESS, \
      IOAGR_SION_S1_Client_Req_TimeSlot_Upper_IOAGR_SION_S1_Client_Req_TimeSlot_Upper_MASK, \
      (0x55005500 << IOAGR_SION_S1_Client_Req_TimeSlot_Upper_IOAGR_SION_S1_Client_Req_TimeSlot_Upper_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_N0_IOHC_SION_CLIENT_DATAPOOLCREDIT_ALLOC_LOWER_ADDRESS, \
      IOHC_SION_CLIENT_DATAPOOLCREDIT_ALLOC_LOWER_DataPoolCredit_Alloc_Lower_MASK, \
      (0x1000101 << IOHC_SION_CLIENT_DATAPOOLCREDIT_ALLOC_LOWER_DataPoolCredit_Alloc_Lower_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_N0_IOHC_SION_CLIENT_DATAPOOLCREDIT_ALLOC_UPPER_ADDRESS, \
      IOHC_SION_CLIENT_DATAPOOLCREDIT_ALLOC_UPPER_DataPoolCredit_Alloc_Upper_MASK, \
      (0x1000701 << IOHC_SION_CLIENT_DATAPOOLCREDIT_ALLOC_UPPER_DataPoolCredit_Alloc_Upper_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_N0_IOHC_SION_CLIENT_REQPOOLCREDIT_ALLOC_LOWER_ADDRESS, \
      IOHC_SION_CLIENT_REQPOOLCREDIT_ALLOC_LOWER_ReqPoolCredit_Alloc_Lower_MASK, \
      (0x1000101 << IOHC_SION_CLIENT_REQPOOLCREDIT_ALLOC_LOWER_ReqPoolCredit_Alloc_Lower_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_N0_IOHC_SION_CLIENT_REQPOOLCREDIT_ALLOC_UPPER_ADDRESS, \
      IOHC_SION_CLIENT_REQPOOLCREDIT_ALLOC_UPPER_ReqPoolCredit_Alloc_Upper_MASK, \
      (0x1000601 << IOHC_SION_CLIENT_REQPOOLCREDIT_ALLOC_UPPER_ReqPoolCredit_Alloc_Upper_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_N2_IOHC_SION_S0_CLIENT_REQ_TIMESLOT_LOWER_ADDRESS, \
      IOHC_SION_S0_CLIENT_REQ_TIMESLOT_LOWER_Req_TimeSlot_Lower_MASK, \
      (0x66000000 << IOHC_SION_S0_CLIENT_REQ_TIMESLOT_LOWER_Req_TimeSlot_Lower_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_N2_IOHC_SION_S0_CLIENT_REQ_TIMESLOT_UPPER_ADDRESS, \
      IOHC_SION_S0_CLIENT_REQ_TIMESLOT_UPPER_Req_TimeSlot_Upper_MASK, \
      (0x66006600 << IOHC_SION_S0_CLIENT_REQ_TIMESLOT_UPPER_Req_TimeSlot_Upper_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_N0_IOHC_SION_S1_CLIENT_REQ_TIMESLOT_LOWER_ADDRESS, \
      IOHC_SION_S1_CLIENT_REQ_TIMESLOT_LOWER_Req_TimeSlot_Lower_MASK, \
      (0x35205435 << IOHC_SION_S1_CLIENT_REQ_TIMESLOT_LOWER_Req_TimeSlot_Lower_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_N0_IOHC_SION_S1_CLIENT_REQ_TIMESLOT_UPPER_ADDRESS, \
      IOHC_SION_S1_CLIENT_REQ_TIMESLOT_UPPER_Req_TimeSlot_Upper_MASK, \
      (0x54352054 << IOHC_SION_S1_CLIENT_REQ_TIMESLOT_UPPER_Req_TimeSlot_Upper_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_IOAGR_SION_LiveLock_WatchDog_Threshold_ADDRESS, \
      IOAGR_SION_LiveLock_WatchDog_Threshold_IOAGR_SION_LiveLock_WatchDog_Threshold_MASK, \
      (0xF0 << IOAGR_SION_LiveLock_WatchDog_Threshold_IOAGR_SION_LiveLock_WatchDog_Threshold_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_IOHC_SION_LiveLock_WatchDog_Threshold_ADDRESS, \
      IOHC_SION_LiveLock_WatchDog_Threshold_IOHC_SION_LiveLock_WatchDog_Threshold_MASK, \
      (0xF0 << IOHC_SION_LiveLock_WatchDog_Threshold_IOHC_SION_LiveLock_WatchDog_Threshold_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_N4_IOHC_SION_S0_CLIENT_REQ_TIMESLOT_LOWER_ADDRESS, \
      IOHC_SION_S0_CLIENT_REQ_TIMESLOT_LOWER_Req_TimeSlot_Lower_MASK, \
      (0x66000000 << IOHC_SION_S0_CLIENT_REQ_TIMESLOT_LOWER_Req_TimeSlot_Lower_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_N4_IOHC_SION_S0_CLIENT_REQ_TIMESLOT_UPPER_ADDRESS, \
      IOHC_SION_S0_CLIENT_REQ_TIMESLOT_UPPER_Req_TimeSlot_Upper_MASK, \
      (0x66006600 << IOHC_SION_S0_CLIENT_REQ_TIMESLOT_UPPER_Req_TimeSlot_Upper_OFFSET) \
      ), \
  // End of NBIO_SION_CLIENT_TBL

#endif /* _NBIO_IOHC_TABLE_H_ */
