/*****************************************************************************
*
 * Copyright (C) 2008-2022 Advanced Micro Devices, Inc. All rights reserved.
 *
*******************************************************************************
*
*/
/*----------------------------------------------------------------------------------------
 *                             M O D U L E S    U S E D
 *----------------------------------------------------------------------------------------
 */
#include  <Library/NbioTableBlastLib.h>
#include  <GnbRegistersRMB.h>
#include  <Filecode.h>

#define FILECODE        NBIO_NBIOBASE_RN_PEI_NBIOTABLES_FILECODE

/*----------------------------------------------------------------------------------------
 *                   D E F I N I T I O N S    A N D    M A C R O S
 *----------------------------------------------------------------------------------------
 */

/*----------------------------------------------------------------------------------------
 *                  T Y P E D E F S     A N D     S T R U C T U  R E S
 *----------------------------------------------------------------------------------------
 */


/*----------------------------------------------------------------------------------------
 *           P R O T O T Y P E S     O F     L O C A L     F U  N C T I O N S
 *----------------------------------------------------------------------------------------
 */


/*----------------------------------------------------------------------------------------
 *           T A B L E S
 *----------------------------------------------------------------------------------------
 */


/*----------------------------------------------------------------------------------------
 *           P R O T O T Y P E S     O F     L O C A L     F U  N C T I O N S
 *----------------------------------------------------------------------------------------
 *
  */

GNB_TABLE ROMDATA GnbEarlyInitB0Table [] = {
// --------------------------------------------------
// PCIe Memory Power Gating in L1 --- for Deep Sleep
// --------------------------------------------------
  //  PCIE_CNTL2 :: SLV_MEM_DS_EN = 1
  //  PCIE_TX_POWER_CTRL_1 :: MST_MEM_DS_EN = 1
  //  PCIE_TX_POWER_CTRL_1 :: REPLAY_MEM_DS_EN = 1
  //  PCIE_RX_CNTL2 :: SLVCPL_MEM_DS_EN =1
    // GNB_ENTRY_RMW (
    //   ALL_NBIO_TYPE,
    //   SMN_PCIE2_PCIE_CNTL2_ADDRESS,
    //   PCIE_CNTL2_SLV_MEM_DS_EN_MASK,
    //   (1 << PCIE_CNTL2_SLV_MEM_DS_EN_OFFSET)
    //   ),
    // GNB_ENTRY_RMW (
    //   ALL_NBIO_TYPE,
    //   SMN_PCIE3_PCIE_CNTL2_ADDRESS,
    //   PCIE_CNTL2_SLV_MEM_DS_EN_MASK,
    //   (1 << PCIE_CNTL2_SLV_MEM_DS_EN_OFFSET)
    //   ),
    // GNB_ENTRY_RMW (
    //   ALL_NBIO_TYPE,
    //   SMN_PCIE2_PCIE_TX_POWER_CTRL_1_ADDRESS,
    //   (PCIE_TX_POWER_CTRL_1_MST_MEM_DS_EN_MASK | PCIE_TX_POWER_CTRL_1_REPLAY_MEM_DS_EN_MASK),
    //   (1 << PCIE_TX_POWER_CTRL_1_MST_MEM_DS_EN_OFFSET) |
    //   (1 << PCIE_TX_POWER_CTRL_1_REPLAY_MEM_DS_EN_OFFSET)
    //   ),
    // GNB_ENTRY_RMW (
    //   ALL_NBIO_TYPE,
    //   SMN_PCIE3_PCIE_TX_POWER_CTRL_1_ADDRESS,
    //   (PCIE_TX_POWER_CTRL_1_MST_MEM_DS_EN_MASK | PCIE_TX_POWER_CTRL_1_REPLAY_MEM_DS_EN_MASK),
    //   (1 << PCIE_TX_POWER_CTRL_1_MST_MEM_DS_EN_OFFSET) |
    //   (1 << PCIE_TX_POWER_CTRL_1_REPLAY_MEM_DS_EN_OFFSET)
    //   ),
    // GNB_ENTRY_RMW (
    //   ONE_ADDR_TYPE,
    //   SMN_PCIE2_PCIE_RX_CNTL2_ADDRESS,
    //   PCIE_RX_CNTL2_SLVCPL_MEM_DS_EN_MASK,
    //   (1 << PCIE_RX_CNTL2_SLVCPL_MEM_DS_EN_OFFSET)
    //   ),
    // GNB_ENTRY_RMW (
    //   ONE_ADDR_TYPE,
    //   SMN_PCIE3_PCIE_RX_CNTL2_ADDRESS,
    //   PCIE_RX_CNTL2_SLVCPL_MEM_DS_EN_MASK,
    //   (1 << PCIE_RX_CNTL2_SLVCPL_MEM_DS_EN_OFFSET)
    //   ),

// --------------------------------------------------
// PCIe Memory Power Gating in L1 --- for Shot Down
// --------------------------------------------------
  //  PCIE_CNTL2 :: SLV_MEM_SD_EN = 1
  //  PCIE_TX_POWER_CTRL_1 :: MST_MEM_SD_EN = 1
  //  PCIE_TX_POWER_CTRL_1 :: REPLAY_MEM_SD_EN = 1
  //  PCIE_RX_CNTL2 :: SLVCPL_MEM_SD_EN =1
    // GNB_ENTRY_RMW (
    //   ALL_NBIO_TYPE,
    //   SMN_PCIE2_PCIE_CNTL2_ADDRESS,
    //   PCIE_CNTL2_SLV_MEM_SD_EN_MASK,
    //   (1 << PCIE_CNTL2_SLV_MEM_SD_EN_OFFSET)
    //   ),
    // GNB_ENTRY_RMW (
    //   ALL_NBIO_TYPE,
    //   SMN_PCIE3_PCIE_CNTL2_ADDRESS,
    //   PCIE_CNTL2_SLV_MEM_SD_EN_MASK,
    //   (1 << PCIE_CNTL2_SLV_MEM_SD_EN_OFFSET)
    //   ),
    // GNB_ENTRY_RMW (
    //   ALL_NBIO_TYPE,
    //   SMN_PCIE2_PCIE_TX_POWER_CTRL_1_ADDRESS,
    //   (PCIE_TX_POWER_CTRL_1_MST_MEM_SD_EN_MASK | PCIE_TX_POWER_CTRL_1_REPLAY_MEM_SD_EN_MASK),
    //   (1 << PCIE_TX_POWER_CTRL_1_MST_MEM_SD_EN_OFFSET) |
    //   (1 << PCIE_TX_POWER_CTRL_1_REPLAY_MEM_SD_EN_OFFSET)
    //   ),
    // GNB_ENTRY_RMW (
    //   ALL_NBIO_TYPE,
    //   SMN_PCIE3_PCIE_TX_POWER_CTRL_1_ADDRESS,
    //   (PCIE_TX_POWER_CTRL_1_MST_MEM_SD_EN_MASK | PCIE_TX_POWER_CTRL_1_REPLAY_MEM_SD_EN_MASK),
    //   (1 << PCIE_TX_POWER_CTRL_1_MST_MEM_SD_EN_OFFSET) |
    //   (1 << PCIE_TX_POWER_CTRL_1_REPLAY_MEM_SD_EN_OFFSET)
    //   ),
    // GNB_ENTRY_RMW (
    //   ALL_NBIO_TYPE,
    //   SMN_PCIE2_PCIE_RX_CNTL2_ADDRESS,
    //   PCIE_RX_CNTL2_SLVCPL_MEM_SD_EN_MASK,
    //   (1 << PCIE_RX_CNTL2_SLVCPL_MEM_SD_EN_OFFSET)
    //   ),
    // GNB_ENTRY_RMW (
    //   ALL_NBIO_TYPE,
    //   SMN_PCIE3_PCIE_RX_CNTL2_ADDRESS,
    //   PCIE_RX_CNTL2_SLVCPL_MEM_SD_EN_MASK,
    //   (1 << PCIE_RX_CNTL2_SLVCPL_MEM_SD_EN_OFFSET)
    //   ),
//
//  PCIe hot plug MSI interrupt (Clean up the pending packets before any transaction send to PCIe.)
//
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_FUNC0_PCIE2_PCIE_TX_PORT_CTRL_1_ADDRESS,
      PCIE_TX_PORT_CTRL_1_TX_FLUSH_TLP_DIS_MASK,
      (0 << PCIE_TX_PORT_CTRL_1_TX_FLUSH_TLP_DIS_OFFSET)
      ),
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_FUNC0_PCIE3_PCIE_TX_PORT_CTRL_1_ADDRESS,
      PCIE_TX_PORT_CTRL_1_TX_FLUSH_TLP_DIS_MASK,
      (0 << PCIE_TX_PORT_CTRL_1_TX_FLUSH_TLP_DIS_OFFSET)
      ),

//TX_REQUESTER_ID_DEVICE
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_FUNC0_PCIE2_PCIE_TX_REQUESTER_ID_ADDRESS,
      (PCIE_TX_REQUESTER_ID_TX_REQUESTER_ID_DEVICE_MASK | PCIE_TX_REQUESTER_ID_TX_REQUESTER_ID_FUNCTION_MASK),
      (3 << PCIE_TX_REQUESTER_ID_TX_REQUESTER_ID_DEVICE_OFFSET) |
      (1 << PCIE_TX_REQUESTER_ID_TX_REQUESTER_ID_FUNCTION_OFFSET)
      ),
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_FUNC0_PCIE3_PCIE_TX_REQUESTER_ID_ADDRESS,
      (PCIE_TX_REQUESTER_ID_TX_REQUESTER_ID_DEVICE_MASK | PCIE_TX_REQUESTER_ID_TX_REQUESTER_ID_FUNCTION_MASK),
      (4 << PCIE_TX_REQUESTER_ID_TX_REQUESTER_ID_DEVICE_OFFSET) |
      (1 << PCIE_TX_REQUESTER_ID_TX_REQUESTER_ID_FUNCTION_OFFSET)
      ),
// enable L1 - LC_CNTL/LC_CNTL4
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_FUNC0_PCIE2_PCIE_LC_L1_PM_SUBSTATE_ADDRESS,
      (PCIE_LC_CNTL_LC_L1_IMMEDIATE_ACK_MASK | PCIE_LC_CNTL_LC_PMI_TO_L1_DIS_MASK),
      (1 << PCIE_LC_CNTL_LC_L1_IMMEDIATE_ACK_OFFSET) |
      (0 << PCIE_LC_CNTL_LC_PMI_TO_L1_DIS_OFFSET)
      ),
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_FUNC0_PCIE3_PCIE_LC_L1_PM_SUBSTATE_ADDRESS,
      (PCIE_LC_CNTL_LC_L1_IMMEDIATE_ACK_MASK | PCIE_LC_CNTL_LC_PMI_TO_L1_DIS_MASK),
      (1 << PCIE_LC_CNTL_LC_L1_IMMEDIATE_ACK_OFFSET) |
      (0 << PCIE_LC_CNTL_LC_PMI_TO_L1_DIS_OFFSET)
      ),
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_FUNC0_PCIE2_PCIE_LC_CNTL4_ADDRESS,
      PCIE_LC_CNTL4_LC_L1_POWERDOWN_MASK,
      (1 << PCIE_LC_CNTL4_LC_L1_POWERDOWN_OFFSET)
      ),
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_FUNC0_PCIE3_PCIE_LC_CNTL4_ADDRESS,
      PCIE_LC_CNTL4_LC_L1_POWERDOWN_MASK,
      (1 << PCIE_LC_CNTL4_LC_L1_POWERDOWN_OFFSET)
      ),
// LC CLK_GATE
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_FUNC0_PCIE2_PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_ADDRESS, \
      PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_LC_DISABLE_LTSSM_DYN_CLK_GATING_MASK | \
      PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_LC_DISABLE_TRANSMIT_MUX_DYN_CLK_GATING_MASK | \
      PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_LC_DISABLE_LC_PKT_GEN_DYN_CLK_GATING_MASK | \
      PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_LC_DISABLE_SYMBOL_MUX_OUTPUT_GATING_MASK | \
      PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_LC_DISABLE_TRANSMIT_MUX_OUTPUT_GATING_MASK, \
      (0x0 << PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_LC_DISABLE_TRANSMIT_MUX_OUTPUT_GATING_MASK) | \
      (0x0 << PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_LC_DISABLE_TRANSMIT_MUX_DYN_CLK_GATING_OFFSET) | \
      (0x0 << PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_LC_DISABLE_LC_PKT_GEN_DYN_CLK_GATING_OFFSET) | \
      (0x0 << PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_LC_DISABLE_SYMBOL_MUX_OUTPUT_GATING_OFFSET) | \
      (0x0 << PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_LC_DISABLE_TRANSMIT_MUX_OUTPUT_GATING_OFFSET) \
      ),
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_FUNC0_PCIE3_PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_ADDRESS, \
      PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_LC_DISABLE_LTSSM_DYN_CLK_GATING_MASK | \
      PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_LC_DISABLE_TRANSMIT_MUX_DYN_CLK_GATING_MASK | \
      PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_LC_DISABLE_LC_PKT_GEN_DYN_CLK_GATING_MASK | \
      PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_LC_DISABLE_SYMBOL_MUX_OUTPUT_GATING_MASK | \
      PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_LC_DISABLE_TRANSMIT_MUX_OUTPUT_GATING_MASK, \
      (0x0 << PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_LC_DISABLE_TRANSMIT_MUX_OUTPUT_GATING_MASK) | \
      (0x0 << PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_LC_DISABLE_TRANSMIT_MUX_DYN_CLK_GATING_OFFSET) | \
      (0x0 << PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_LC_DISABLE_LC_PKT_GEN_DYN_CLK_GATING_OFFSET) | \
      (0x0 << PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_LC_DISABLE_SYMBOL_MUX_OUTPUT_GATING_OFFSET) | \
      (0x0 << PCIE_LC_FINE_GRAIN_CLK_GATE_OVERRIDES_LC_DISABLE_TRANSMIT_MUX_OUTPUT_GATING_OFFSET) \
      ),
// LC PM Substate
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_FUNC0_PCIE2_PCIE_LC_L1_PM_SUBSTATE_ADDRESS,
      PCIE_LC_L1_PM_SUBSTATE_LC_FORCE_L1_PG_EXIT_ON_REG_WRITE_MASK,
      (1 << PCIE_LC_L1_PM_SUBSTATE_LC_FORCE_L1_PG_EXIT_ON_REG_WRITE_OFFSET)
      ),
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_FUNC0_PCIE3_PCIE_LC_L1_PM_SUBSTATE_ADDRESS,
      PCIE_LC_L1_PM_SUBSTATE_LC_FORCE_L1_PG_EXIT_ON_REG_WRITE_MASK,
      (1 << PCIE_LC_L1_PM_SUBSTATE_LC_FORCE_L1_PG_EXIT_ON_REG_WRITE_OFFSET)
      ),
// 1.2 PCIE SDP disconnect control.
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_PCIE2_PCIE_MST_CTRL_2_ADDRESS,
      (PCIE_MST_CTRL_2_CI_MSTSDP_CLKGATE_ONESIDED_ENABLE_MASK | PCIE_MST_CTRL_2_CI_MSTSDP_DISCONNECT_RSP_ON_PARTIAL_MASK),
      (1 << PCIE_MST_CTRL_2_CI_MSTSDP_CLKGATE_ONESIDED_ENABLE_OFFSET) |
      (1 << PCIE_MST_CTRL_2_CI_MSTSDP_DISCONNECT_RSP_ON_PARTIAL_OFFSET)
      ),
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_PCIE3_PCIE_MST_CTRL_2_ADDRESS,
      (PCIE_MST_CTRL_2_CI_MSTSDP_CLKGATE_ONESIDED_ENABLE_MASK | PCIE_MST_CTRL_2_CI_MSTSDP_DISCONNECT_RSP_ON_PARTIAL_MASK),
      (1 << PCIE_MST_CTRL_2_CI_MSTSDP_CLKGATE_ONESIDED_ENABLE_OFFSET) |
      (1 << PCIE_MST_CTRL_2_CI_MSTSDP_DISCONNECT_RSP_ON_PARTIAL_OFFSET)
      ),
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_PCIE2_PCIE_SDP_CTRL_ADDRESS,
      PCIE_SDP_CTRL_CI_SLV_REQR_PART_DISCONNECT_EN_MASK,
      (1 << PCIE_SDP_CTRL_CI_SLV_REQR_PART_DISCONNECT_EN_OFFSET)
      ),
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_PCIE3_PCIE_SDP_CTRL_ADDRESS,
      PCIE_SDP_CTRL_CI_SLV_REQR_PART_DISCONNECT_EN_MASK,
      (1 << PCIE_SDP_CTRL_CI_SLV_REQR_PART_DISCONNECT_EN_OFFSET)
      ),
// 1.3 LCLK DS and LCLK Gating.
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_PCIE2_CPM_CONTROL_EXT_ADDRESS,
      (CPM_CONTROL_EXT_HOTPLUG_ALLOW_LCLK_GATING_EN_MASK | CPM_CONTROL_EXT_LCLK_DS_ENABLE_MASK
      | CPM_CONTROL_EXT_LCLK_DS_MODE_MASK),
      (1 << CPM_CONTROL_EXT_HOTPLUG_ALLOW_LCLK_GATING_EN_OFFSET) |
      (1 << CPM_CONTROL_EXT_LCLK_DS_ENABLE_OFFSET) |
      (1 << CPM_CONTROL_EXT_LCLK_DS_MODE_OFFSET)
      ),
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_PCIE3_CPM_CONTROL_EXT_ADDRESS,
      (CPM_CONTROL_EXT_HOTPLUG_ALLOW_LCLK_GATING_EN_MASK | CPM_CONTROL_EXT_LCLK_DS_ENABLE_MASK
      | CPM_CONTROL_EXT_LCLK_DS_MODE_MASK),
      (1 << CPM_CONTROL_EXT_HOTPLUG_ALLOW_LCLK_GATING_EN_OFFSET) |
      (1 << CPM_CONTROL_EXT_LCLK_DS_ENABLE_OFFSET) |
      (1 << CPM_CONTROL_EXT_LCLK_DS_MODE_OFFSET)
      ),
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_PCIE2_CPM_CONTROL_ADDRESS, \
      CPM_CONTROL_REGS_IDLE_TO_PG_LATENCY_MASK | \
      CPM_CONTROL_PG_EARLY_WAKE_ENABLE_MASK | \
      CPM_CONTROL_LCLK_GATE_ALLOW_IN_L1_MASK | \
      CPM_CONTROL_CLKREQb_UNGATE_TXCLK_ENABLE_MASK | \
      CPM_CONTROL_IGNORE_REGS_IDLE_IN_PG_MASK | \
      CPM_CONTROL_REFCLK_REGS_GATE_ENABLE_MASK | \
      CPM_CONTROL_TXCLK_PRBS_GATE_ENABLE_MASK | \
      CPM_CONTROL_TXCLK_REGS_GATE_ENABLE_MASK | \
      CPM_CONTROL_TXCLK_LCNT_GATE_ENABLE_MASK | \
      CPM_CONTROL_L1_2_PWR_GATE_ENABLE_MASK | \
      CPM_CONTROL_L1_1_PWR_GATE_ENABLE_MASK | \
      CPM_CONTROL_L1_PWR_GATE_ENABLE_MASK | \
      CPM_CONTROL_TXCLK_DYN_GATE_ENABLE_MASK | \
      CPM_CONTROL_LCLK_DYN_GATE_ENABLE_MASK, \
      (0x1 << CPM_CONTROL_REGS_IDLE_TO_PG_LATENCY_OFFSET) | \
      (0x1 << CPM_CONTROL_PG_EARLY_WAKE_ENABLE_OFFSET) | \
      (0x1 << CPM_CONTROL_LCLK_GATE_ALLOW_IN_L1_OFFSET) | \
      (0x1 << CPM_CONTROL_CLKREQb_UNGATE_TXCLK_ENABLE_OFFSET) | \
      (0x1 << CPM_CONTROL_IGNORE_REGS_IDLE_IN_PG_OFFSET) | \
      (0x1 << CPM_CONTROL_REFCLK_REGS_GATE_ENABLE_OFFSET) | \
      (0x1 << CPM_CONTROL_TXCLK_PRBS_GATE_ENABLE_OFFSET) | \
      (0x1 << CPM_CONTROL_TXCLK_REGS_GATE_ENABLE_OFFSET) | \
      (0x1 << CPM_CONTROL_TXCLK_LCNT_GATE_ENABLE_OFFSET) | \
      (0x1 << CPM_CONTROL_L1_2_PWR_GATE_ENABLE_OFFSET) | \
      (0x1 << CPM_CONTROL_L1_1_PWR_GATE_ENABLE_OFFSET) | \
      (0x1 << CPM_CONTROL_L1_PWR_GATE_ENABLE_OFFSET) | \
      (0x1 << CPM_CONTROL_TXCLK_DYN_GATE_ENABLE_OFFSET) | \
      (0x1 << CPM_CONTROL_LCLK_DYN_GATE_ENABLE_OFFSET) \
      ),
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_PCIE3_CPM_CONTROL_ADDRESS, \
      CPM_CONTROL_REGS_IDLE_TO_PG_LATENCY_MASK | \
      CPM_CONTROL_PG_EARLY_WAKE_ENABLE_MASK | \
      CPM_CONTROL_LCLK_GATE_ALLOW_IN_L1_MASK | \
      CPM_CONTROL_CLKREQb_UNGATE_TXCLK_ENABLE_MASK | \
      CPM_CONTROL_IGNORE_REGS_IDLE_IN_PG_MASK | \
      CPM_CONTROL_REFCLK_REGS_GATE_ENABLE_MASK | \
      CPM_CONTROL_TXCLK_PRBS_GATE_ENABLE_MASK | \
      CPM_CONTROL_TXCLK_REGS_GATE_ENABLE_MASK | \
      CPM_CONTROL_TXCLK_LCNT_GATE_ENABLE_MASK | \
      CPM_CONTROL_L1_2_PWR_GATE_ENABLE_MASK | \
      CPM_CONTROL_L1_1_PWR_GATE_ENABLE_MASK | \
      CPM_CONTROL_L1_PWR_GATE_ENABLE_MASK | \
      CPM_CONTROL_TXCLK_DYN_GATE_ENABLE_MASK | \
      CPM_CONTROL_LCLK_DYN_GATE_ENABLE_MASK, \
      (0x1 << CPM_CONTROL_REGS_IDLE_TO_PG_LATENCY_OFFSET) | \
      (0x1 << CPM_CONTROL_PG_EARLY_WAKE_ENABLE_OFFSET) | \
      (0x1 << CPM_CONTROL_LCLK_GATE_ALLOW_IN_L1_OFFSET) | \
      (0x1 << CPM_CONTROL_CLKREQb_UNGATE_TXCLK_ENABLE_OFFSET) | \
      (0x1 << CPM_CONTROL_IGNORE_REGS_IDLE_IN_PG_OFFSET) | \
      (0x1 << CPM_CONTROL_REFCLK_REGS_GATE_ENABLE_OFFSET) | \
      (0x1 << CPM_CONTROL_TXCLK_PRBS_GATE_ENABLE_OFFSET) | \
      (0x1 << CPM_CONTROL_TXCLK_REGS_GATE_ENABLE_OFFSET) | \
      (0x1 << CPM_CONTROL_TXCLK_LCNT_GATE_ENABLE_OFFSET) | \
      (0x1 << CPM_CONTROL_L1_2_PWR_GATE_ENABLE_OFFSET) | \
      (0x1 << CPM_CONTROL_L1_1_PWR_GATE_ENABLE_OFFSET) | \
      (0x1 << CPM_CONTROL_L1_PWR_GATE_ENABLE_OFFSET) | \
      (0x1 << CPM_CONTROL_TXCLK_DYN_GATE_ENABLE_OFFSET) | \
      (0x1 << CPM_CONTROL_LCLK_DYN_GATE_ENABLE_OFFSET) \
      ),
// RSMU_MASTER_MESSAGE_SEND_ENABLE
    GNB_ENTRY_RMW (
      ONE_ADDR_TYPE,
      SMN_PCIE2_RSMU_MASTER_CONTROL_ADDRESS,
      RSMU_MASTER_CONTROL_RSMU_MASTER_MESSAGE_SEND_ENABLE_MASK,
      (1 << RSMU_MASTER_CONTROL_RSMU_MASTER_MESSAGE_SEND_ENABLE_OFFSET)
      ),
    GNB_ENTRY_RMW (
      ONE_ADDR_TYPE,
      SMN_PCIE3_RSMU_MASTER_CONTROL_ADDRESS,
      RSMU_MASTER_CONTROL_RSMU_MASTER_MESSAGE_SEND_ENABLE_MASK,
      (1 << RSMU_MASTER_CONTROL_RSMU_MASTER_MESSAGE_SEND_ENABLE_OFFSET)
      ),
    GNB_ENTRY_RMW (
      ONE_ADDR_TYPE,
      SMN_PCIE2_SMU_PCIE_USB_BDF_ADDRESS_ADDRESS,
      SMU_PCIE_USB_BDF_ADDRESS_USB_BDF_ADDR_LOWER_MASK,
      (0x197F2080 << SMU_PCIE_USB_BDF_ADDRESS_USB_BDF_ADDR_LOWER_OFFSET)
      ),
    GNB_ENTRY_RMW (
      ONE_ADDR_TYPE,
      SMN_PCIE3_SMU_PCIE_USB_BDF_ADDRESS_ADDRESS,
      SMU_PCIE_USB_BDF_ADDRESS_USB_BDF_ADDR_LOWER_MASK,
      (0x198F2080 << SMU_PCIE_USB_BDF_ADDRESS_USB_BDF_ADDR_LOWER_OFFSET)
      ),
    GNB_ENTRY_RMW (
      ONE_ADDR_TYPE,
      SMN_PCIE2_SMU_PCIE_USB_S_LTR_ADDRESS_ADDRESS,
      SMU_PCIE_USB_S_LTR_ADDRESS_USB_S_LTR_ADDR_LOWER_MASK,
      (0x197D5D00 << SMU_PCIE_USB_S_LTR_ADDRESS_USB_S_LTR_ADDR_LOWER_OFFSET)
      ),
    GNB_ENTRY_RMW (
      ONE_ADDR_TYPE,
      SMN_PCIE3_SMU_PCIE_USB_S_LTR_ADDRESS_ADDRESS,
      SMU_PCIE_USB_S_LTR_ADDRESS_USB_S_LTR_ADDR_LOWER_MASK,
      (0x198D5D00 << SMU_PCIE_USB_S_LTR_ADDRESS_USB_S_LTR_ADDR_LOWER_OFFSET)
      ),
// ACS
    GNB_ENTRY_RMW_IF_PCD_EQUAL (
      ALL_NBIO_TYPE,
      PcdToken(PcdCfgACSEnable),
      TRUE,
      SMN_NBIF0INTERNAL_RCC_DEV1_EPF2_STRAP2_ADDRESS,
      RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_MASK,
      (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_OFFSET)
      ),
    GNB_ENTRY_RMW_IF_PCD_EQUAL (
      ALL_NBIO_TYPE,
      PcdToken(PcdCfgACSEnable),
      TRUE,
      SMN_NBIF0INTERNAL_RCC_DEV1_EPF3_STRAP2_ADDRESS,
      RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_MASK,
      (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_OFFSET)
      ),
    GNB_ENTRY_RMW_IF_PCD_EQUAL (
      ALL_NBIO_TYPE,
      PcdToken(PcdCfgACSEnable),
      TRUE,
      SMN_NBIF0INTERNAL_RCC_DEV2_EPF3_STRAP2_ADDRESS,
      RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_MASK,
      (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_OFFSET)
      ),
    GNB_ENTRY_RMW_IF_PCD_EQUAL (
      ALL_NBIO_TYPE,
      PcdToken(PcdCfgACSEnable),
      TRUE,
      SMN_NBIF0INTERNAL_RCC_DEV2_EPF4_STRAP2_ADDRESS,
      RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_MASK,
      (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_OFFSET)
      ),
    GNB_ENTRY_RMW_IF_PCD_EQUAL (
      ALL_NBIO_TYPE,
      PcdToken(PcdCfgACSEnable),
      TRUE,
      SMN_NBIF0INTERNAL_RCC_DEV2_EPF5_STRAP2_ADDRESS,
      RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_MASK,
      (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_OFFSET)
      ),
    GNB_ENTRY_RMW_IF_PCD_EQUAL (
      ALL_NBIO_TYPE,
      PcdToken(PcdCfgACSEnable),
      TRUE,
      SMN_NBIF0INTERNAL_RCC_DEV2_EPF6_STRAP2_ADDRESS,
      RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_MASK,
      (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_OFFSET)
      ),
// 14.6.9.5.6 PerfReg Final Setting
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_NBIF0_A2S_TAG_ALLOC_0_ADDRESS_Bx,
      A2S_TAG_ALLOC_0_TAG_ALLOC_FOR_VC0_WR_MASK |
      A2S_TAG_ALLOC_0_TAG_ALLOC_FOR_VC0_RD_MASK |
      A2S_TAG_ALLOC_0_TAG_ALLOC_FOR_VC1_WR_MASK,
      (0x4 << A2S_TAG_ALLOC_0_TAG_ALLOC_FOR_VC0_WR_OFFSET) |
      (0x4 << A2S_TAG_ALLOC_0_TAG_ALLOC_FOR_VC0_RD_OFFSET) |
      (0xB << A2S_TAG_ALLOC_0_TAG_ALLOC_FOR_VC1_WR_OFFSET)
      ),
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_NBIF0_A2S_TAG_ALLOC_1_ADDRESS_Bx,
      A2S_TAG_ALLOC_1_TAG_ALLOC_FOR_VC3_WR_MASK |
      A2S_TAG_ALLOC_1_TAG_ALLOC_FOR_VC7_WR_MASK |
      A2S_TAG_ALLOC_1_TAG_ALLOC_FOR_VC7_RD_MASK,
      (0x4 << A2S_TAG_ALLOC_1_TAG_ALLOC_FOR_VC3_WR_OFFSET) |
      (0x0 << A2S_TAG_ALLOC_1_TAG_ALLOC_FOR_VC7_WR_OFFSET) |
      (0x0 << A2S_TAG_ALLOC_1_TAG_ALLOC_FOR_VC7_RD_OFFSET)
      ),
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_NBIF0_A2S_TAG_ALLOC_2_ADDRESS_Bx,
      A2S_TAG_ALLOC_2_TAG_ALLOC_FOR_VC5_WR_MASK |
      A2S_TAG_ALLOC_2_TAG_ALLOC_FOR_VC5_RD_MASK |
      A2S_TAG_ALLOC_2_TAG_ALLOC_FOR_VC6_WR_MASK |
      A2S_TAG_ALLOC_2_TAG_ALLOC_FOR_VC6_RD_MASK,
      (0x4A << A2S_TAG_ALLOC_2_TAG_ALLOC_FOR_VC5_WR_OFFSET) |
      (0x4A << A2S_TAG_ALLOC_2_TAG_ALLOC_FOR_VC5_RD_OFFSET) |
      (0x0 << A2S_TAG_ALLOC_2_TAG_ALLOC_FOR_VC6_WR_OFFSET) |
      (0x0 << A2S_TAG_ALLOC_2_TAG_ALLOC_FOR_VC6_RD_OFFSET)
      ),
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_NBIF0_A2S_TAG_ALLOC_3_ADDRESS_Bx,
      A2S_TAG_ALLOC_3_TAG_ALLOC_FOR_VC4_WR_MASK |
      A2S_TAG_ALLOC_3_TAG_ALLOC_FOR_VC4_RD_MASK |
      A2S_TAG_ALLOC_3_TAG_ALLOC_FOR_VC2_WR_MASK |
      A2S_TAG_ALLOC_3_TAG_ALLOC_FOR_VC2_RD_MASK,
      (0x0 << A2S_TAG_ALLOC_3_TAG_ALLOC_FOR_VC4_WR_OFFSET) |
      (0x0 << A2S_TAG_ALLOC_3_TAG_ALLOC_FOR_VC4_RD_OFFSET) |
      (0x0 << A2S_TAG_ALLOC_3_TAG_ALLOC_FOR_VC2_WR_OFFSET) |
      (0x0 << A2S_TAG_ALLOC_3_TAG_ALLOC_FOR_VC2_RD_OFFSET)
      ),
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_NBIF0_SHUB_A2S_TAG_ALLOC_FOR_CHAIN_0_ADDRESS,
      SHUB_A2S_TAG_ALLOC_FOR_CHAIN_0_TAG_ALLOC_FOR_VC1_CHAIN_MASK |
      SHUB_A2S_TAG_ALLOC_FOR_CHAIN_0_TAG_ALLOC_FOR_VC2_CHAIN_MASK,
      (0x3 << SHUB_A2S_TAG_ALLOC_FOR_CHAIN_0_TAG_ALLOC_FOR_VC1_CHAIN_OFFSET) |
      (0x0 << SHUB_A2S_TAG_ALLOC_FOR_CHAIN_0_TAG_ALLOC_FOR_VC2_CHAIN_OFFSET)
      ),
    GNB_ENTRY_RMW (
      ALL_NBIO_TYPE,
      SMN_NBIF0_SHUB_A2S_TAG_ALLOC_FOR_CHAIN_1_ADDRESS,
      SHUB_A2S_TAG_ALLOC_FOR_CHAIN_1_TAG_ALLOC_FOR_VC4_CHAIN_MASK |
      SHUB_A2S_TAG_ALLOC_FOR_CHAIN_1_TAG_ALLOC_FOR_VC5_CHAIN_MASK |
      SHUB_A2S_TAG_ALLOC_FOR_CHAIN_1_TAG_ALLOC_FOR_VC6_CHAIN_MASK |
      SHUB_A2S_TAG_ALLOC_FOR_CHAIN_1_TAG_ALLOC_FOR_VC7_CHAIN_MASK,
      (0x0 << SHUB_A2S_TAG_ALLOC_FOR_CHAIN_1_TAG_ALLOC_FOR_VC4_CHAIN_OFFSET) |
      (0x47 << SHUB_A2S_TAG_ALLOC_FOR_CHAIN_1_TAG_ALLOC_FOR_VC5_CHAIN_OFFSET) |
      (0x0 << SHUB_A2S_TAG_ALLOC_FOR_CHAIN_1_TAG_ALLOC_FOR_VC6_CHAIN_OFFSET) |
      (0x0 << SHUB_A2S_TAG_ALLOC_FOR_CHAIN_1_TAG_ALLOC_FOR_VC7_CHAIN_OFFSET)
      ),
  GNB_ENTRY_TERMINATE
};

