/*****************************************************************************
 *
 * Copyright (C) 2008-2022 Advanced Micro Devices, Inc. All rights reserved.
 *
 *******************************************************************************
 **/

#ifndef _NBIO_NBIF_TABLE_H_
#define _NBIO_NBIF_TABLE_H_
// --------------------------------------------------
// 14.6.9.1 nBIF Configurations
// --------------------------------------------------

  // NBIFMM::RCC_DEV0_EPF1_STRAP0[STRAP_FUNC_EN_DEV0_F1] --- Reset value = 1, no need to program
  // NBIFMM::RCC_DEV0_EPF2_STRAP0[STRAP_FUNC_EN_DEV0_F2] --- Reset value = 1, no need to program
  // NBIFMM::RCC_DEV0_EPF3_STRAP0[STRAP_FUNC_EN_DEV0_F3] --- Reset value = 1, no need to program
  // NBIFMM::RCC_DEV0_EPF4_STRAP0[STRAP_FUNC_EN_DEV0_F4] --- Reset value = 1, no need to program
  // NBIFMM::RCC_DEV0_EPF5_STRAP0[STRAP_FUNC_EN_DEV0_F5] --- Reset value = 1, no need to program
  // NBIFMM::RCC_DEV0_EPF6_STRAP0[STRAP_FUNC_EN_DEV0_F6] --- Reset value = 1, no need to program
  // NBIFMM::RCC_DEV0_EPF7_STRAP0[STRAP_FUNC_EN_DEV0_F7] --- Reset value = 1, no need to program
  // NBIFMM::RCC_DEV1_EPF2_STRAP0[STRAP_FUNC_EN_DEV1_F2] --- Reset value = 1, no need to program
  // NBIFMM::RCC_DEV2_EPF2_STRAP0[STRAP_FUNC_EN_DEV2_F2] --- Reset value = 1, HSP, hide from pci space by default
  // NBIFMM::RCC_DEV0_EPF7_STRAP13[STRAP_CLASS_CODE_BASE_DEV0_F7] = 11h --- Reset value matches the requirement, no need to program
  // NBIFMM::RCC_DEV0_EPF7_STRAP13[STRAP_CLASS_CODE_SUB_DEV0_F7] = 80h --- Reset value matches the requirement, no need to program
  // NBIFMM::RCC_DEV0_PORT_RCC_DEV1_EPF1_STRAP0STRAP7[STRAP_RP_BUSNUM_DEV0] --- See NbioBaseInitCallback ()
  // NBIFMM::RCC_DEV0_PORT_STRAP7[STRAP_DN_DEVNUM_DEV0] --- See NbioBaseInitCallback ()
  // NBIFMM::RCC_DEV0_PORT_STRAP7[STRAP_DN_FUNCID_DEV0] --- See NbioBaseInitCallback ()
  // NBIFMM::RCC_DEV1_PORT_STRAP7[STRAP_RP_BUSNUM_DEV1] --- See NbioBaseInitCallback ()
  // NBIFMM::RCC_DEV1_PORT_STRAP7[STRAP_DN_DEVNUM_DEV1] --- See NbioBaseInitCallback ()
  // NBIFMM::RCC_DEV1_PORT_STRAP7[STRAP_DN_FUNCID_DEV1] --- See NbioBaseInitCallback ()
  // NBIFMM::RCC_DEV2_PORT_STRAP7[STRAP_RP_BUSNUM_DEV2] --- See NbioBaseInitCallback ()
  // NBIFMM::RCC_DEV2_PORT_STRAP7[STRAP_DN_DEVNUM_DEV2] --- See NbioBaseInitCallback ()
  // NBIFMM::RCC_DEV2_PORT_STRAP7[STRAP_DN_FUNCID_DEV2] --- See NbioBaseInitCallback ()
  // NBIFMM::RCC_DEV1_EPF0_STRAP0[STRAP_MAJOR_REV_ID_DEV1_F0] = Ah
  // NBIFMM::RCC_DEV1_EPF0_STRAP0[STRAP_MINOR_REV_ID_DEV1_F0] = 1h
  // NBIFMM::RCC_DEV1_EPF1_STRAP0[STRAP_MAJOR_REV_ID_DEV1_F1] = Ah
  // NBIFMM::RCC_DEV1_EPF1_STRAP0[STRAP_MINOR_REV_ID_DEV1_F1] = 1h
  #define NBIO_NBIF_DEVICE_CFG_TBL \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV0_EPF3_STRAP3_ADDRESS, \
      RCC_DEV0_EPF3_STRAP3_STRAP_TRUE_PM_STATUS_EN_DEV0_F3_MASK, \
      (0x1 << RCC_DEV0_EPF3_STRAP3_STRAP_TRUE_PM_STATUS_EN_DEV0_F3_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV0_EPF4_STRAP3_ADDRESS, \
      RCC_DEV0_EPF4_STRAP3_STRAP_TRUE_PM_STATUS_EN_DEV0_F4_MASK, \
      (0x1 << RCC_DEV0_EPF4_STRAP3_STRAP_TRUE_PM_STATUS_EN_DEV0_F4_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV1_EPF0_STRAP3_ADDRESS, \
      RCC_DEV1_EPF0_STRAP3_STRAP_TRUE_PM_STATUS_EN_DEV1_F0_MASK, \
      (0x1 << RCC_DEV1_EPF0_STRAP3_STRAP_TRUE_PM_STATUS_EN_DEV1_F0_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV2_EPF0_STRAP3_ADDRESS, \
      RCC_DEV2_EPF0_STRAP3_STRAP_TRUE_PM_STATUS_EN_DEV2_F0_MASK, \
      (0x1 << RCC_DEV2_EPF0_STRAP3_STRAP_TRUE_PM_STATUS_EN_DEV2_F0_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV1_EPF0_STRAP0_ADDRESS, \
      RCC_DEV1_EPF0_STRAP0_STRAP_MAJOR_REV_ID_DEV1_F0_MASK | \
      RCC_DEV1_EPF0_STRAP0_STRAP_MINOR_REV_ID_DEV1_F0_MASK, \
      (0xA << RCC_DEV1_EPF0_STRAP0_STRAP_MAJOR_REV_ID_DEV1_F0_OFFSET) | \
      (0x1 << RCC_DEV1_EPF0_STRAP0_STRAP_MINOR_REV_ID_DEV1_F0_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV1_EPF1_STRAP0_ADDRESS, \
      RCC_DEV1_EPF1_STRAP0_STRAP_MAJOR_REV_ID_DEV1_F1_MASK | \
      RCC_DEV1_EPF1_STRAP0_STRAP_MINOR_REV_ID_DEV1_F1_MASK, \
      (0xA << RCC_DEV1_EPF1_STRAP0_STRAP_MAJOR_REV_ID_DEV1_F1_OFFSET) | \
      (0x1 << RCC_DEV1_EPF1_STRAP0_STRAP_MINOR_REV_ID_DEV1_F1_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV2_EPF2_STRAP0_ADDRESS, \
      RCC_DEV2_EPF2_STRAP0_STRAP_FUNC_EN_DEV2_F2_MASK, \
      (0 << RCC_DEV2_EPF2_STRAP0_STRAP_FUNC_EN_DEV2_F2_OFFSET) \
      ), \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdCfgNbifDev0Epf7En), \
      FALSE, \
      SMN_NBIF0INTERNAL_RCC_DEV0_EPF7_STRAP0_ADDRESS, \
      RCC_DEV0_EPF7_STRAP0_STRAP_FUNC_EN_DEV0_F7_MASK, \
      (0 << RCC_DEV0_EPF7_STRAP0_STRAP_FUNC_EN_DEV0_F7_OFFSET) \
      ),
  // End of NBIO_NBIF_DEVICE_CFG_TBL


// --------------------------------------------------
// 14.6.9.4.3 ATC/ATS Support
// --------------------------------------------------

  // Set NBIFMM::RCC_DEV0_EPF0_STRAP2[STRAP_ATS_EN_DEV0_F0] = 1h.
  // Set NBIFMM::RCC_DEV0_EPF0_STRAP2[STRAP_MAX_PASID_WIDTH_DEV0_F0] = 10h.
  // Set NBIFMM::RCC_DEV0_PORT_STRAP2[STRAP_E2E_PREFIX_EN_DEV0] = 1h.
  // Set NBIFMM::RCC_DEV0_PORT_STRAP2[STRAP_EXTENDED_FMT_SUPPORTED_DEV0] = 1h.
  // Set NBIFMM::RCC_DEV0_EPF0_STRAP2[STRAP_PAGE_REQ_EN_DEV0_F0] = 1h.
  // Set NBIFMM::RCC_DEV0_EPF0_STRAP2[STRAP_PASID_EN_DEV0_F0] = 1h.
  // Set NBIFMM::RCC_DEV0_EPF0_STRAP2[STRAP_PASID_EXE_PERMISSION_SUPPORTED_DEV0_F0] = 1h.
  // Set NBIFMM::RCC_DEV0_EPF0_STRAP2[STRAP_PASID_PRIV_MODE_SUPPORTED_DEV0_F0] = 1h.
  #define NBIO_NBIF_ATC_ATS_TBL \
    GNB_ENTRY_RMW ( \
      ONE_ADDR_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV0_EPF0_STRAP2_ADDRESS, \
      RCC_DEV0_EPF0_STRAP2_STRAP_ATS_EN_DEV0_F0_MASK | \
      RCC_DEV0_EPF0_STRAP2_STRAP_MAX_PASID_WIDTH_DEV0_F0_MASK | \
      RCC_DEV0_EPF0_STRAP2_STRAP_PAGE_REQ_EN_DEV0_F0_MASK | \
      RCC_DEV0_EPF0_STRAP2_STRAP_PASID_EN_DEV0_F0_MASK | \
      RCC_DEV0_EPF0_STRAP2_STRAP_PASID_EXE_PERMISSION_SUPPORTED_DEV0_F0_MASK | \
      RCC_DEV0_EPF0_STRAP2_STRAP_PASID_PRIV_MODE_SUPPORTED_DEV0_F0_MASK, \
      ((0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_ATS_EN_DEV0_F0_OFFSET) | \
      (0x10 << RCC_DEV0_EPF0_STRAP2_STRAP_MAX_PASID_WIDTH_DEV0_F0_OFFSET) | \
      (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_PAGE_REQ_EN_DEV0_F0_OFFSET) | \
      (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_PASID_EN_DEV0_F0_OFFSET) | \
      (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_PASID_EXE_PERMISSION_SUPPORTED_DEV0_F0_OFFSET) | \
      (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_PASID_PRIV_MODE_SUPPORTED_DEV0_F0_OFFSET)) \
      ), \
    GNB_ENTRY_RMW ( \
      ONE_ADDR_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV0_PORT_STRAP2_ADDRESS, \
      RCC_DEV0_PORT_STRAP2_STRAP_E2E_PREFIX_EN_DEV0_MASK | \
      RCC_DEV0_PORT_STRAP2_STRAP_EXTENDED_FMT_SUPPORTED_DEV0_MASK, \
      ((0x1 << RCC_DEV0_PORT_STRAP2_STRAP_E2E_PREFIX_EN_DEV0_OFFSET) | \
      (0x1 << RCC_DEV0_PORT_STRAP2_STRAP_EXTENDED_FMT_SUPPORTED_DEV0_OFFSET)) \
      ),
  // End of NBIO_NBIF_ATC_ATS_TBL


// --------------------------------------------------
// 14.6.9.5.1 Endpoint function interrupt enable
// --------------------------------------------------

  // NBIFMM::INTR_LINE_POLARITY = 0h --- Reset value is already 0
  // NBIFMM::INTR_LINE_ENABLE = 1h --- NOTE: skip enabling interrupt for XGBE for client
  #define NBIO_NBIF_DEVICE_INTERRUPT_TBL \
    GNB_ENTRY_WR ( \
      ONE_ADDR_TYPE, \
      SMN_NBIF0_INTR_LINE_ENABLE_ADDRESS, \
      ((0xFF << INTR_LINE_ENABLE_INTR_LINE_ENABLE_DEV0_OFFSET) | \
      (0x3 << INTR_LINE_ENABLE_INTR_LINE_ENABLE_DEV1_OFFSET) | \
      (0x7 << INTR_LINE_ENABLE_INTR_LINE_ENABLE_DEV2_OFFSET)) \
      ),
  // End of NBIO_NBIF_DEVICE_INTERRUPT_TBL

// --------------------------------------------------
// 14.6.9.5.3 Dummy F0
// --------------------------------------------------

  // NBIFMM::RCC_DEV0_PORT_STRAP0[STRAP_EPF0_DUMMY_EN_DEV0] = 1'b1
  // NBIFMM::RCC_DEV0_EPF1_STRAP0[STRAP_FUNC_EN_DEV0_F1] = 1'b0
  // NBIFMM::RCC_DEV0_EPF0_STRAP0[STRAP_DEVICE_ID_DEV0_F0] = 0x145A
  // NBIFMM::RCC_DEV0_EPF0_STRAP13[STRAP_CLASS_CODE_PIF_DEV0_F0] = 0x0
  // NBIFMM::RCC_DEV0_EPF0_STRAP13[STRAP_CLASS_CODE_SUB_DEV0_F0] = 0x0
  // NBIFMM::RCC_DEV0_EPF0_STRAP13[STRAP_CLASS_CODE_BASE_DEV0_F0] = 0x13
  // NBIFMM::RCC_DEV0_EPF0_STRAP4[STRAP_INTERRUPT_PIN_DEV0_F0] = 0x0
  // NBIFMM::RCC_DEV0_EPF0_STRAP3[STRAP_MSI_EN_DEV0_F0] = 0x0
  // NBIFMM::RCC_DEV0_EPF0_STRAP3[STRAP_MSIX_EN_DEV0_F0] = 0x0
  // NBIFMM::RCC_DEV0_EPF0_STRAP4[STRAP_PME_SUPPORT_DEV0_F0] = 0x0
  // NBIFMM::RCC_DEV0_EPF0_STRAP2[STRAP_RESIZE_BAR_EN_DEV0_F0] = 1'b0
  #define NBIO_NBIF_DISABLE_IGPU_TBL \
    GNB_ENTRY_PROPERTY_RMW ( \
      TABLE_PROPERTY_IGFX_DISABLED, \
      ONE_ADDR_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV0_PORT_STRAP0_ADDRESS, \
      RCC_DEV0_PORT_STRAP0_STRAP_EPF0_DUMMY_EN_DEV0_MASK, \
      (0x1 << RCC_DEV0_PORT_STRAP0_STRAP_EPF0_DUMMY_EN_DEV0_OFFSET) \
      ), \
    GNB_ENTRY_PROPERTY_RMW ( \
      TABLE_PROPERTY_IGFX_DISABLED, \
      ALL_NBIO_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV0_EPF1_STRAP0_ADDRESS, \
      RCC_DEV0_EPF1_STRAP0_STRAP_FUNC_EN_DEV0_F1_MASK, \
      (0x0 << RCC_DEV0_EPF1_STRAP0_STRAP_FUNC_EN_DEV0_F1_OFFSET) \
      ), \
    GNB_ENTRY_PROPERTY_RMW ( \
      TABLE_PROPERTY_IGFX_DISABLED, \
      ONE_ADDR_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV0_EPF0_STRAP0_ADDRESS, \
      RCC_DEV0_EPF0_STRAP0_STRAP_DEVICE_ID_DEV0_F0_MASK, \
      (0x145A << RCC_DEV0_EPF0_STRAP0_STRAP_DEVICE_ID_DEV0_F0_OFFSET) \
      ), \
    GNB_ENTRY_PROPERTY_RMW ( \
      TABLE_PROPERTY_IGFX_DISABLED, \
      ALL_NBIO_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV0_EPF0_STRAP13_ADDRESS, \
      RCC_DEV0_EPF0_STRAP13_STRAP_CLASS_CODE_PIF_DEV0_F0_MASK | \
      RCC_DEV0_EPF0_STRAP13_STRAP_CLASS_CODE_SUB_DEV0_F0_MASK | \
      RCC_DEV0_EPF0_STRAP13_STRAP_CLASS_CODE_BASE_DEV0_F0_MASK, \
      (0x0 << RCC_DEV0_EPF0_STRAP13_STRAP_CLASS_CODE_PIF_DEV0_F0_OFFSET) | \
      (0x0 << RCC_DEV0_EPF0_STRAP13_STRAP_CLASS_CODE_SUB_DEV0_F0_OFFSET) | \
      (0x13 << RCC_DEV0_EPF0_STRAP13_STRAP_CLASS_CODE_BASE_DEV0_F0_OFFSET) \
      ), \
    GNB_ENTRY_PROPERTY_RMW ( \
      TABLE_PROPERTY_IGFX_DISABLED, \
      ONE_ADDR_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV0_EPF0_STRAP4_ADDRESS, \
      RCC_DEV0_EPF0_STRAP4_STRAP_INTERRUPT_PIN_DEV0_F0_MASK, \
      (0x0 << RCC_DEV0_EPF0_STRAP4_STRAP_INTERRUPT_PIN_DEV0_F0_OFFSET) \
      ), \
    GNB_ENTRY_PROPERTY_RMW ( \
      TABLE_PROPERTY_IGFX_DISABLED, \
      ONE_ADDR_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV0_EPF0_STRAP3_ADDRESS, \
      RCC_DEV0_EPF0_STRAP3_STRAP_MSI_EN_DEV0_F0_MASK | \
      RCC_DEV0_EPF0_STRAP3_STRAP_MSIX_EN_DEV0_F0_MASK, \
      (0x0 << RCC_DEV0_EPF0_STRAP3_STRAP_MSI_EN_DEV0_F0_OFFSET) | \
      (0x0 << RCC_DEV0_EPF0_STRAP3_STRAP_MSIX_EN_DEV0_F0_OFFSET) \
      ), \
    GNB_ENTRY_PROPERTY_RMW ( \
      TABLE_PROPERTY_IGFX_DISABLED, \
      ONE_ADDR_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV0_EPF0_STRAP4_ADDRESS, \
      RCC_DEV0_EPF0_STRAP4_STRAP_PME_SUPPORT_DEV0_F0_MASK, \
      (0x0 << RCC_DEV0_EPF0_STRAP4_STRAP_PME_SUPPORT_DEV0_F0_OFFSET) \
      ), \
    GNB_ENTRY_PROPERTY_RMW ( \
      TABLE_PROPERTY_IGFX_DISABLED, \
      ONE_ADDR_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV0_EPF0_STRAP2_ADDRESS, \
      RCC_DEV0_EPF0_STRAP2_STRAP_RESIZE_BAR_EN_DEV0_F0_MASK, \
      (0x0 << RCC_DEV0_EPF0_STRAP2_STRAP_RESIZE_BAR_EN_DEV0_F0_OFFSET) \
      ),
  // End of NBIO_NBIF_DISABLE_IGPU_TBL


// --------------------------------------------------
// LTR disable
// --------------------------------------------------

  #define NBIO_NBIF_DISABLE_LTR_TBL \
    GNB_ENTRY_PROPERTY_RMW ( \
      TABLE_PROPERTY_IGFX_DISABLED, \
      ONE_ADDR_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV0_PORT_STRAP3_ADDRESS, \
      RCC_DEV0_PORT_STRAP3_STRAP_LTR_EN_DEV0_MASK | \
      RCC_DEV0_PORT_STRAP3_STRAP_LTR_EN_DN_DEV0_MASK, \
      (0x0 << RCC_DEV0_PORT_STRAP3_STRAP_LTR_EN_DEV0_OFFSET) | \
      (0x0 << RCC_DEV0_PORT_STRAP3_STRAP_LTR_EN_DN_DEV0_OFFSET) \
      ),
  // End of NBIO_NBIF_DISABLE_LTR_TBL


// --------------------------------------------------
// AER disable
// --------------------------------------------------

  #define NBIO_NBIF_DISABLE_AER_TBL \
    GNB_ENTRY_PROPERTY_RMW ( \
      TABLE_PROPERTY_IGFX_DISABLED, \
      ONE_ADDR_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV0_EPF0_STRAP2_ADDRESS, \
      RCC_DEV0_EPF0_STRAP2_STRAP_AER_EN_DEV0_F0_MASK | \
      RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_MASK | \
      RCC_DEV0_EPF0_STRAP2_STRAP_ATS_EN_DEV0_F0_MASK | \
      RCC_DEV0_EPF0_STRAP2_STRAP_PASID_EN_DEV0_F0_MASK | \
      RCC_DEV0_EPF0_STRAP2_STRAP_PAGE_REQ_EN_DEV0_F0_MASK | \
      RCC_DEV0_EPF0_STRAP2_STRAP_RESIZE_BAR_EN_DEV0_F0_MASK, \
      (0x0 << RCC_DEV0_EPF0_STRAP2_STRAP_AER_EN_DEV0_F0_OFFSET) | \
      (0x0 << RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_OFFSET) | \
      (0x0 << RCC_DEV0_EPF0_STRAP2_STRAP_ATS_EN_DEV0_F0_OFFSET) | \
      (0x0 << RCC_DEV0_EPF0_STRAP2_STRAP_PASID_EN_DEV0_F0_OFFSET) | \
      (0x0 << RCC_DEV0_EPF0_STRAP2_STRAP_PAGE_REQ_EN_DEV0_F0_OFFSET) | \
      (0x0 << RCC_DEV0_EPF0_STRAP2_STRAP_RESIZE_BAR_EN_DEV0_F0_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV2_PORT_STRAP0_ADDRESS, \
      RCC_DEV2_PORT_STRAP0_STRAP_AER_EN_DN_DEV2_MASK | \
      RCC_DEV2_PORT_STRAP0_STRAP_ACS_EN_DN_DEV2_MASK, \
      (0x1 << RCC_DEV2_PORT_STRAP0_STRAP_AER_EN_DN_DEV2_OFFSET) | \
      (0x1 << RCC_DEV2_PORT_STRAP0_STRAP_ACS_EN_DN_DEV2_OFFSET) \
    ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV2_PORT_STRAP5_ADDRESS, \
      RCC_DEV2_PORT_STRAP5_STRAP_ACS_SOURCE_VALIDATION_DN_DEV2_MASK | \
      RCC_DEV2_PORT_STRAP5_STRAP_ACS_TRANSLATION_BLOCKING_DN_DEV2_MASK | \
      RCC_DEV2_PORT_STRAP5_STRAP_ACS_P2P_REQUEST_REDIRECT_DN_DEV2_MASK | \
      RCC_DEV2_PORT_STRAP5_STRAP_ACS_P2P_COMPLETION_REDIRECT_DN_DEV2_MASK | \
      RCC_DEV2_PORT_STRAP5_STRAP_ACS_UPSTREAM_FORWARDING_DN_DEV2_MASK | \
      RCC_DEV2_PORT_STRAP5_STRAP_ACS_DIRECT_TRANSLATED_P2P_DN_DEV2_MASK, \
      (0x1 << RCC_DEV2_PORT_STRAP5_STRAP_ACS_SOURCE_VALIDATION_DN_DEV2_OFFSET) | \
      (0x1 << RCC_DEV2_PORT_STRAP5_STRAP_ACS_TRANSLATION_BLOCKING_DN_DEV2_OFFSET) | \
      (0x1 << RCC_DEV2_PORT_STRAP5_STRAP_ACS_P2P_REQUEST_REDIRECT_DN_DEV2_OFFSET) | \
      (0x1 << RCC_DEV2_PORT_STRAP5_STRAP_ACS_P2P_COMPLETION_REDIRECT_DN_DEV2_OFFSET) | \
      (0x1 << RCC_DEV2_PORT_STRAP5_STRAP_ACS_UPSTREAM_FORWARDING_DN_DEV2_OFFSET) | \
      (0x1 << RCC_DEV2_PORT_STRAP5_STRAP_ACS_DIRECT_TRANSLATED_P2P_DN_DEV2_OFFSET) \
    ),

  // End of NBIO_NBIF_DISABLE_AER_TBL


// --------------------------------------------------
// FLR disable
// atomic disable
// --------------------------------------------------

  #define NBIO_NBIF_DISABLE_FLR_ATOMIC_TBL \
    GNB_ENTRY_PROPERTY_RMW ( \
      TABLE_PROPERTY_IGFX_DISABLED, \
      ONE_ADDR_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV0_EPF0_STRAP4_ADDRESS, \
      RCC_DEV0_EPF0_STRAP4_STRAP_ATOMIC_EN_DEV0_F0_MASK | \
      RCC_DEV0_EPF0_STRAP4_STRAP_FLR_EN_DEV0_F0_MASK | \
      RCC_DEV0_EPF0_STRAP4_STRAP_ATOMIC_64BIT_EN_DEV0_F0_MASK, \
      (0x0 << RCC_DEV0_EPF0_STRAP4_STRAP_FLR_EN_DEV0_F0_OFFSET) | \
      (0x0 << RCC_DEV0_EPF0_STRAP4_STRAP_ATOMIC_EN_DEV0_F0_OFFSET) | \
      (0x0 << RCC_DEV0_EPF0_STRAP4_STRAP_ATOMIC_64BIT_EN_DEV0_F0_OFFSET) \
      ),
  // End of NBIO_NBIF_DISABLE_AER_TBL


// --------------------------------------------------
// 14.6.9.5.2 DMA Arbitration
// --------------------------------------------------

  // NBIFMM::BIF_GMI_WRR_WEIGHT2[GMI_REQ_ENTRY0_WEIGHT] = 4h.
  // NBIFMM::BIF_GMI_WRR_WEIGHT2[GMI_REQ_ENTRY1_WEIGHT] = 4h.
  // NBIFMM::BIF_GMI_WRR_WEIGHT2[GMI_REQ_ENTRY2_WEIGHT] = 4h.
  // NBIFMM::BIF_GMI_WRR_WEIGHT2[GMI_REQ_ENTRY3_WEIGHT] = 4h.
  // NBIFMM::BIF_GMI_WRR_WEIGHT3[GMI_REQ_ENTRY4_WEIGHT] = 4h.
  // NBIFMM::BIF_GMI_WRR_WEIGHT3[GMI_REQ_ENTRY5_WEIGHT] = 4h.
  // NBIFMM::BIF_GMI_WRR_WEIGHT3[GMI_REQ_ENTRY6_WEIGHT] = 4h.
  // NBIFMM::BIF_GMI_WRR_WEIGHT3[GMI_REQ_ENTRY7_WEIGHT] = 4h.
  #define NBIO_NBIF_DMA_ARBITRATION_TBL \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_NBIF0_BIF_GMI_WRR_WEIGHT2_ADDRESS, \
      BIF_GMI_WRR_WEIGHT2_GMI_REQ_ENTRY0_WEIGHT_MASK | \
      BIF_GMI_WRR_WEIGHT2_GMI_REQ_ENTRY1_WEIGHT_MASK | \
      BIF_GMI_WRR_WEIGHT2_GMI_REQ_ENTRY2_WEIGHT_MASK | \
      BIF_GMI_WRR_WEIGHT2_GMI_REQ_ENTRY3_WEIGHT_MASK, \
      (0x4 << BIF_GMI_WRR_WEIGHT2_GMI_REQ_ENTRY0_WEIGHT_OFFSET) | \
      (0x4 << BIF_GMI_WRR_WEIGHT2_GMI_REQ_ENTRY1_WEIGHT_OFFSET) | \
      (0x4 << BIF_GMI_WRR_WEIGHT2_GMI_REQ_ENTRY2_WEIGHT_OFFSET) | \
      (0x4 << BIF_GMI_WRR_WEIGHT2_GMI_REQ_ENTRY3_WEIGHT_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_NBIF0_BIF_GMI_WRR_WEIGHT3_ADDRESS, \
      BIF_GMI_WRR_WEIGHT3_GMI_REQ_ENTRY4_WEIGHT_MASK | \
      BIF_GMI_WRR_WEIGHT3_GMI_REQ_ENTRY5_WEIGHT_MASK | \
      BIF_GMI_WRR_WEIGHT3_GMI_REQ_ENTRY6_WEIGHT_MASK | \
      BIF_GMI_WRR_WEIGHT3_GMI_REQ_ENTRY7_WEIGHT_MASK, \
      (0x4 << BIF_GMI_WRR_WEIGHT3_GMI_REQ_ENTRY4_WEIGHT_OFFSET) | \
      (0x4 << BIF_GMI_WRR_WEIGHT3_GMI_REQ_ENTRY5_WEIGHT_OFFSET) | \
      (0x4 << BIF_GMI_WRR_WEIGHT3_GMI_REQ_ENTRY6_WEIGHT_OFFSET) | \
      (0x4 << BIF_GMI_WRR_WEIGHT3_GMI_REQ_ENTRY7_WEIGHT_OFFSET) \
      ),
  // End of NBIO_NBIF_DMA_ARBITRATION_TBL


// --------------------------------------------------
// 14.6.9.6.1 Clock Gating Feature
// --------------------------------------------------

  // Set NBIFMM::NBIF_MGCG_CTRL_LCLK[NBIF_MGCG_EN_LCLK] = 1h.
  // Set SYSHUBMM::SYSHUB_MGCG_CTRL_SHUBCLK[SYSHUB_MGCG_EN_SHUBCLK] = 1h.
  // Set SYSHUBMM::SYSHUB_MGCG_CTRL_SOCCLK[SYSHUB_MGCG_EN_SOCCLK] = 1h.
  #define NBIO_NBIF_CLOCK_GATING_TBL \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdCfgNbifMgcgClkGating), \
      TRUE, \
      SMN_NBIF0_NBIF_MGCG_CTRL_LCLK_ADDRESS, \
      NBIF_MGCG_CTRL_LCLK_NBIF_MGCG_EN_LCLK_MASK, \
      (0x1 << NBIF_MGCG_CTRL_LCLK_NBIF_MGCG_EN_LCLK_OFFSET) \
      ), \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdCfgSyshubMgcgClkGating), \
      TRUE, \
      SMN_NBIF0_SYSHUB_MGCG_CTRL_SHUBCLK_ADDRESS, \
      SYSHUB_MGCG_CTRL_SHUBCLK_SYSHUB_MGCG_EN_SHUBCLK_MASK, \
      (0x1 << SYSHUB_MGCG_CTRL_SHUBCLK_SYSHUB_MGCG_EN_SHUBCLK_OFFSET) \
      ), \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdCfgSyshubMgcgClkGating), \
      TRUE, \
      SMN_NBIF0_SYSHUB_MGCG_CTRL_SOCCLK_ADDRESS, \
      SYSHUB_MGCG_CTRL_SOCCLK_SYSHUB_MGCG_EN_SOCCLK_MASK, \
      (0x1 << SYSHUB_MGCG_CTRL_SOCCLK_SYSHUB_MGCG_EN_SOCCLK_OFFSET) \
      ),
  // End of NBIO_NBIF_CLOCK_GATING_TBL


// --------------------------------------------------
// 14.6.9.6.2 Power Gating Feature
// --------------------------------------------------

  // Set NBIFMM::NBIF_PGMST_CTRL[NBIF_CFG_PG_HYSTERESIS] = 10h. //DERMBE-598
  // Set NBIFMM::NBIF_PGMST_CTRL[NBIF_CFG_PG_EN] = 1h.
  #define NBIO_NBIF_POWER_GATING_TBL \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdCfgNbifPgClkGating), \
      TRUE, \
      SMN_NBIF0_NBIF_PGMST_CTRL_ADDRESS, \
      NBIF_PGMST_CTRL_NBIF_CFG_PG_HYSTERESIS_MASK | \
      NBIF_PGMST_CTRL_NBIF_CFG_PG_EN_MASK, \
      (0x10 << NBIF_PGMST_CTRL_NBIF_CFG_PG_HYSTERESIS_OFFSET) | \
      (0x1 << NBIF_PGMST_CTRL_NBIF_CFG_PG_EN_OFFSET) \
      ),
  // End of NBIO_NBIF_POWER_GATING_TBL


// --------------------------------------------------
// Syshub Power Gating Feature  - PPR missing PLAT-73094
// --------------------------------------------------

  // Set SYSHUBMM::NGDC_PGMST_CTRL[NGDC_CFG_PG_HYSTERESIS] = 50h.
  // Set SYSHUBMM::NGDC_PGMST_CTRL[NGDC_CFG_PG_EN] = 1h.
  #define NBIO_NBIF_SHUB_POWER_GATING_TBL \
  GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
    ALL_NBIO_TYPE, \
    PcdToken(PcdSyshubPg), \
    TRUE, \
    SMN_NBIF0_NGDC_PGMST_CTRL_ADDRESS, \
    NGDC_PGMST_CTRL_NGDC_CFG_PG_HYSTERESIS_MASK | \
    NGDC_PGMST_CTRL_NGDC_CFG_PG_EN_MASK, \
    (0x50 << NGDC_PGMST_CTRL_NGDC_CFG_PG_HYSTERESIS_OFFSET) | \
    (0x1 << NGDC_PGMST_CTRL_NGDC_CFG_PG_EN_OFFSET) \
    ),
  // End of NBIO_NBIF_SHUB_POWER_GATING_TBL

// --------------------------------------------------
// 14.6.9.5.5 Atomic
// --------------------------------------------------
  // NBIFMM::RCC_DEV0_PORT_STRAP5[STRAP_ATOMIC_ROUTING_EN_DEV0] = 0x1
  // NBIFEPFCFG::DEVICE_CNTL2[ATOMICOP_REQUEST_EN] = 0x1
  // NBIFEPFCFG::DEVICE_CNTL2[ATOMICOP_EGRESS_BLOCKING] = 0x0
  // NBIFMM::RCC_DEV0_PORT_STRAP5[STRAP_ATOMIC_ROUTING_EN_DEV0] = 0x1
  // NBIFMM::RCC_DEV0_EPF0_STRAP4[STRAP_ATOMIC_64BIT_EN_DEV0_F0] = 0x1
  // NBIFMM::RCC_DEV0_EPF0_STRAP4[STRAP_ATOMIC_EN_DEV0_F0] = 0x1
  #define NBIO_NBIF_ATOMIC_TBL \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV0_PORT_STRAP5_ADDRESS, \
      RCC_DEV0_PORT_STRAP5_STRAP_ATOMIC_ROUTING_EN_DEV0_MASK, \
      (0x1 << RCC_DEV0_PORT_STRAP5_STRAP_ATOMIC_ROUTING_EN_DEV0_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_DEV0_FUNC0_NBIF0_DEVICE_CNTL2_ADDRESS, \
      DEVICE_CNTL2_ATOMICOP_REQUEST_EN_MASK | \
      DEVICE_CNTL2_ATOMICOP_EGRESS_BLOCKING_MASK, \
      (0x1 << DEVICE_CNTL2_ATOMICOP_REQUEST_EN_OFFSET) |\
      (0x0 << DEVICE_CNTL2_ATOMICOP_EGRESS_BLOCKING_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_DEV0_FUNC1_NBIF0_DEVICE_CNTL2_ADDRESS, \
      DEVICE_CNTL2_ATOMICOP_REQUEST_EN_MASK | \
      DEVICE_CNTL2_ATOMICOP_EGRESS_BLOCKING_MASK, \
      (0x1 << DEVICE_CNTL2_ATOMICOP_REQUEST_EN_OFFSET) |\
      (0x0 << DEVICE_CNTL2_ATOMICOP_EGRESS_BLOCKING_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV0_PORT_STRAP5_ADDRESS, \
      RCC_DEV0_PORT_STRAP5_STRAP_ATOMIC_ROUTING_EN_DEV0_MASK, \
      (0x1 << RCC_DEV0_PORT_STRAP5_STRAP_ATOMIC_ROUTING_EN_DEV0_OFFSET) \
      ), \
    GNB_ENTRY_RMW ( \
      ALL_NBIO_TYPE, \
      SMN_NBIF0INTERNAL_RCC_DEV0_EPF0_STRAP4_ADDRESS, \
      RCC_DEV0_EPF0_STRAP4_STRAP_ATOMIC_64BIT_EN_DEV0_F0_MASK | \
      RCC_DEV0_EPF0_STRAP4_STRAP_ATOMIC_EN_DEV0_F0_MASK, \
      (0x1 << RCC_DEV0_EPF0_STRAP4_STRAP_ATOMIC_64BIT_EN_DEV0_F0_OFFSET) | \
      (0x1 << RCC_DEV0_EPF0_STRAP4_STRAP_ATOMIC_EN_DEV0_F0_OFFSET) \
      ),
  // End of NBIO_NBIF_ATOMIC_TBL

// --------------------------------------------------
// 14.6.9.5.6 PerfReg Final Setting
// --------------------------------------------------
  // SYSHUBMM::DMA_CLK1_SW1_CL4_CNTL[READ_WRR_WEIGHT] = 20h.
  // SYSHUBMM::DMA_CLK1_SW1_CL4_CNTL[WRITE_WRR_WEIGHT] = 20h.
  // SYSHUBMM::A2S_CNTL_SW3[WRR_WR_WEIGHT] =4h.
  // SYSHUBMM::A2S_CNTL_SW3[WRR_RD_WEIGHT] = 4h.
  // NBIFMM::BIFC_GMI_SDP_REQ_POOLCRED_ALLOC = 160_1011h.
  // NBIFMM::BIFC_GMI_SDP_DAT_POOLCRED_ALLOC = 280_2022h.
  // NBIFMM::BIF_GMI_WRR_WEIGHT2[GMI_REQ_ENTRY0_WEIGHT] = 4h.
  // NBIFMM::BIF_GMI_WRR_WEIGHT2[GMI_REQ_ENTRY1_WEIGHT] = 4h.
  // NBIFMM::BIF_GMI_WRR_WEIGHT2[GMI_REQ_ENTRY3_WEIGHT] = 60h.
  // NBIFMM::BIF_GMI_WRR_WEIGHT3[GMI_REQ_ENTRY4_WEIGHT] = 08h.
  // SYSHUBMM::SION_CL2_Req_TimeSlot_REG1[Req_TimeSlot_63_32] = 0006_0006h.
  // SYSHUBMM::SION_CL2_Req_TimeSlot_REG0[Req_TimeSlot_31_0] = 0006_0006h.
  // SYSHUBMM::SION_CL0_Req_TimeSlot_REG1[Req_TimeSlot_63_32] = 2303_0303h.
  // SYSHUBMM::SION_CL0_Req_TimeSlot_REG0[Req_TimeSlot_31_0] = 3303_0303h.
  // SYSHUBMM::SION_CNTL_REG1[LIVELOCK_WATCHDOG_THRESHOLD] = f0h.
  #define NBIO_NBIF_PERF_REG_TBL \
  GNB_ENTRY_RMW ( \
    ALL_NBIO_TYPE, \
    SMN_NBIF0_DMA_CLK1_SW1_CL4_CNTL_ADDRESS, \
    DMA_CLK1_SW1_CL4_CNTL_READ_WRR_WEIGHT_MASK | \
    DMA_CLK1_SW1_CL4_CNTL_WRITE_WRR_WEIGHT_MASK, \
    (0x20 << DMA_CLK1_SW1_CL4_CNTL_READ_WRR_WEIGHT_OFFSET) | \
    (0x20 << DMA_CLK1_SW1_CL4_CNTL_WRITE_WRR_WEIGHT_OFFSET) \
    ), \
  GNB_ENTRY_RMW ( \
    ALL_NBIO_TYPE, \
    SMN_NBIF0_A2S_CNTL_SW3_ADDRESS, \
    A2S_CNTL_SW3_WRR_WR_WEIGHT_MASK | \
    A2S_CNTL_SW3_WRR_RD_WEIGHT_MASK, \
    (0x4 << A2S_CNTL_SW3_WRR_WR_WEIGHT_OFFSET) | \
    (0x4 << A2S_CNTL_SW3_WRR_RD_WEIGHT_OFFSET) \
    ), \
  GNB_ENTRY_RMW ( \
    ALL_NBIO_TYPE, \
    SMN_NBIF0_BIFC_GMI_SDP_REQ_POOLCRED_ALLOC_ADDRESS, \
    0xFFFFFFFF, \
    0x1601011 \
    ), \
  GNB_ENTRY_RMW ( \
    ALL_NBIO_TYPE, \
    SMN_NBIF0_BIFC_GMI_SDP_DAT_POOLCRED_ALLOC_ADDRESS, \
    0xFFFFFFFF, \
    0x2802022 \
    ), \
  GNB_ENTRY_RMW ( \
    ALL_NBIO_TYPE, \
    SMN_NBIF0_BIF_GMI_WRR_WEIGHT2_ADDRESS, \
    BIF_GMI_WRR_WEIGHT2_GMI_REQ_ENTRY0_WEIGHT_MASK | \
    BIF_GMI_WRR_WEIGHT2_GMI_REQ_ENTRY1_WEIGHT_MASK | \
    BIF_GMI_WRR_WEIGHT2_GMI_REQ_ENTRY3_WEIGHT_MASK, \
    (0x4 << BIF_GMI_WRR_WEIGHT2_GMI_REQ_ENTRY0_WEIGHT_OFFSET) | \
    (0x4 << BIF_GMI_WRR_WEIGHT2_GMI_REQ_ENTRY1_WEIGHT_OFFSET) | \
    (0x60 << BIF_GMI_WRR_WEIGHT2_GMI_REQ_ENTRY3_WEIGHT_OFFSET) \
    ), \
  GNB_ENTRY_RMW ( \
    ALL_NBIO_TYPE, \
    SMN_NBIF0_BIF_GMI_WRR_WEIGHT3_ADDRESS, \
    BIF_GMI_WRR_WEIGHT3_GMI_REQ_ENTRY4_WEIGHT_MASK, \
    (0x8 << BIF_GMI_WRR_WEIGHT3_GMI_REQ_ENTRY4_WEIGHT_OFFSET) \
    ), \
  GNB_ENTRY_RMW ( \
    ALL_NBIO_TYPE, \
    SMN_NBIF0_SION_CL2_Req_TimeSlot_REG1_ADDRESS, \
    SION_CL2_Req_TimeSlot_REG1_Req_TimeSlot_63_32_MASK, \
    (0x00060006 << SION_CL2_Req_TimeSlot_REG1_Req_TimeSlot_63_32_OFFSET) \
    ), \
  GNB_ENTRY_RMW ( \
    ALL_NBIO_TYPE, \
    SMN_NBIF0_SION_CL2_Req_TimeSlot_REG0_ADDRESS, \
    SION_CL2_Req_TimeSlot_REG0_Req_TimeSlot_31_0_MASK, \
    (0x00060006 << SION_CL2_Req_TimeSlot_REG0_Req_TimeSlot_31_0_OFFSET) \
    ), \
  GNB_ENTRY_RMW ( \
    ALL_NBIO_TYPE, \
    SMN_NBIF0_SION_CL0_Req_TimeSlot_REG1_ADDRESS, \
    SION_CL0_Req_TimeSlot_REG1_Req_TimeSlot_63_32_MASK, \
    (0x23030303 << SION_CL0_Req_TimeSlot_REG1_Req_TimeSlot_63_32_OFFSET) \
    ), \
  GNB_ENTRY_RMW ( \
    ALL_NBIO_TYPE, \
    SMN_NBIF0_SION_CL0_Req_TimeSlot_REG0_ADDRESS, \
    SION_CL0_Req_TimeSlot_REG0_Req_TimeSlot_31_0_MASK, \
    (0x33030303 << SION_CL0_Req_TimeSlot_REG0_Req_TimeSlot_31_0_OFFSET) \
    ), \
  GNB_ENTRY_RMW ( \
    ALL_NBIO_TYPE, \
    SMN_NBIF0_SION_CNTL_REG1_ADDRESS, \
    SION_CNTL_REG1_LIVELOCK_WATCHDOG_THRESHOLD_MASK, \
    (0xF0 << SION_CNTL_REG1_LIVELOCK_WATCHDOG_THRESHOLD_OFFSET) \
    ),
  // End of NBIO_NBIF_PERF_REG_TBL

// --------------------------------------------------
// First VF offset
//   There're 8 Pysical Fuctions, so the first VF has to be 8
// --------------------------------------------------
  // Set RCC_CONSOLE_IOV_FIRST_VF_OFFSET[CONSOLE_IOV_FIRST_VF_OFFSET] = 8
  #define NBIO_NBIF_FIRST_VF_OFFSET_TBL \
  GNB_ENTRY_RMW ( \
    ONE_ADDR_TYPE, \
    SMN_DEV0_NBIF0_RCC_CONSOLE_IOV_FIRST_VF_OFFSET_ADDRESS, \
    RCC_CONSOLE_IOV_FIRST_VF_OFFSET_CONSOLE_IOV_FIRST_VF_OFFSET_MASK, \
    (8 << RCC_CONSOLE_IOV_FIRST_VF_OFFSET_CONSOLE_IOV_FIRST_VF_OFFSET_OFFSET) \
    ),
  // End of NBIO_NBIF_FIRST_VF_OFFSET

// --------------------------------------------------
// NBIF HSP CLOCK DS
// --------------------------------------------------
  // Set CLK0_CLK11_ALLOW_DS_n0[CLK11_ALLOW_DS] = 1
  //     SYSHUB_DS_CTRL_HSPCLK[SYSHUB_HSPCLK_DS_EN] = 1
  #define NBIO_NBIF_HSP_CLOCK_DS_TBL \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdEnableHspClkDs), \
      TRUE, \
      SMN_N0_CLK0_CLK11_ALLOW_DS_ADDRESS, \
      CLK0_CLK11_ALLOW_DS_CLK11_ALLOW_DS_MASK, \
      (0x1 << CLK0_CLK11_ALLOW_DS_CLK11_ALLOW_DS_OFFSET) \
      ), \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdEnableHspClkDs), \
      TRUE, \
      SMN_NBIF0_SYSHUB_DS_CTRL_HSPCLK_ADDRESS, \
      SYSHUB_DS_CTRL_HSPCLK_SYSHUB_HSPCLK_DS_EN_MASK, \
      (0x1 << SYSHUB_DS_CTRL_HSPCLK_SYSHUB_HSPCLK_DS_EN_OFFSET) \
      ),
  // End of NBIO_NBIF_HSP_CLOCK_DS_TBL

// --------------------------------------------------
// NBIF OBFF CTRL
// --------------------------------------------------
  // Set OBFF_EMU_CFG[OBFF_EMU_INTR_EN] = 1
  //     OBFF_EMU_CFG_SOCCLK[OBFF_EMU_DMA_EN] = 1
  #define NBIO_NBIF_OBFF_CTRL_TBL \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdEnableNbifOBFF), \
      TRUE, \
      SMN_NBIF0_OBFF_EMU_CFG_ADDRESS, \
      OBFF_EMU_CFG_OBFF_EMU_INTR_EN_MASK, \
      (0x1 << OBFF_EMU_CFG_OBFF_EMU_INTR_EN_OFFSET) \
      ), \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdEnableNbifDmaOBFF), \
      TRUE, \
      SMN_NBIF0_OBFF_EMU_CFG_SOCCLK_ADDRESS, \
      OBFF_EMU_CFG_SOCCLK_OBFF_EMU_DMA_EN_MASK, \
      (0x1 << OBFF_EMU_CFG_SOCCLK_OBFF_EMU_DMA_EN_OFFSET) \
      ),
  // End of NBIO_NBIF_OBFF_CTRL_TBL

// --------------------------------------------------
// SYSHUB NGDC MGCG Clock Gating
// --------------------------------------------------

  // Set SYSHUBMM::NGDC_MGCG_CTRL[NGDC_MGCG_EN] = 1h.
  #define NBIO_SYSHUB_NGDC_MGCG_CTR_CLOCK_GATING_TBL \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdCfgSyshubGdcMgcgClkGating), \
      TRUE, \
      SMN_NGDC_MGCG_CTRL_ADDRESS, \
      NGDC_MGCG_CTRL_NGDC_MGCG_EN_MASK, \
      (0x1 << NGDC_MGCG_CTRL_NGDC_MGCG_EN_OFFSET) \
      ),
  // End of NBIO_SYSHUB_NGDC_MGCG_CTR_CLOCK_GATING_TBL

// --------------------------------------------------
// SYSHUB NGDC MGCG Clock Gating
// --------------------------------------------------

  // Set SYSHUBMM::SYSHUB_MGCG_CTRL_HSPCLK[SYSHUB_MGCG_EN_HSPCLK] = 1h.
  #define NBIO_SYSHUB_MGCG_CTRL_HSP_CLOCK_GATING_TBL \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdCfgSyshubMgcgHspClkGating), \
      TRUE, \
      SMN_SYSHUB_MGCG_CTRL_HSPCLK_ADDRESS, \
      SYSHUB_MGCG_CTRL_HSPCLK_SYSHUB_MGCG_EN_HSPCLK_MASK, \
      (0x1 << SYSHUB_MGCG_CTRL_HSPCLK_SYSHUB_MGCG_EN_HSPCLK_OFFSET) \
      ),
  // End of NBIO_SYSHUB_MGCG_CTRL_HSP_CLOCK_GATING_TBL

// --------------------------------------------------
// ATHUB MISC CNTL
// --------------------------------------------------
  #define NBIO_ATHUB_MISC_CNTL_TBL \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdAthubClockGating), \
      FALSE, \
      SMN_ATHUB_MISC_CNTL_ADDRESS, \
      ATHUB_MISC_CNTL_CG_ENABLE_MASK, \
      (0 << ATHUB_MISC_CNTL_CG_ENABLE_OFFSET) \
      ), \
    GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
      ALL_NBIO_TYPE, \
      PcdToken(PcdAthubClockGating), \
      TRUE, \
      SMN_ATHUB_MISC_CNTL_ADDRESS, \
      ATHUB_MISC_CNTL_CG_ENABLE_MASK, \
      (0x1 << ATHUB_MISC_CNTL_CG_ENABLE_OFFSET) \
      ),
  // End of NBIO_ATHUB_MISC_CNTL_TBL

// ACS
  #define NBIO_NBIF_ACS_CNTL_TBL \
  GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
    ALL_NBIO_TYPE, \
    PcdToken(PcdCfgACSEnable), \
    TRUE, \
    SMN_NBIF0INTERNAL_RCC_DEV0_PORT_STRAP0_ADDRESS, \
    RCC_DEV0_PORT_STRAP0_STRAP_ACS_EN_DN_DEV0_MASK, \
    (0x1 << RCC_DEV0_PORT_STRAP0_STRAP_ACS_EN_DN_DEV0_OFFSET) \
    ), \
  GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
    ALL_NBIO_TYPE, \
    PcdToken(PcdCfgACSEnable), \
    TRUE, \
    SMN_NBIF0INTERNAL_RCC_DEV1_PORT_STRAP0_ADDRESS, \
    RCC_DEV0_PORT_STRAP0_STRAP_ACS_EN_DN_DEV0_MASK, \
    (0x1 << RCC_DEV0_PORT_STRAP0_STRAP_ACS_EN_DN_DEV0_OFFSET) \
    ), \
  GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
    ALL_NBIO_TYPE, \
    PcdToken(PcdCfgACSEnable), \
    TRUE, \
    SMN_NBIF0INTERNAL_RCC_DEV2_PORT_STRAP0_ADDRESS, \
    RCC_DEV0_PORT_STRAP0_STRAP_ACS_EN_DN_DEV0_MASK, \
    (0x1 << RCC_DEV0_PORT_STRAP0_STRAP_ACS_EN_DN_DEV0_OFFSET) \
    ), \
  GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
    ALL_NBIO_TYPE, \
    PcdToken(PcdCfgACSEnable), \
    TRUE, \
    SMN_NBIF0INTERNAL_RCC_DEV0_EPF0_STRAP2_ADDRESS, \
    RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_MASK, \
    (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_OFFSET) \
    ), \
  GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
    ALL_NBIO_TYPE, \
    PcdToken(PcdCfgACSEnable), \
    TRUE, \
    SMN_NBIF0INTERNAL_RCC_DEV0_EPF1_STRAP2_ADDRESS, \
    RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_MASK, \
    (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_OFFSET) \
    ), \
  GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
    ALL_NBIO_TYPE, \
    PcdToken(PcdCfgACSEnable), \
    TRUE, \
    SMN_NBIF0INTERNAL_RCC_DEV0_EPF2_STRAP2_ADDRESS, \
    RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_MASK, \
    (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_OFFSET) \
    ), \
  GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
    ALL_NBIO_TYPE, \
    PcdToken(PcdCfgACSEnable), \
    TRUE, \
    SMN_NBIF0INTERNAL_RCC_DEV0_EPF3_STRAP2_ADDRESS, \
    RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_MASK, \
    (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_OFFSET) \
    ), \
  GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
    ALL_NBIO_TYPE, \
    PcdToken(PcdCfgACSEnable), \
    TRUE, \
    SMN_NBIF0INTERNAL_RCC_DEV0_EPF4_STRAP2_ADDRESS, \
    RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_MASK, \
    (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_OFFSET) \
    ), \
  GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
    ALL_NBIO_TYPE, \
    PcdToken(PcdCfgACSEnable), \
    TRUE, \
    SMN_NBIF0INTERNAL_RCC_DEV0_EPF5_STRAP2_ADDRESS, \
    RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_MASK, \
    (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_OFFSET) \
    ), \
  GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
    ALL_NBIO_TYPE, \
    PcdToken(PcdCfgACSEnable), \
    TRUE, \
    SMN_NBIF0INTERNAL_RCC_DEV0_EPF6_STRAP2_ADDRESS, \
    RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_MASK, \
    (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_OFFSET) \
    ), \
  GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
    ALL_NBIO_TYPE, \
    PcdToken(PcdCfgACSEnable), \
    TRUE, \
    SMN_NBIF0INTERNAL_RCC_DEV0_EPF7_STRAP2_ADDRESS, \
    RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_MASK, \
    (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_OFFSET) \
    ), \
  GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
    ALL_NBIO_TYPE, \
    PcdToken(PcdCfgACSEnable), \
    TRUE, \
    SMN_NBIF0INTERNAL_RCC_DEV1_EPF0_STRAP2_ADDRESS, \
    RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_MASK, \
    (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_OFFSET) \
    ), \
  GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
    ALL_NBIO_TYPE, \
    PcdToken(PcdCfgACSEnable), \
    TRUE, \
    SMN_NBIF0INTERNAL_RCC_DEV2_EPF0_STRAP2_ADDRESS, \
    RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_MASK, \
    (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_OFFSET) \
    ), \
  GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
    ALL_NBIO_TYPE, \
    PcdToken(PcdCfgACSEnable), \
    TRUE, \
    SMN_NBIF0INTERNAL_RCC_DEV2_EPF2_STRAP2_ADDRESS, \
    RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_MASK, \
    (0x1 << RCC_DEV0_EPF0_STRAP2_STRAP_ACS_EN_DEV0_F0_OFFSET) \
    ), \
  GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
    ALL_NBIO_TYPE, \
    PcdToken(PcdCfgACSEnable), \
    TRUE, \
    SMN_NBIF0INTERNAL_RCC_DEV0_PORT_STRAP5_ADDRESS, \
    RCC_DEV0_PORT_STRAP5_STRAP_ACS_SOURCE_VALIDATION_DN_DEV0_MASK | \
    RCC_DEV0_PORT_STRAP5_STRAP_ACS_TRANSLATION_BLOCKING_DN_DEV0_MASK | \
    RCC_DEV0_PORT_STRAP5_STRAP_ACS_P2P_REQUEST_REDIRECT_DN_DEV0_MASK | \
    RCC_DEV0_PORT_STRAP5_STRAP_ACS_P2P_COMPLETION_REDIRECT_DN_DEV0_MASK | \
    RCC_DEV0_PORT_STRAP5_STRAP_ACS_UPSTREAM_FORWARDING_DN_DEV0_MASK | \
    RCC_DEV0_PORT_STRAP5_STRAP_ACS_DIRECT_TRANSLATED_P2P_DN_DEV0_MASK, \
    (0x1 << RCC_DEV0_PORT_STRAP5_STRAP_ACS_SOURCE_VALIDATION_DN_DEV0_OFFSET) | \
    (0x1 << RCC_DEV0_PORT_STRAP5_STRAP_ACS_TRANSLATION_BLOCKING_DN_DEV0_OFFSET) | \
    (0x1 << RCC_DEV0_PORT_STRAP5_STRAP_ACS_P2P_REQUEST_REDIRECT_DN_DEV0_OFFSET) | \
    (0x1 << RCC_DEV0_PORT_STRAP5_STRAP_ACS_P2P_COMPLETION_REDIRECT_DN_DEV0_OFFSET) | \
    (0x1 << RCC_DEV0_PORT_STRAP5_STRAP_ACS_UPSTREAM_FORWARDING_DN_DEV0_OFFSET) | \
    (0x1 << RCC_DEV0_PORT_STRAP5_STRAP_ACS_DIRECT_TRANSLATED_P2P_DN_DEV0_OFFSET) \
    ), \
  GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
    ALL_NBIO_TYPE, \
    PcdToken(PcdCfgACSEnable), \
    TRUE, \
    SMN_NBIF0INTERNAL_RCC_DEV1_PORT_STRAP5_ADDRESS, \
    RCC_DEV0_PORT_STRAP5_STRAP_ACS_SOURCE_VALIDATION_DN_DEV0_MASK | \
    RCC_DEV0_PORT_STRAP5_STRAP_ACS_TRANSLATION_BLOCKING_DN_DEV0_MASK | \
    RCC_DEV0_PORT_STRAP5_STRAP_ACS_P2P_REQUEST_REDIRECT_DN_DEV0_MASK | \
    RCC_DEV0_PORT_STRAP5_STRAP_ACS_P2P_COMPLETION_REDIRECT_DN_DEV0_MASK | \
    RCC_DEV0_PORT_STRAP5_STRAP_ACS_UPSTREAM_FORWARDING_DN_DEV0_MASK | \
    RCC_DEV0_PORT_STRAP5_STRAP_ACS_DIRECT_TRANSLATED_P2P_DN_DEV0_MASK, \
    (0x1 << RCC_DEV0_PORT_STRAP5_STRAP_ACS_SOURCE_VALIDATION_DN_DEV0_OFFSET) | \
    (0x1 << RCC_DEV0_PORT_STRAP5_STRAP_ACS_TRANSLATION_BLOCKING_DN_DEV0_OFFSET) | \
    (0x1 << RCC_DEV0_PORT_STRAP5_STRAP_ACS_P2P_REQUEST_REDIRECT_DN_DEV0_OFFSET) | \
    (0x1 << RCC_DEV0_PORT_STRAP5_STRAP_ACS_P2P_COMPLETION_REDIRECT_DN_DEV0_OFFSET) | \
    (0x1 << RCC_DEV0_PORT_STRAP5_STRAP_ACS_UPSTREAM_FORWARDING_DN_DEV0_OFFSET) | \
    (0x1 << RCC_DEV0_PORT_STRAP5_STRAP_ACS_DIRECT_TRANSLATED_P2P_DN_DEV0_OFFSET) \
    ), \
  GNB_ENTRY_RMW_IF_PCD_EQUAL ( \
    ALL_NBIO_TYPE, \
    PcdToken(PcdCfgACSEnable), \
    TRUE, \
    SMN_NBIF0INTERNAL_RCC_DEV2_PORT_STRAP5_ADDRESS, \
    RCC_DEV0_PORT_STRAP5_STRAP_ACS_SOURCE_VALIDATION_DN_DEV0_MASK | \
    RCC_DEV0_PORT_STRAP5_STRAP_ACS_TRANSLATION_BLOCKING_DN_DEV0_MASK | \
    RCC_DEV0_PORT_STRAP5_STRAP_ACS_P2P_REQUEST_REDIRECT_DN_DEV0_MASK | \
    RCC_DEV0_PORT_STRAP5_STRAP_ACS_P2P_COMPLETION_REDIRECT_DN_DEV0_MASK | \
    RCC_DEV0_PORT_STRAP5_STRAP_ACS_UPSTREAM_FORWARDING_DN_DEV0_MASK | \
    RCC_DEV0_PORT_STRAP5_STRAP_ACS_DIRECT_TRANSLATED_P2P_DN_DEV0_MASK, \
    (0x1 << RCC_DEV0_PORT_STRAP5_STRAP_ACS_SOURCE_VALIDATION_DN_DEV0_OFFSET) | \
    (0x1 << RCC_DEV0_PORT_STRAP5_STRAP_ACS_TRANSLATION_BLOCKING_DN_DEV0_OFFSET) | \
    (0x1 << RCC_DEV0_PORT_STRAP5_STRAP_ACS_P2P_REQUEST_REDIRECT_DN_DEV0_OFFSET) | \
    (0x1 << RCC_DEV0_PORT_STRAP5_STRAP_ACS_P2P_COMPLETION_REDIRECT_DN_DEV0_OFFSET) | \
    (0x1 << RCC_DEV0_PORT_STRAP5_STRAP_ACS_UPSTREAM_FORWARDING_DN_DEV0_OFFSET) | \
    (0x1 << RCC_DEV0_PORT_STRAP5_STRAP_ACS_DIRECT_TRANSLATED_P2P_DN_DEV0_OFFSET) \
    ),
  // End of NBIO_NBIF_ACS_CNTL_TBL
#endif /* _NBIO_NBIF_TABLE_H_ */
