/*******************************************************************************
*
 * Copyright (C) 2021-2022 Advanced Micro Devices, Inc. All rights reserved.
 *
*******************************************************************************/

#include <MyPorting.h>
#include <APCB.h>
#include "ApcbCustomizedDefinitions.h"
#include "ApcbCustomizedBoardDefinitions.h"
#include <ApcbDefaults.h>

APCB_TYPE_DATA_START_SIGNATURE();
APCB_V3_TYPE_HEADER       ApcbTypeHeader = {
  APCB_GROUP_FCH,                           // GroupId
  APCB_FCH_TYPE_ESPI_INIT,                  // TypeId
  sizeof(ApcbTypeHeader),                   // SizeOfType, will be fixed up by tool
  0,                                        // InstanceId
  {
    APCB_TYPE_ATTR_CONTEXT_TYPE_STRUCT,
    APCB_TYPE_ATTR_CONTEXT_FORMAT_NATIVE_RAW,
    0,
    APCB_PRIORITY_TYPE_MASK_DEFAULT,        // Priority mask
    0,
    0,
    BLDCFG_APCB_DATA_BOARD_MASK             // Board specific APCB instance mask
  }
};  // SizeOfType will be fixed up by tool

///< Platform Specific Overrides
APCB_FCH_ESPI_INIT_STRUCT EspiInitConfig = {

#ifdef APCB_TOKEN_UID_ESPI_ABL_INIT_ENABLE_VALUE
  APCB_TOKEN_UID_ESPI_ABL_INIT_ENABLE_VALUE,
#else
  TRUE,
#endif

#ifdef APCB_TOKEN_UID_ESPI_DATA_SELECTION_VALUE
  APCB_TOKEN_UID_ESPI_DATA_SELECTION_VALUE,
#else
  1,  //ESPI_DATA_SELECTION_VAL_SPI_DATA2
#endif

#ifdef APCB_TOKEN_UID_ESPI_CLOCK_PIN_SELECTION_VALUE
  APCB_TOKEN_UID_ESPI_CLOCK_PIN_SELECTION_VALUE,
#else
  1,  //ESPI_CLOCK_PIN_SELECTION_VAL_GPIO86
#endif

#ifdef APCB_TOKEN_UID_ESPI_CS_SELECTION_VALUE
  APCB_TOKEN_UID_ESPI_CS_SELECTION_VALUE,
#else
  0,  //ESPI_CS_SELECTION_VAL_GPIO30
#endif

#ifdef APCB_TOKEN_UID_ESPI_CLOCK_VALUE
  APCB_TOKEN_UID_ESPI_CLOCK_VALUE,
#else
  0,  //ESPI_CLOCKVAL_16MHZ
#endif

#ifdef APCB_TOKEN_UID_ESPI_IOMODE_VALUE
  APCB_TOKEN_UID_ESPI_IOMODE_VALUE,
#else
  0,  //ESPI_IOMODEVAL_SINGLE
#endif

#ifdef APCB_TOKEN_UID_ESPI_ALERT_MODE_VALUE
  APCB_TOKEN_UID_ESPI_ALERT_MODE_VALUE,
#else
  1,  //ESPI_ALERT_MODE_VAL_ALERT_PIN
#endif

#ifdef APCB_TOKEN_UID_ESPI_PLT_RESET_DEASSERT_VALUE
  APCB_TOKEN_UID_ESPI_PLT_RESET_DEASSERT_VALUE,
#else
  FALSE,
#endif

#ifdef APCB_TOKEN_UID_ESPI_IO80_ENABLE_VALUE
  APCB_TOKEN_UID_ESPI_IO80_ENABLE_VALUE,
#else
  FALSE,
#endif

#ifdef APCB_TOKEN_UID_ESPI_KBC6064_ENABLE_VALUE
  APCB_TOKEN_UID_ESPI_KBC6064_ENABLE_VALUE,
#else
  FALSE,
#endif

  {
  #ifdef APCB_TOKEN_UID_ESPI_IORANGE0_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE0_SIZE_VALUE,
  #else
    0x00,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE1_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE1_SIZE_VALUE,
  #else
    0x00,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE2_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE2_SIZE_VALUE,
  #else
    0x00,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE3_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE3_SIZE_VALUE,
  #else
    0x00,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE4_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE4_SIZE_VALUE,
  #else
    0x00,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE5_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE5_SIZE_VALUE,
  #else
    0x00,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE6_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE6_SIZE_VALUE,
  #else
    0x00,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE7_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE7_SIZE_VALUE,
  #else
    0x00,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE8_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE8_SIZE_VALUE,
  #else
    0x00,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE9_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE9_SIZE_VALUE,
  #else
    0x00,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE10_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE10_SIZE_VALUE,
  #else
    0x00,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE11_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE11_SIZE_VALUE,
  #else
    0x00,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE12_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE12_SIZE_VALUE,
  #else
    0x00,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE13_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE13_SIZE_VALUE,
  #else
    0x00,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE14_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE14_SIZE_VALUE,
  #else
    0x00,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE15_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE15_SIZE_VALUE,
  #else
    0x00,
  #endif
  },

  {
  #ifdef APCB_TOKEN_UID_ESPI_IORANGE0_BASE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE0_BASE_VALUE,
  #else
    0x0000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE1_BASE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE1_BASE_VALUE,
  #else
    0x0000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE2_BASE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE2_BASE_VALUE,
  #else
    0x0000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE3_BASE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE3_BASE_VALUE,
  #else
    0x0000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE4_BASE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE4_BASE_VALUE,
  #else
    0x0000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE5_BASE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE5_BASE_VALUE,
  #else
    0x0000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE6_BASE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE6_BASE_VALUE,
  #else
    0x0000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE7_BASE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE7_BASE_VALUE,
  #else
    0x0000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE8_BASE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE8_BASE_VALUE,
  #else
    0x0000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE9_BASE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE9_BASE_VALUE,
  #else
    0x0000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE10_BASE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE10_BASE_VALUE,
  #else
    0x0000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE11_BASE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE11_BASE_VALUE,
  #else
    0x0000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE12_BASE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE12_BASE_VALUE,
  #else
    0x0000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE13_BASE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE13_BASE_VALUE,
  #else
    0x0000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE14_BASE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE14_BASE_VALUE,
  #else
    0x0000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_IORANGE15_BASE_VALUE
    APCB_TOKEN_UID_ESPI_IORANGE15_BASE_VALUE,
  #else
    0x0000,
  #endif
  },

  {
  #ifdef APCB_TOKEN_UID_ESPI_MMIORANGE0_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_MMIORANGE0_SIZE_VALUE,
  #else
    0x0000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_MMIORANGE1_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_MMIORANGE1_SIZE_VALUE,
  #else
    0x0000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_MMIORANGE2_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_MMIORANGE2_SIZE_VALUE,
  #else
    0x0000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_MMIORANGE3_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_MMIORANGE3_SIZE_VALUE,
  #else
    0x0000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_MMIORANGE4_SIZE_VALUE
    APCB_TOKEN_UID_ESPI_MMIORANGE4_SIZE_VALUE,
  #else
    0x0000,
  #endif
  },

  {
  #ifdef APCB_TOKEN_UID_ESPI_MMIORANGE0_BASE_VALUE
    APCB_TOKEN_UID_ESPI_MMIORANGE0_BASE_VALUE,
  #else
    0x00000000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_MMIORANGE1_BASE_VALUE
    APCB_TOKEN_UID_ESPI_MMIORANGE1_BASE_VALUE,
  #else
    0x00000000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_MMIORANGE2_BASE_VALUE
    APCB_TOKEN_UID_ESPI_MMIORANGE2_BASE_VALUE,
  #else
    0x00000000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_MMIORANGE3_BASE_VALUE
    APCB_TOKEN_UID_ESPI_MMIORANGE3_BASE_VALUE,
  #else
    0x00000000,
  #endif

  #ifdef APCB_TOKEN_UID_ESPI_MMIORANGE4_BASE_VALUE
    APCB_TOKEN_UID_ESPI_MMIORANGE4_BASE_VALUE,
  #else
    0x00000000,
  #endif
  },

#ifdef APCB_TOKEN_UID_ESPI_IRQ_MASK_VALUE
  APCB_TOKEN_UID_ESPI_IRQ_MASK_VALUE,
#else
  0xFFFFFF,
#endif

#ifdef APCB_TOKEN_UID_ESPI_IRQ_POLARITY_VALUE
  APCB_TOKEN_UID_ESPI_IRQ_POLARITY_VALUE,
#else
  0x00000000,
#endif

#ifdef APCB_TOKEN_UID_ESPI_TEMPRTC_VWEN_VALUE
  APCB_TOKEN_UID_ESPI_TEMPRTC_VWEN_VALUE,
#else
  FALSE,
#endif

#ifdef APCB_TOKEN_UID_ESPI_VW_INDEX_SEL_VALUE
  APCB_TOKEN_UID_ESPI_VW_INDEX_SEL_VALUE,
#else
  0x00,
#endif

#ifdef APCB_TOKEN_UID_ESPI_MMIO_CPUTEMP_VALUE
  APCB_TOKEN_UID_ESPI_MMIO_CPUTEMP_VALUE,
#else
  0x00000000,
#endif

#ifdef APCB_TOKEN_UID_ESPI_MMIO_RTCTIME_VALUE
  APCB_TOKEN_UID_ESPI_MMIO_RTCTIME_VALUE,
#else
  0x00000000,
#endif

#ifdef APCB_TOKEN_UID_ESPI_BUS_MASTE_EN_VALUE
  APCB_TOKEN_UID_ESPI_BUS_MASTE_EN_VALUE,
#else
  FALSE,
#endif
};

APCB_TYPE_DATA_END_SIGNATURE();
APCB_DUMMY_MAIN_FUNC();

