@echo on
REM -------------------------------------------------------------------
REM BOARD NAME is set by caller
REM -------------------------------------------------------------------
ECHO *********************************
ECHO BOARD NAME : %BOARD_NAME%
ECHO *********************************

SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_ConsoleOutControl
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_DimmInfoSpd
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_DimmInfoDdr5
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_ErrorOutControl
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_PsoOverride
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_PsBusCfgSODIMMDdr5
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_PsBusCfgSODIMMDdr5_2C80
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_PsBusCfgSODIMMDdr5_AD80
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_PsBusCfgSODIMMDdr5_CE80
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_PsMaxFreqSODIMMDdr5
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_PsStretchFreqSODIMMDdr5
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_PsDramCaPinMapping
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_PsDramDqPinMapping
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_SpdInfoDdr5
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1705_Type_DisplayConnect
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1705_Type_DpPhyStaticConnect
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_ErrorOutIndicatorOpcode
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1706_Type_EspiInitConfiguration
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_MemOverclockConfig
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_MemOverclockMatrix

REM APCB data to enable UDIMM supported CRBs
REM SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_PsBusCfgUDIMMDdr5
REM SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_PsBusCfgUDIMMDdr5_2C80
REM SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_PsBusCfgUDIMMDdr5_AD80
REM SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_PsBusCfgUDIMMDdr5_CE80
REM SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_PsOdtPatUDIMMDdr5
REM SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_PsMaxFreqUDIMMDdr5
REM SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_PsStretchFreqUDIMMDdr5
REM SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_ExtVoltageControl

IF NOT "!APCB_VER!" == "V3" GOTO SKIP_V3_TOKEN_FILES
REM APCB V3 Priority Mapping Customization (To be supported)
REM Disable this temporarily
REM SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_RN_GID_0x1000_Type_PriorityCustomization
REM APCB V3 Tokens
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x3000_Type_TokenBoolean
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x3000_Type_Token1Byte
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x3000_Type_Token2Bytes
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x3000_Type_Token4Bytes

:SKIP_V3_TOKEN_FILES
REM ----------------------------------------------------------------------------
REM BoardIdGettingMethod applies to multiple APCB only, please remove it if
REM only 1 APCB instance is needed
REM ----------------------------------------------------------------------------
IF NOT "%APCB_MULTI_BOARD_SUPPORT%" == "1" GOTO SKIP_MULTI_BOARD_SUPPORT
SET APCB_DATA_TYPE_FILE_LIST=%APCB_DATA_TYPE_FILE_LIST% %BOARD_NAME%\ApcbData_FP7r2_GID_0x1704_Type_BoardIdGettingMethod
:SKIP_MULTI_BOARD_SUPPORT


:END
EXIT /B 0
