/** @file

;******************************************************************************
;* Copyright (c) 2023, Insyde Software Corp. All Rights Reserved.
;*
;* You may not reproduce, distribute, publish, display, perform, modify, adapt,
;* transmit, broadcast, present, recite, release, license or otherwise exploit
;* any part of this publication in any form, by any means, without the prior
;* written permission of Insyde Software Corporation.
;*
;******************************************************************************
*/
#include "H2ODisplayEngineLocalMetro.h"

#if FixedPcdGet32(PcdH2OLmdeMultiLayout) == 1
CHAR16 *mDialogPanelChilds = L""
  L"<VerticalLayout name='DialogPanel' background-color='0xFF000000'/>";

CHAR16 *mScreenPanelChilds = L""
  L"<Texture float='true' name='background' background-color='0x0' background-image-style='stretch' background-color='0x0' height='match_parent' width='match_parent'/>"
  L"<Texture float='true' name='ContextBkg' background-color='0x0' background-image-style='stretch' background-image='@Bkg'/>"
  L"<H2OOwnerDrawPanel name='H2OOwnerDrawPanel' RefreshInterval='400'/>"
  L"<H2OSetupMenuPanel border-color='0x70FFFFFF' name='H2OSetupMenuPanel' padding='2,0,2,0' box-sizing='border-box'/>"
  L"<H2OFormTitlePanel border-color='0x70FFFFFF' name='H2OFormTitlePanel' background-color='0x0'/>"
  L"<H2OSetupPagePanel name='H2OSetupPagePanel' background-color='0x0'/>"
  L"<H2OHelpTextPanel  name='H2OHelpTextPanel' background-color='0x0'/>"
  L"<H2OHotkeyPanel border-color='0x70FFFFFF' name='H2OHotkeyPanel' padding='15,10,0,10' box-sizing='border-box' background-color='0x0'/>"
  L"<Texture name='overlay' float='true' visibility='false' height='match_parent' width='match_parent' background-color='0x80C8C8C8'/>"
  L"";

CHAR16 *mOwnerDrawPanelChilds = L""
  L"<Control>"
    L"<Texture name='OwnerDrawBackground' float='true' height='match_parent' width='match_parent' background-image='@OwnerDrawBkg' background-color='0xFF333333' background-image-style='stretch'/>"
    L"<HorizontalLayout width='match_parent' padding='10,20,10,20' name='OwnerDrawList'>"
      L"<VerticalLayout width='190'>"
        L"<Control width='180' height='50' background-image='@OwnerDrawInsyde' background-color='0x0'/>"
        L"<Control width='180' height='2'/>"
        L"<Label textcolor='0xFF000000' font-size='9' background-color='0x0' text-align='singleline' text-overflow='ellipsis' name='OwnerDrawSystemInfoProcessor'/>"
        L"<Label textcolor='0xFF000000' font-size='9' background-color='0x0' text-align='singleline' text-overflow='ellipsis' name='OwnerDrawSystemInfoMemFrequency'/>"
        L"<Label textcolor='0xFF000000' font-size='9' background-color='0x0' text-align='singleline' text-overflow='ellipsis' name='OwnerDrawSystemInfoMemSize'/>"
      L"</VerticalLayout>"
      L"<Control/>"
      L"<HorizontalLayout width='530'>"
        L"<VerticalLayout width='160'>"
          L"<HorizontalLayout width='158' height='38'>"
            L"<Control width='36' height='36' background-image='@OwnerDrawTime' background-color='0x0'/>"
            L"<Control/>"
            L"<VerticalLayout width='120'>"
              L"<Label textcolor='0xFFC69842' font-size='15' background-color='0x0' name='OwnerDrawDateValue'/>"
              L"<Label textcolor='0xFFC69842' font-size='15' background-color='0x0' name='OwnerDrawWeekdayValue'/>"
            L"</VerticalLayout>"
          L"</HorizontalLayout>"
          L"<Label textcolor='0xFF000000' font-size='38' text-align='center' background-color='0x0' name='OwnerDrawTimeValue'/>"
        L"</VerticalLayout>"
        L"<Control/>"
        L"<Control width='22' height='80' background-image='@OwnerDrawSeparator' background-color='0x0'/>"
        L"<Control/>"
        L"<VerticalLayout width='160'>"
          L"<HorizontalLayout width='158' height='38'>"
            L"<Control width='36' height='36' background-image='@OwnerDrawTemperature' background-color='0x0'/>"
            L"<Control/>"
            L"<VerticalLayout width='120'>"
              L"<Label textcolor='0xFFC69842' font-size='15' background-color='0x0' name='OwnerDrawMainboardName'/>"
              L"<Label textcolor='0xFFC69842' font-size='15' background-color='0x0' name='OwnerDrawSystemName'/>"
            L"</VerticalLayout>"
          L"</HorizontalLayout>"
          L"<Label textcolor='0xFF000000' font-size='38' text-align='center' background-color='0x0' name='OwnerDrawSystemTemperature'/>"
        L"</VerticalLayout>"
        L"<Control width='15'/>"
        L"<Control width='22' height='80' background-image='@OwnerDrawSeparator' background-color='0x0'/>"
        L"<Control width='15'/>"
        L"<VerticalLayout width='160'>"
          L"<HorizontalLayout width='158' height='38'>"
            L"<Control width='36' height='36' background-image='@OwnerDrawTemperature' background-color='0x0'/>"
            L"<Control/>"
            L"<VerticalLayout width='120'>"
              L"<Label textcolor='0xFFC69842' font-size='15' background-color='0x0' name='OwnerDrawCpuName'/>"
              L"<Label textcolor='0xFFC69842' font-size='15' background-color='0x0' name='OwnerDrawTemperatureName'/>"
            L"</VerticalLayout>"
          L"</HorizontalLayout>"
          L"<Label textcolor='0xFF000000' font-size='38' text-align='center' background-color='0x0' name='OwnerDrawCpuTemperature'/>"
        L"</VerticalLayout>"
      L"</HorizontalLayout>"
      L"<Control/>"
      L"<Control width='100' height='84' background-image='@OwnerDrawInsydeH2O' background-color='0x0'/>"
    L"</HorizontalLayout>"
  L"</Control>";

CHAR16 *mFormTitlePanelChilds = L""
  L"<HorizontalLayout background-color='0x0' height='match_parent'>"
    L"<HorizontalLayout width='match_parent' float='true' height='match_parent'>"
      L"<Texture background-color='0x0'/>"
    L"</HorizontalLayout>"
    L"<VerticalLayout padding='13,0,15,30' width='37' height='match_parent'>"
      L"<Control/>"
      L"<Texture background-color='0x0' name='TitleImage' height='37' background-image-style='stretch'/>"
      L"<Control/>"
    L"</VerticalLayout>"
    L"<VerticalLayout padding='0,0,0,8' height='match_parent'>"
      L"<Control/>"
      L"<Label background-color='0x0' textcolor='0xFFFFFFFF' font-size='30' name='TitleName' height='wrap_content' width='match_parent'/>"
      L"<Control/>"
    L"</VerticalLayout>"
  L"</HorizontalLayout>";

CHAR16 *mHelpTextPanelChilds = L""
  L"<VerticalLayout width='match_parent' float='true' height='match_parent' visibility='false'>"
    L"<Control />"
    L"<Texture width='300' height='300' name='HelpBkgImage' background-image-style='stretch|gray' visibility='false' background-color='0x0'/>"
  L"</VerticalLayout>"
  L"<VerticalLayout padding='40,30,40,30' width='match_parent' float='true' name='HelpMenu' height='match_parent'>"
    L"<HorizontalLayout padding='0,0,8,0' min-height='50' height='wrap_content'>"
      L"<Label background-color='0x0' textcolor='0xFFFFFFFF' font-size='20' name='HelpTitle' height='wrap_content'/>"
      L"<Control padding='0,25,0,25' height='50' width='50'>"
        L"<Texture width='50' height='50' name='HelpImage' background-image-style='stretch'/>"
      L"</Control>"
    L"</HorizontalLayout>"
    L"<Control height='10'/>"
    L"<Texture width='match_parent' height='1' background-image='@HtSepartor' background-image-style='stretch' background-color='0x0'/>"
    L"<Control height='10'/>"
    L"<ScrollView taborder='20' name='HelpTextScrollView' vscrollbar='true' scale9grid='1,13,1,13'>"
      L"<Label background-color='0x0' width='match_parent' height='wrap_content' textcolor='0xFFFFFFFF' font-size='19' name='HelpText'/>"
    L"</ScrollView>"
  L"</VerticalLayout>";

CHAR16 *mHotkeyItemChilds = L""
  L"<VerticalLayout padding='2,2,2,2' name='ItemLayout' height='match_parent' background-color='0x0'>"
    L"<HorizontalLayout name='MarkLayout' height='50'>"
      L"<Label background-color='0x0' name='MarkLayoutLeft'/>"
      L"<HorizontalLayout name='HotkeyLayout' height='48'/>"
      L"<Label name='MarkLayoutRight'/>"
    L"</HorizontalLayout>"
    L"<Label background-color='0x0' name='HelpText' text-align='center' height='15' padding='4,0,4,0' font-size='15' textcolor='0xFFFFFFFF'/>"
    L"<Label background-color='0x0' name='HelpTextBottom'/>"
  L"</VerticalLayout>";

CHAR16 *mFrontPageItemChilds = L""
  L"<Texture float='true' name='HotBkg' background-image='@SpSelectedBkg' background-image-style='stretch' background-color='0x0' visibility='false'/>"
  L"<VerticalLayout padding='15,15,15,15' name='ItemLayout'>"
    L"<HorizontalLayout name='ImageLayout'>"
      L"<Label name='ImageLayoutLeft'/>"
      L"<Texture name='FrontPageImage' background-image-style='stretch|light'/>"
    L"</HorizontalLayout>"
    L"<Label background-color='0x0' name='menu_prompt' text-align='center' height='15' padding='8,0,0,0' font-size='15' textcolor='0xFFFFFFFF'/>"
    L"<Label height='7'/>"
    L"<Texture background-color='0xFFF4F4F4' name='separator' height='1'/>"
    L"<Label height='8'/>"
    L"<Label background-color='0x0' text-align='center' textcolor='0xFFFFFFFF' font-size='13' name='menu_help' height='26'/>"
  L"</VerticalLayout>";

CHAR16 *mSetupMenuItemChilds = L""
  L"<VerticalLayout>"
    L"<Texture float='true' background-color='0x0' name='bkimage' background-image-style='stretch' height='match_parent' width='match_parent' visibility='false'/>"
    L"<Texture float='true' background-color='0x0' name='HotBkg' background-image-style='stretch' height='match_parent' width='match_parent' visibility='false' background-image='@MenuBackgroundHot'/>"
    L"<VerticalLayout padding='30, 30, 30, 30' width='match_parent' float='true' height='match_parent'>"
      L"<Texture background-color='0x0' name='image' background-image-style='stretch|light'/>"
    L"</VerticalLayout>"
    L"<VerticalLayout/>"
    L"<Label background-color='0x0' name='text' text-align='center' height='21' padding='4,0,8,0' font-size='20' textcolor='0xFFFFFFFF'/>"
  L"</VerticalLayout>";

CHAR16 *mSubtitleChilds = L""
  L"<Texture float='true' name='OptionBkg' background-color='0x0' background-image-style='stretch' visibility='false'/>"
  L"<Texture float='true' name='HotBkg' background-image='@SpSelectedBkg' background-image-style='stretch' background-color='0x0' visibility='false'/>"
  L"<VerticalLayout min-height='35' width='match_parent' height='wrap_content'>"
    L"<Label name='OptionPrompt' width='match_parent' height='wrap_content' background-color='0x0' padding='0,0,0,20' font-size='20' textcolor='0xFFFFFFFF' text-overflow='ellipsis'/>"
    L"<Control height='10' width='match_parent'/>"
  L"</VerticalLayout>";

CHAR16 *mH2OCheckBoxOpChilds = L""
  L"<Texture float='true' name='OptionBkg' background-color='0x0' background-image-style='stretch' visibility='false'/>"
  L"<Texture float='true' name='HotBkg' background-image='@SpSelectedBkg' background-image-style='stretch' background-color='0x0' visibility='false'/>"
  L"<HorizontalLayout>"
    L"<Control width='60' />"
    L"<Label background-color='0x0' text-align='singleline' textcolor='0xFFFFFFFF' font-size='21' name='OptionPrompt' text-overflow='ellipsis'/>"
    L"<HorizontalLayout width='120' height='35'>"
      L"<Switch switchcolor='@menucolor' name='CheckBox'/>"
    L"</HorizontalLayout>"
    L"<Label width='30' />"
  L"</HorizontalLayout>";

CHAR16 *mStatementChilds = L""
  L"<Texture float='true' name='OptionBkg' background-color='0x0' background-image-style='stretch' visibility='false'/>"
  L"<Texture float='true' name='HotBkg' background-image='@SpSelectedBkg' background-image-style='stretch' background-color='0x0' visibility='false'/>"
  L"<HorizontalLayout>"
    L"<Control width='25' name='RefImagePadding' padding='10,17,10,18'>"
      L"<Texture width='15' name='RefImage' background-image-style='stretch' background-image='@SpTriangle' visibility='false'/>"
    L"</Control>"
    L"<HorizontalLayout name='OptionLayout'>"
      L"<Label background-color='0x0' text-align='singleline|left' textcolor='0xFFFFFFFF' font-size='21' name='OptionPrompt' text-overflow='ellipsis'/>"
      L"<Label background-color='0x0' text-align='singleline' name='OptionSparator' width='10'/>"
      L"<Label background-color='0x0' text-align='singleline|right' width='wrap_content' max-width='160' textcolor='0xFFFFFFFF' font-size='21' name='OptionValue' text-overflow='ellipsis'/>"
      L"<Label background-color='0x0' name='OptionEnd' text='>' text-align='singleline|right' text-align='center' width='20' font-size='21' textcolor='0xFFFFFFFF'/>"
      L"<Label text-align='singleline' name='EndSparator' width='20'/>"
    L"</HorizontalLayout>"
  L"</HorizontalLayout>";

CHAR16 *mH2OTextOpChilds = L""
  L"<Texture float='true' name='OptionBkg' background-color='0x0' background-image-style='stretch' visibility='false'/>"
  L"<Texture float='true' name='OptionPromptBackground' background-color='0x0' background-image-style='stretch' visibility='false'/>"
  L"<Texture float='true' name='OptionValueBackground' background-color='0x0' background-image-style='stretch' visibility='false'/>"
  L"<Texture float='true' name='HotBkg' background-image='@SpSelectedBkg' background-image-style='stretch' background-color='0x0' visibility='false'/>"
  L"<HorizontalLayout child-padding='2' width='match_parent' min-height='35' height='wrap_content' padding='0,0,0,60'>"
    L"<Label background-color='0x0' name='OptionPrompt' min-height='35' height='wrap_content' padding='7,0,7,0' width='50%' font-size='20' textcolor='0xFFFFFFFF'/>"
    L"<Label background-color='0x0' name='OptionValue' text-align='center' min-height='35' height='wrap_content' padding='7,0,7,0' width='50%' font-size='20' textcolor='0xFFFFFFFF'/>"
    L"<Texture float='true' background-color='@menucolor' left='30' top='11' width='8' height='8' position='absolute' />"
  L"</HorizontalLayout>";

CHAR16 *mCommonDialogChilds = L""
  L"<VerticalLayout padding='40,30,40,30' name='PopUpDialog' background-image='@DialogBkg' background-image-style='stretch'>"
    L"<VerticalLayout name='TitleLayout'>"
      L"<Label padding='0,0,30,0' textcolor='0xFFFFFFFF' font-size='29' name='DialogTitle' height='80'/>"
      L"<Label padding='0,0,45,0' textcolor='0xFFA8D2DF' font-size='19' name='DialogText'/>"
    L"</VerticalLayout>"
    L"<Control background-image='@DialogSeparator' background-color='0x0' name='DialogSeparator' height='2' background-image-style='stretch'/>"
    L"<Control height='8'/>"
    L"<VerticalLayout>"
      L"<HorizontalLayout padding='10,0,0,0' visibility='false' name='DialogPasswordInput' height='41'>"
        L"<Label name='ConfirmNewPasswordLabel' height='41' width='119' font-size='16' background-color='0xFFF2F2F2' textcolor='0xFF4D4D4D'/>"
        L"<VerticalLayout padding='6,8,6,8' background-color='0xFFF2F2F2' height='29'>"
          L"<Control padding='1,1,1,1' background-color='0xFF999999' height='27'>"
            L"<UiEdit name='ConfirmPasswordInput' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' height='20' padding='7,3,0,3' background-color='0xFFF2F2F2' password='true'/>"
          L"</Control>"
        L"</VerticalLayout>"
      L"</HorizontalLayout>"
      L"<HorizontalLayout padding='10,0,0,0' child-padding='2' name='DialogButtonList'/>"
    L"</VerticalLayout>"
  L"</VerticalLayout>";

CHAR16 *mCommonDialogWithHelpChilds = L""
  L"<VerticalLayout padding='40,30,40,30' width='match_parent' float='true' name='HelpMenu' height='match_parent' name='Dialog' background-image='@DialogBkg' background-image-style='stretch'>"
    L"<VerticalLayout name='TitleLayout'>"
      L"<HorizontalLayout padding='0,0,8,0' min-height='50' height='wrap_content'>"
        L"<Label textcolor='0xFFFFFFFF' font-size='29' name='DialogTitle' height='wrap_content' width='67%'/>"
        L"<Control padding='0,25,0,25' height='50' width='33%'>"
          L"<Texture width='50' height='50' name='DialogImage' background-image-style='stretch|light'/>"
        L"</Control>"
      L"</HorizontalLayout>"
      L"<ScrollView taborder='20' name='DialogTextScrollView' vscrollbar='true' scale9grid='1,13,1,13'>"
        L"<Label name='DialogText' height='wrap_content' width='match_parent' font-size='19' textcolor='0xFFA8D2DF'/>"
      L"</ScrollView>"
    L"</VerticalLayout>"
    L"<VerticalLayout>"
      L"<Control background-image='@DialogSeparator' background-color='0x0' height='2' background-image-style='stretch'/>"
      L"<Control height='5'/>"
      L"<Control name='Content'/>"
    L"</VerticalLayout>"
  L"</VerticalLayout>";

CHAR16 *mDialogWithoutSendFormChilds = L""
  L"<VerticalLayout name='DialogWithoutSendForm'>"
    L"<Control/>"
    L"<Control name='parent' height='wrap_content' background-image='@DialogBkg' background-image-style='stretch'>"
      L"<VerticalLayout padding='20,30,20,30' height='wrap_content' background-image='@DialogBkg' background-image-style='stretch'>"
        L"<VerticalLayout name='TitleLayout' height='wrap_content'>"
          L"<Label name='DialogTitle' text-align='center' height='40' visibility='false' font-size='19' textcolor='0xFFFFFFFF'/>"
          L"<Label width='match_parent' textcolor='0xFFFFFFFF' font-size='19' name='DialogText' height='wrap_content'/>"
          L"<Control height='15'/>"
          L"<Control height='10' background-image='@DialogSeparator' background-color='0x0' background-image-style='center'/>"
          L"<Control height='15'/>"
        L"</VerticalLayout>"
        L"<VerticalLayout padding='0,0,10,0' visibility='false' min-height='51' name='DialogPasswordInput' height='wrap_content'>"
          L"<Label name='ConfirmNewPasswordLabel' height='wrap_content' padding='0,0,2,0' width='match_parent' font-size='18' textcolor='0xFFFFFFFF'/>"
          L"<Control padding='2,2,2,2' background-color='0xFFCCCCCC' height='wrap_content'>"
            L"<UiEdit name='ConfirmPasswordInput' focusbkcolor='0xFFFFFFFF' tabstop='true' height='20' padding='7,3,0,3' taborder='1' background-color='@menulightcolor' password='true'/>"
          L"</Control>"
        L"</VerticalLayout>"
        L"<HorizontalLayout padding='1,0,0,0' child-padding='2' visibility='false' name='DialogButtonList' height='31'/>"
      L"</VerticalLayout>"
    L"</Control>"
    L"<Control/>"
  L"</VerticalLayout>";

CHAR16 *mHelpDialogChilds = L""
  L"<VerticalLayout padding='20,20,0,20' name='HelpDialog' background-image='@DialogBkg' background-image-style='stretch'>"
    L"<VerticalLayout padding='0,0,20,0' vscrollbar='false'>"
      L"<Label textcolor='0xFFFFFFFF' font-size='19' name='DialogText'/>"
    L"</VerticalLayout>"
    L"<HorizontalLayout height='50'>"
      L"<Control/>"
      L"<Button name='DialogButton' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' text='OK' text-align='singleline|center' height='30' width='55' font-size='27' background-color='0xFFCCCCCC' textcolor='0xFFFFFFFF' background-image='@DialogBkg' background-image-style='stretch'/>"
      L"<Control/>"
    L"</HorizontalLayout>"
  L"</VerticalLayout>";

CHAR16 *mConfirmPageDialogChilds = L""
  L"<VerticalLayout padding='20,20,0,20' name='ConfirmPageDialog' background-image='@DialogBkg' background-image-style='stretch'>"
    L"<VerticalLayout name='TitleLayout' height='70'>"
      L"<Label padding='0,0,30,0' textcolor='0xFFFFFFFF' font-size='29' name='DialogTitle'/>"
    L"</VerticalLayout>"
    L"<VerticalLayout padding='0,0,20,0' vscrollbar='false'>"
      L"<Label textcolor='0xFFFFFFFF' font-size='19' name='ConfirmPageDialogText'/>"
    L"</VerticalLayout>"
    L"<HorizontalLayout height='30'>"
      L"<Label text-align='center' textcolor='0xFFFFFFFF' font-size='20' name='ConfirmPageConfirmString'/>"
    L"</HorizontalLayout>"
    L"<HorizontalLayout height='50'>"
      L"<HorizontalLayout padding='10,0,0,0' child-padding='2' name='DialogButtonList'/>"
    L"</HorizontalLayout>"
  L"</VerticalLayout>";

CHAR16 *mOneOfDialogChilds = L""
  L"<ListView name='OneOfList' vscrollbar='true' tabstop='true' padding='15,0,0,0' child-padding='2' taborder='1'/>";

CHAR16 *mOneOfDialogWithoutSendFormChilds = L""
  L"<VerticalLayout name='OneOfDialog'>"
    L"<Control/>"
    L"<HorizontalLayout height='wrap_content'>"
      L"<Control/>"
      L"<Control width='wrap_content' height='wrap_content'>"
        L"<VerticalLayout name='Content' width='wrap_content' height='wrap_content' padding='20,30,20,30' child-padding='15' background-image='@DialogBkg' background-image-style='stretch'>"
          L"<Label name='DialogTitle' text-align='center' height='wrap_content' width='match_parent' font-size='19' textcolor='0xFFFFFFFF'/>"
          L"<Control height='10' background-image='@DialogSeparator' background-color='0x0' background-image-style='center'/>"
          L"<ListView name='OneOfList' vscrollbar='true' width='wrap_content' height='wrap_content' padding='0,0,0,0' child-padding='2'/>"
        L"</VerticalLayout>"
      L"</Control>"
      L"<Control/>"
    L"</HorizontalLayout>"
    L"<Control/>"
  L"</VerticalLayout>";

CHAR16 *mOneOfOptionChilds = L""
  L"<HorizontalLayout height='40'>"
    L"<Label name='Option' padding='0,20,0,20' text-align='singleline|center' height='40' font-size='19' background-color='0x0' textcolor='0xFFFFFFFF' text-overflow='ellipsis'/>"
    L"<HorizontalLayout float='true' padding='12,0,0,0' >"
      L"<Control/>"
      L"<Texture name='OptionSelectedIcon' width='21' height='match_parent'  visibility='false' background-image='@DialogSelectedIcon' background-color='0x0'/>"
      L"<Control width='20'/>"
    L"</HorizontalLayout>"
  L"</HorizontalLayout>";

CHAR16 *mOneOfOptionChildsWithoutSendForm = L""
  L"<VerticalLayout height='40'>"
    L"<Label name='Option' text-align='singleline' height='40' padding='0,10,0,10' width='match_parent' font-size='19' background-color='0x0' textcolor='0xFFFFFFFF' text-overflow='ellipsis'/>"
  L"</VerticalLayout>";

CHAR16 *mNumericDialogChilds = L""
  L"<VerticalLayout>"
    L"<VerticalLayout background-color='0xFFF2F2F2' height='49'>"
      L"<Label name='NumericLabel' text='input number:' height='18' padding='2,0,0,2' font-size='16' textcolor='0xFF4D4D4D'/>"
      L"<VerticalLayout padding='2,2,0,2' height='26' >"
        L"<Control padding='2,1,1,1' background-color='0xFF999999' >"
          L"<HorizontalLayout>"
            L"<UiEdit name='InputNumericText' padding='0,0,0,19' font-size='19' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' tabstop='true' height='27' taborder='1' background-color='0xFFF2F2F2' valuetype='dec'/>"
            L"<Label name='Prefix' text=''  font-size='19' height='27' width='wrap_content' background-color='0x00000000' float='true' />"
          L"</HorizontalLayout>"
        L"</Control>"
      L"</VerticalLayout>"
    L"</VerticalLayout>"
    L"<Control height='2'/>"
    L"<Control height='10'/>"
    L"<HorizontalLayout padding='0,0,30,0' child-padding='2' height='25'>"
      L"<Control/>"
      L"<Button name='Ok' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' text='Enter' text-align='singleline|center' height='30' width='55' taborder='2' font-size='19' background-color='0x0' textcolor='0xFFFFFFFF'/>"
      L"<Button name='Cancel' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' text='Cancel' text-align='singleline|center' height='30' width='55' taborder='3' font-size='19' background-color='0x0' textcolor='0xFFFFFFFF'/>"
    L"</HorizontalLayout>"
  L"</VerticalLayout>";

CHAR16 *mNumericDialogWithoutSendFormChilds = L""
  L"<Control name='NumericDialogWithoutSendForm' background-image='@DialogBkg' background-image-style='stretch'>"
    L"<VerticalLayout padding='20,30,20,30' background-image='@DialogBkg' background-image-style='stretch'>"
      L"<VerticalLayout name='TitleLayout'>"
        L"<Label text-align='center' textcolor='0xFFFFFFFF' font-size='19' name='DialogTitle' height='40'/>"
        L"<Control height='15'/>"
        L"<Control height='10' background-image='@DialogSeparator' background-color='0x0' background-image-style='center'/>"
        L"<Control height='15'/>"
      L"</VerticalLayout>"
      L"<HorizontalLayout padding='0,0,10,0' name='DialogPasswordInput' height='41'>"
        L"<VerticalLayout padding='6,8,6,8' background-color='0xFFF2F2F2' height='29'>"
          L"<Control padding='1,1,1,1' background-color='0xFF999999' height='27'>"
            L"<HorizontalLayout>"
              L"<UiEdit font-size='19' padding='7,3,0,22' name='InputNumericText' background-color='0xFFF2F2F2' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040'  height='20' tabstop='true' taborder='1'  valuetype='dec'/>"
              L"<Label name='Prefix' text=''  font-size='19' height='27' width='wrap_content' background-color='0x00000000' float='true' />"
            L"</HorizontalLayout>"
          L"</Control>"
        L"</VerticalLayout>"
      L"</HorizontalLayout>"
      L"<HorizontalLayout child-padding='2' visibility='false' name='DialogButtonList' height='30'/>"
    L"</VerticalLayout>"
  L"</Control>";

CHAR16 *mPasswordDialogChilds = L""
  L"<VerticalLayout>"
    L"<HorizontalLayout background-color='0xFFF2F2F2' name='OldPassword' height='41'>"
      L"<Label width='119' textcolor='0xFF4D4D4D' font-size='16' name='OldPasswordLabel' height='41'/>"
      L"<VerticalLayout padding='6,8,6,0' height='29'>"
        L"<Control/>"
        L"<Control padding='1,1,1,1' background-color='0xFF999999' height='27'>"
          L"<UiEdit name='OldPasswordText' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' tabstop='true' height='20' padding='7,3,0,3' taborder='1' background-color='0xFFF2F2F2' password='true' text-align='singleline'/>"
        L"</Control>"
        L"<Control/>"
      L"</VerticalLayout>"
    L"</HorizontalLayout>"
    L"<Control name='OldPasswordSeperator' height='2'/>"
    L"<HorizontalLayout background-color='0xFFF2F2F2' name='NewPassword' height='41'>"
      L"<Label width='119' textcolor='0xFF4D4D4D' font-size='16' name='NewPasswordLabel' height='41'/>"
      L"<VerticalLayout padding='6,8,6,0' height='29'>"
        L"<Control/>"
        L"<Control padding='1,1,1,1' background-color='0xFF999999' height='27'>"
          L"<UiEdit name='NewPasswordText' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' tabstop='true' height='20' padding='7,3,0,3' taborder='2' background-color='0xFFF2F2F2' password='true' text-align='singleline'/>"
        L"</Control>"
        L"<Control/>"
      L"</VerticalLayout>"
    L"</HorizontalLayout>"
    L"<Control name='NewPasswordSeperator' height='2'/>"
    L"<HorizontalLayout background-color='0xFFF2F2F2' name='ConfirmNewPassword' height='41'>"
      L"<Label width='119' textcolor='0xFF4D4D4D' font-size='16' name='ConfirmNewPasswordLabel' height='41'/>"
      L"<VerticalLayout padding='6,8,6,0' height='29'>"
        L"<Control/>"
        L"<Control padding='1,1,1,1' background-color='0xFF999999' height='27'>"
          L"<UiEdit name='ConfirmNewPasswordText' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' tabstop='true' height='20' padding='7,3,0,3' taborder='3' background-color='0xFFF2F2F2' password='true' text-align='singleline'/>"
        L"</Control>"
        L"<Control/>"
      L"</VerticalLayout>"
    L"</HorizontalLayout>"
    L"<Control name='ConfirmNewPasswordSeperator' height='2'/>"
    L"<Control height='10'/>"
    L"<HorizontalLayout child-padding='2' height='30'>"
      L"<Label textcolor='0xFFFFFFFF' font-size='19' name='PasswordStrLen' text=''/>"
      L"<Button name='Ok' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' text='Enter' text-align='singleline|center' height='30' width='55' taborder='4' font-size='19' background-color='0x0' textcolor='0xFFFFFFFF' tabstop='true'/>"
      L"<Button name='Cancel' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' text='Cancel' text-align='singleline|center' height='30' width='55' taborder='5' font-size='19' background-color='0x0' textcolor='0xFFFFFFFF' tabstop='true'/>"
    L"</HorizontalLayout>"
  L"</VerticalLayout>";

CHAR16 *mConfirmPasswordDialogChilds = L""
  L"<VerticalLayout name='DialogWithoutSendForm'>"
    L"<Control/>"
    L"<Control name='parent' height='wrap_content'>"
      L"<VerticalLayout padding='20,30,20,30' height='wrap_content' background-image='@DialogBkg' background-image-style='stretch'>"
        L"<VerticalLayout name='TitleLayout' height='wrap_content'>"
          L"<Label name='DialogTitle' text-align='center' height='40' visibility='false' font-size='19' textcolor='0xFFFFFFFF'/>"
          L"<Label width='match_parent' textcolor='0xFFFFFFFF' font-size='19' name='DialogText' height='wrap_content'/>"
          L"<Control height='15'/>"
          L"<Control height='10' background-image='@DialogSeparator' background-color='0x0' background-image-style='center'/>"
          L"<Control height='15'/>"
        L"</VerticalLayout>"
        L"<VerticalLayout padding='0,0,10,0' min-height='51' name='DialogPasswordInput' height='wrap_content'>"
          L"<Label name='ConfirmNewPasswordLabel' height='wrap_content' padding='0,0,2,0' width='match_parent' font-size='18' textcolor='0xFFFFFFFF'/>"
          L"<Control padding='2,2,2,2' background-color='0xFFCCCCCC' height='wrap_content'>"
            L"<UiEdit name='ConfirmPasswordInput' focusbkcolor='0xFFFFFFFF' tabstop='true' height='20' padding='7,3,0,3' taborder='1' background-color='@menulightcolor' password='true' text-align='singleline'/>"
          L"</Control>"
          L"<Label textcolor='0xFFFFFFFF' font-size='19' name='PasswordStrLen' text='' height='wrap_content'/>"
        L"</VerticalLayout>"
      L"</VerticalLayout>"
    L"</Control>"
    L"<Control/>"
  L"</VerticalLayout>";

CHAR16 *mStringDialogChilds = L""
  L"<VerticalLayout>"
    L"<HorizontalLayout width='300' background-color='0xFFF2F2F2' height='wrap_content' >"
      L"<Label name='StringLabel' text='input string:' height='29' padding='12,0,0,0' width='119' font-size='16' textcolor='0xFF4D4D4D'/>"
      L"<VerticalLayout name='InputStringArea' padding='6,8,6,0' width='173' height='wrap_content' >"
        L"<Control/>"
        L"<Control name='InputStringBox' padding='1,1,1,1' width='171' background-color='0xFF999999' height='wrap_content'>"
          L"<UiEdit name='InputStringText' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' tabstop='true' font-size='19' height='wrap_content' width='171' taborder='1' background-color='0xFFF2F2F2'/>"
        L"</Control>"
        L"<Control/>"
      L"</VerticalLayout>"
    L"</HorizontalLayout>"
    L"<Control height='2'/>"
    L"<Control height='10'/>"
    L"<HorizontalLayout padding='0,0,30,0' child-padding='2' width='300' height='25'>"
      L"<Control/>"
      L"<Button name='Ok' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' text='Enter' text-align='singleline|center' height='30' width='55' taborder='2' font-size='19' background-color='0x0' textcolor='0xFFFFFFFF' tabstop='true'/>"
      L"<Button name='Cancel' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' text='Cancel' text-align='singleline|center' height='30' width='55' taborder='3' font-size='19' background-color='0x0' textcolor='0xFFFFFFFF' tabstop='true'/>"
    L"</HorizontalLayout>"
  L"</VerticalLayout>";

CHAR16 *mOrderedListDialogChilds = L""
  L"<VerticalLayout name='OrderedListDialog'>"
    L"<ListView moveitemsupport='true' name='OrderedListList' vscrollbar='true' tabstop='true' child-padding='2' taborder='1'/>"
    L"<Control height='12'/>"
    L"<HorizontalLayout padding='0,0,30,0' child-padding='2' height='25'>"
      L"<Control/>"
      L"<Button name='Ok' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' text='YES' text-align='singleline|center' height='30' width='55' taborder='2' font-size='19' background-color='0xFFCCCCCC' textcolor='0xFFFFFFFF' tabstop='true'/>"
      L"<Button name='Cancel' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' text='NO' text-align='singleline|center' height='30' width='55' taborder='3' font-size='19' background-color='0xFFCCCCCC' textcolor='0xFFFFFFFF' tabstop='true'/>"
    L"</HorizontalLayout>"
  L"</VerticalLayout>";

CHAR16 *mOrderedListOptionChilds = L""
  L"<HorizontalLayout width='-1' background-color='0xFFE6E6E6' name='Option' height='40'>"
    L"<Texture width='40' name='Icon' height='40'/>"
    L"<Label padding='7,0,7,0' text-align='center' background-color='0x0' textcolor='0xFFFFFFFF' font-size='14' name='Words'/>"
    L"<Texture height='40' width='40' background-image='@DialogSortIcon' name='SortIcon' background-image-style='stretch|gray'/>"
  L"</HorizontalLayout>";

CHAR16 *mTimeDialogChilds = L""
  L"<VerticalLayout>"
    L"<TimeItem name='Time' height='156'/>"
    L"<Control height='12'/>"
    L"<HorizontalLayout child-padding='2' height='30'>"
      L"<Control/>"
      L"<Button name='ok' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' text='Enter' text-align='singleline|center' height='30' width='55' taborder='2' font-size='19' background-color='0x0' textcolor='0xFFFFFFFF'/>"
      L"<Button name='cancel' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' text='Close' text-align='singleline|center' height='30' width='55' taborder='3' font-size='19' background-color='0x0' textcolor='0xFFFFFFFF'/>"
    L"</HorizontalLayout>"
  L"</VerticalLayout>";

CHAR16 *mDateDialogChilds = L""
  L"<VerticalLayout>"
    L"<DateItem taborder='1' name='Date' height='156'/>"
    L"<Control height='12'/>"
    L"<HorizontalLayout child-padding='2' height='30'>"
      L"<Control/>"
      L"<Button name='ok' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' text='Enter' text-align='singleline|center' height='30' width='55' taborder='2' font-size='19' background-color='0x0' textcolor='0xFFFFFFFF'/>"
      L"<Button name='cancel' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' text='Close' text-align='singleline|center' height='30' width='55' taborder='3' font-size='19' background-color='0x0' textcolor='0xFFFFFFFF'/>"
    L"</HorizontalLayout>"
  L"</VerticalLayout>";

CHAR16 *mScrollbarChilds = L""
  L"<HorizontalLayout float='true' height='match_parent' background-color='0x0'>"
    L"<HorizontalLayout/>"
    L"<Texture name='track' width='1' background-image='@ScrollbarBackground' background-image-style='stretch'/>"
    L"<HorizontalLayout/>"
  L"</HorizontalLayout>"
  L"<HorizontalLayout float='true' height='match_parent' name='thumbparent'>"
    L"<HorizontalLayout/>"
    L"<Texture name='thumb' width='10' background-image='@ScrollbarThumb' background-image-style='stretch' visibility='false'/>"
    L"<HorizontalLayout/>"
  L"</HorizontalLayout>"
  L"";

CHAR16 *mSwitchChilds = L""
  L"<Label float='true' background-image='@CheckBoxBorder' name='CheckboxBorder' scale9grid='14,1,14,1'/>"
  L"<Label float='true' padding='3,5,4,5' background-image='@CheckBoxBkg' name='CheckboxBkg' scale9grid='14,1,14,1'/>"
  L"<Label textcolor='0xFF404040' float='true' font-size='17' name='CheckboxText'/>"
  L"<HorizontalLayout float='true' name='CheckboxButton'>"
    L"<Label background-image='@CheckBoxButton' scale9grid='11,1,11,1'/>"
  L"</HorizontalLayout>";

CHAR16 *mDateRollerChilds = L""
  L"<DateItem name='Date' width='match_parent' height='match_parent' tabstop='true'/>"
  ;

CHAR16 *mNumericInputChilds = L""
  L"<VerticalLayout>"
    L"<VerticalLayout width='300' background-color='0xFFF2F2F2' height='49'>"
      L"<Label name='NumericLabel' text='input number:' height='20' padding='2,0,0,2' font-size='16' textcolor='0xFF4D4D4D'/>"
      L"<VerticalLayout padding='2,2,0,2' height='28' >"
        L"<Control padding='2,1,1,1' background-color='0xFF999999' >"
          L"<HorizontalLayout>"
            L"<UiEdit name='InputText' padding='0,0,0,19' font-size='19' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' tabstop='true' height='27' taborder='1' background-color='0xFFF2F2F2'/>"
            L"<Label name='Prefix' text=''  font-size='19' height='27' width='wrap_content' background-color='0x00000000' float='true' />"
          L"</HorizontalLayout>"
        L"</Control>"
      L"</VerticalLayout>"
    L"</VerticalLayout>";

CHAR16 *mOptionListChilds = L""
  L"<ListView name='OptionList' width='match_parent' height='match_parent' child-padding='2' vscrollbar='true' tabstop='true' taborder='1'/>";

CHAR16 *mOptionChilds = L""
  L"<HorizontalLayout height='40'>"
    L"<Label name='Option' padding='0,20,0,20' text-align='singleline|center' height='40' font-size='19' background-color='0x0' textcolor='0xFFFFFFFF' text-overflow='ellipsis'/>"
    L"<Texture name='OptionSelectedIcon' float='true' left='260' top='12' width='21' height='17' visibility='false' background-image='@DialogSelectedIcon' background-color='0x0'/>"
  L"</HorizontalLayout>";

CHAR16 *mOrderedListOptionListChilds = L""
  L"<ListView moveitemsupport='true' name='OrderedListOptionList' width='match_parent' height='match_parent' vscrollbar='true' tabstop='true' child-padding='2' taborder='1'/>";

CHAR16 *mOrderedListOptionListOptionChilds = L""
  L"<HorizontalLayout width='-1' name='Option' height='40' background-color='0xFFE6E6E6'>"
    L"<Texture width='40' name='Icon' height='40'/>"
    L"<Label padding='7,0,7,0' text-align='center' textcolor='0xFF404040' font-size='14' name='Words'/>"
    L"<Texture height='40' width='40' background-image='@DialogSortIcon' name='SortIcon' background-image-style='stretch|gray'/>"
  L"</HorizontalLayout>";

CHAR16 *mPasswordInputChilds = L""
  L"<VerticalLayout>"
    L"<HorizontalLayout width='300' background-color='0xFFF2F2F2' name='OldPassword' height='41'>"
      L"<Label width='119' textcolor='0xFF4D4D4D' font-size='16' name='OldPasswordLabel' height='41'/>"
      L"<VerticalLayout padding='6,8,6,0' width='181' height='41'>"
        L"<Control/>"
        L"<Control padding='1,1,1,1' width='173' background-color='0xFF999999' height='29'>"
          L"<UiEdit name='OldPasswordText' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' tabstop='true' height='27' padding='7,3,0,3' width='171' taborder='1' background-color='0xFFF2F2F2' password='true'/>"
        L"</Control>"
        L"<Control/>"
      L"</VerticalLayout>"
    L"</HorizontalLayout>"
    L"<Control name='OldPasswordSeperator' height='2'/>"
    L"<HorizontalLayout width='300' background-color='0xFFF2F2F2' name='NewPassword' height='41'>"
      L"<Label width='119' textcolor='0xFF4D4D4D' font-size='16' name='NewPasswordLabel' height='41'/>"
      L"<VerticalLayout padding='6,8,6,0' width='181' height='41'>"
        L"<Control/>"
        L"<Control padding='1,1,1,1' width='173' background-color='0xFF999999' height='29'>"
          L"<UiEdit name='NewPasswordText' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' tabstop='true' height='27' padding='7,3,0,3' width='171' taborder='2' background-color='0xFFF2F2F2' password='true'/>"
        L"</Control>"
        L"<Control/>"
      L"</VerticalLayout>"
    L"</HorizontalLayout>"
    L"<Control name='NewPasswordSeperator' height='2'/>"
    L"<HorizontalLayout width='300' background-color='0xFFF2F2F2' name='ConfirmNewPassword' height='41'>"
      L"<Label width='119' textcolor='0xFF4D4D4D' font-size='16' name='ConfirmNewPasswordLabel' height='41'/>"
      L"<VerticalLayout padding='6,8,6,0' width='181' height='41'>"
        L"<Control/>"
        L"<Control padding='1,1,1,1' width='173' background-color='0xFF999999' height='29'>"
          L"<UiEdit name='ConfirmNewPasswordText' focusbkcolor='@menulightcolor' focustextcolor='0xFF404040' tabstop='true' height='27' padding='7,3,0,3' width='171' taborder='3' background-color='0xFFF2F2F2' password='true'/>"
        L"</Control>"
        L"<Control/>"
      L"</VerticalLayout>"
    L"</HorizontalLayout>"
  L"</VerticalLayout>";

CHAR16 *mStringInputChilds = L""
  L"<HorizontalLayout width='300' background-color='0xFFF2F2F2' height='wrap_content' >"
    L"<Label name='StringLabel' text='input string:' height='41' padding='12,0,0,0' width='119' font-size='16' textcolor='0xFF4D4D4D'/>"
    L"<VerticalLayout name='InputStringArea' padding='6,8,6,0' width='181' height='wrap_content' >"
      L"<Control/>"
      L"<Control name='InputStringBox' padding='1,1,1,1' width='173' background-color='0xFF999999' height='wrap_content'>"
        L"<UiEdit name='InputStringText' focusbkcolor='@menulightcolor' tabstop='true' font-size='19' height='wrap_content' width='171' taborder='1' background-color='0xFFF2F2F2'/>"
      L"</Control>"
      L"<Control/>"
    L"</VerticalLayout>"
  L"</HorizontalLayout>";

CHAR16 *mTimeRollerChilds = L""
  L"<TimeItem name='Time' width='match_parent' height='match_parent' tabstop='true'/>"
  ;

INT32
GetStatementHeight (
  IN VOID                                 *Statement
  )
{
  return 35;
}
#endif

