/*******************************************************************************
*
 * Copyright (C) 2021-2022 Advanced Micro Devices, Inc. All rights reserved.
 *
*******************************************************************************/

#include <MyPorting.h>
#include "ApcbV2.h"
#include <MiscMemDefines.h>
#include <APCB.h>
#include "ApcbCustomizedDefinitions.h"
#include "ApcbCustomizedBoardDefinitions.h"
#include <ApcbDefaults.h>

APCB_TYPE_DATA_START_SIGNATURE();
APCB_V3_TYPE_HEADER       ApcbTypeHeader = {
  APCB_GROUP_MEMORY,                    // GroupId
  APCB_MEM_TYPE_PLATFORM_TUNING,        // TypeId
  sizeof(ApcbTypeHeader),       // SizeOfType, will be fixed up by tool
  0,                            // InstanceId
  {
    APCB_TYPE_ATTR_CONTEXT_TYPE_STRUCT,
    APCB_TYPE_ATTR_CONTEXT_FORMAT_NATIVE_RAW,
    0,
    APCB_PRIORITY_TYPE_MASK_DEFAULT,    // Priority mask
    0,
    0,
    BLDCFG_APCB_DATA_BOARD_MASK             // Board specific APCB instance mask
  }
};  // SizeOfType will be fixed up by tool

PTO_ENTRY PtoEntry[] = {
#if 0
MAKE_PTO_VALIDITY_DRAM_MFG_ID_ENTRY(SOCKET0, CHANNEL_A, 0x7766),
MAKE_PTO_VALIDITY_DRAM_STEPPING_ENTRY(SOCKET0, CHANNEL_A, 0x88),
     MAKE_PTO_CHIPSEL_INTLV_ENTRY(ANY_SOCKET, ANY_CHANNEL, FALSE),
     MAKE_PTO_ECC_ENTRY(ANY_SOCKET, ANY_CHANNEL, TRUE),
     MAKE_PTO_MEM_BUS_LIMIT_ENTRY(ANY_SOCKET, ANY_CHANNEL, 1200),
     MAKE_PTO_MBIST_ENABLE_ENTRY(ANY_SOCKET, ANY_CHANNEL, FALSE),
     MAKE_PTO_MBIST_TEST_MODE_ENTRY  (ANY_SOCKET, ANY_CHANNEL, 2),
     MAKE_PTO_POST_PACKAGE_REPAIR_ENABLE_ENTRY(ANY_SOCKET, ANY_CHANNEL, TRUE),
     MAKE_PTO_BANK_GROUP_SWAP_ENTRY(ANY_SOCKET, ANY_CHANNEL, FALSE),

     MAKE_PTO_AUTO_REFFINE_GRAN_MODE_ENTRY(ANY_SOCKET, ANY_CHANNEL, 1),
     MAKE_PTO_ADDR_CMD_PARITY_RETRY_ENTRY(ANY_SOCKET, ANY_CHANNEL, FALSE),
     MAKE_PTO_RCD_PARITY_ENABLE_ENTRY(ANY_SOCKET, ANY_CHANNEL, TRUE),
     MAKE_PTO_WR_CRC_ENABLE_ENTRY(ANY_SOCKET, ANY_CHANNEL, TRUE),
     MAKE_PTO_WR_CRC_RETRY_ENTRY(ANY_SOCKET, ANY_CHANNEL, FALSE),
     MAKE_PTO_SPD_VALUE_OVERRIDE_ENTRY(SOCKET0, CHANNEL_A, DIMM0, 13, 0x0B),
     MAKE_PTO_SPD_CRC_IGNORE_ENTRY(ANY_SOCKET, ANY_CHANNEL, ALL_DIMMS, TRUE),
MAKE_PTO_VALIDITY_END(),

     MAKE_PTO_CMD_BUS_TMG_ENTRY(ANY_SOCKET, ANY_CHANNEL, 1, DDR1600, 0xFF, V1_2, DIMM_SR, NP, 0, 0x003A3A3A, 7, 7, 7, 7),
     MAKE_PTO_GEAR_DOWN_ENABLE_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0,  DIMM_SR, NP, TRUE),
     MAKE_PTO_CMD_2T_ENABLE_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0,  DIMM_SR, NP, TRUE),
     MAKE_PTO_WR_PREAMBLE_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0,	DIMM_SR, NP, TRUE),
     MAKE_PTO_RD_PREAMBLE_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0,	DIMM_SR, NP, FALSE),
     MAKE_PTO_ODT_PAT_CTRL_CS0_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0,  DIMM_SR, NP, 0x8),
     MAKE_PTO_ODT_PAT_CTRL_CS1_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0,  DIMM_SR, NP, 0x5),
     MAKE_PTO_ODT_PAT_CTRL_CS2_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0,  DIMM_SR, NP, 0x6),
     MAKE_PTO_ODT_PAT_CTRL_CS3_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0,  DIMM_SR, NP, 0x1),
     MAKE_PTO_TX_EQ_IMPEDANCE_DQ_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0,  DIMM_SR, NP, 0x16),

MAKE_PTO_VALIDITY_DRAM_MFG_ID_ENTRY(ANY_SOCKET, ANY_CHANNEL, 0),
     MAKE_PTO_TX_ODT_DRV_STREN_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0,  DIMM_SR, NP, 0x17),
MAKE_PTO_VALIDITY_END(),


     MAKE_PTO_TRCDWR_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0,  DIMM_SR, NP, 0x06),
     MAKE_PTO_TRCDRD_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0,  DIMM_SR, NP, 0x88),
     MAKE_PTO_TRAS_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0,  DIMM_SR, NP, 0x17),
     MAKE_PTO_TCL_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0,  DIMM_SR, NP, 0x16),
     MAKE_PTO_TRP_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0,  DIMM_SR, NP, 0x0A),
     MAKE_PTO_TFAWSLR_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0,  DIMM_SR, NP, 0x20),
     MAKE_PTO_TFAW_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0, DIMM_SR, NP, 0x38),
     MAKE_PTO_TCWL_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0, DIMM_SR, NP, 0x0F),
     MAKE_PTO_TWR_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0,  DIMM_SR, NP, 0x30),
     MAKE_PTO_TRCPAGE_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0,  DIMM_SR, NP, 0x88),
     MAKE_PTO_TSTAG_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0,	  DIMM_SR, NP, 0x99),
     MAKE_PTO_TSTAG2LR_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0, DIMM_SR, NP, 0x55),
     MAKE_PTO_TSTAG4LR_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0, DIMM_SR, NP, 0x00),

     MAKE_PTO_TRRDL_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0, DIMM_SR, NP, 0x09),
     MAKE_PTO_TWTRS_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0, DIMM_SR, NP, 0x06),
     MAKE_PTO_TRFC2_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0, DIMM_SR, NP, 0x1FF),

     MAKE_PTO_TRTP_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0,  DIMM_SR, NP, 0x09),
     MAKE_PTO_TRRDDLR_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0, DIMM_SR, NP, 0x0B),
     MAKE_PTO_TFAWDLR_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0, DIMM_SR, NP, 0x32),

     MAKE_PTO_TRDRDBAN_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0, DIMM_SR, NP, 0x02),
     MAKE_PTO_TRDRDSCL_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0, DIMM_SR, NP, 0x10),

     MAKE_PTO_TWRWRSCDLR_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0, DIMM_SR, NP, 0x0C),
     MAKE_PTO_TRDRDDD_ENTRY(ANY_SOCKET, CHANNEL_A, MEMORY_PSTATE0, DIMM_SR, NP, 0),

     MAKE_PTO_ADDR_CMD_SETUP_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x08),
     MAKE_PTO_CS_ODT_SETUP_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x09),
     MAKE_PTO_CKE_SETUP_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x0A),

MAKE_PTO_VALIDITY_DRAM_MFG_ID_ENTRY(ANY_SOCKET, ANY_CHANNEL, 0x7766),
     MAKE_PTO_CLK_DRV_STREN_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE1, DIMM_SR, NP, 0x65),
     MAKE_PTO_ADDR_CMD_DRV_STREN_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE1, DIMM_SR, NP, 0x66),
     MAKE_PTO_CS_ODT_DRV_STREN_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE1, DIMM_SR, NP, 0x67),
     MAKE_PTO_CKE_DRV_STREN_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE1, DIMM_SR, NP, 0x68),
MAKE_PTO_VALIDITY_END(),

MAKE_PTO_VALIDITY_DRAM_MFG_ID_ENTRY(ANY_SOCKET, ANY_CHANNEL, 0x1111),
     MAKE_PTO_1D_TRAIN_MR0_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x0123),
     MAKE_PTO_2D_TRAIN_MR0_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x7645),
     MAKE_PTO_1D_TRAIN_MR1_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x3412),
     MAKE_PTO_2D_TRAIN_MR1_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x6745),
     MAKE_PTO_1D_TRAIN_MR2_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x7766),
     MAKE_PTO_2D_TRAIN_MR2_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x5566),
     MAKE_PTO_1D_TRAIN_MR3_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x0101),
     MAKE_PTO_2D_TRAIN_MR3_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x3434),
MAKE_PTO_VALIDITY_END(),

     MAKE_PTO_1D_TRAIN_MR4_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x1423),
     MAKE_PTO_2D_TRAIN_MR4_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x4756),

     MAKE_PTO_1D_TRAIN_MR5_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x9876),
     MAKE_PTO_2D_TRAIN_MR5_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x1324),

     MAKE_PTO_1D_TRAIN_MR6_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x7643),
     MAKE_PTO_2D_TRAIN_MR6_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x8811),

     MAKE_PTO_1D_TRAIN_PHY_VREF_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x78),
     MAKE_PTO_2D_TRAIN_PHY_VREF_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x87),

     MAKE_PTO_1D_TRAIN_SEQUENCE_CTRL_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, (SMB_SEQ_DEVINIT | SMB_SEQ_WRLVL | SMB_SEQ_RXEN | SMB_SEQ_RDDQS1D | SMB_SEQ_WRDQ1D | SMB_SEQ_MXRDLAT )),
     MAKE_PTO_2D_TRAIN_SEQUENCE_CTRL_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, (SMB_SEQ_DEVINIT | SMB_SEQ_WRLVL | SMB_SEQ_RXEN | SMB_SEQ_RDDQS1D | SMB_SEQ_WRDQ1D | SMB_SEQ_MXRDLAT )),

     MAKE_PTO_1D_TRAIN_DFI_MRL_MARGIN_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x08),
     MAKE_PTO_2D_TRAIN_DFI_MRL_MARGIN_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x88),

     MAKE_PTO_2D_TRAIN_RX2D_TRAIN_OPT_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 1),
     MAKE_PTO_2D_TRAIN_TX2D_TRAIN_OPT_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 1),

     MAKE_PTO_1D_CUSTOM_MSG_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x0C, 0x66),
     MAKE_PTO_2D_CUSTOM_MSG_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x24, 0x33),

     MAKE_PTO_1D_TRAIN_ACSM_ODT_CTRL0_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x07),
     MAKE_PTO_1D_TRAIN_ACSM_ODT_CTRL1_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x16),
     MAKE_PTO_1D_TRAIN_ACSM_ODT_CTRL2_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x25),
     MAKE_PTO_1D_TRAIN_ACSM_ODT_CTRL3_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x34),
     MAKE_PTO_1D_TRAIN_ACSM_ODT_CTRL4_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x43),
     MAKE_PTO_1D_TRAIN_ACSM_ODT_CTRL5_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x52),
     MAKE_PTO_1D_TRAIN_ACSM_ODT_CTRL6_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x61),
     MAKE_PTO_1D_TRAIN_ACSM_ODT_CTRL7_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x70),

     MAKE_PTO_2D_TRAIN_ACSM_ODT_CTRL0_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x11),
     MAKE_PTO_2D_TRAIN_ACSM_ODT_CTRL1_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x22),
     MAKE_PTO_2D_TRAIN_ACSM_ODT_CTRL2_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x33),
     MAKE_PTO_2D_TRAIN_ACSM_ODT_CTRL3_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x44),
     MAKE_PTO_2D_TRAIN_ACSM_ODT_CTRL4_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x55),
     MAKE_PTO_2D_TRAIN_ACSM_ODT_CTRL5_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x66),
     MAKE_PTO_2D_TRAIN_ACSM_ODT_CTRL6_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x77),
     MAKE_PTO_2D_TRAIN_ACSM_ODT_CTRL7_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x88),

     MAKE_PTO_1D_TRAIN_ALT_WCAS_L_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x17),
     MAKE_PTO_2D_TRAIN_ALT_WCAS_L_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, DIMM_SR, NP, 0x88),

     // Phy registers
     MAKE_PTO_RX_ENABLE_DELAY_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, OP_MINUS, 0, 1, 1, 0x55),
     MAKE_PTO_TX_DQ_DELAY_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, OP_OVERRIDE, 0, 1, 2, 0x111),
     MAKE_PTO_RX_PB_DELAY_ENTRY(ANY_SOCKET, ANY_CHANNEL, OP_PLUS, 0, 3, 5, 0x23),
     MAKE_PTO_RX_CLK_DELAY_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, OP_PLUS, 0, 5, 3, 0x11),
     MAKE_PTO_VREF_DAC_0_ENTRY(ANY_SOCKET, ANY_CHANNEL, OP_MINUS, 7, 6, 0x88),
     MAKE_PTO_VREF_DAC_1_ENTRY(ANY_SOCKET, ANY_CHANNEL, OP_PLUS, 2, 5, 0x34),
     MAKE_PTO_VREF_IN_GLOBAL_ENTRY(ANY_SOCKET, ANY_CHANNEL, MEMORY_PSTATE0, OP_OVERRIDE, 0x88),

     MAKE_PTO_ENABLE_POWER_DOWN_ENTRY(ANY_SOCKET, ANY_CHANNEL, FALSE),
     MAKE_PTO_ENABLE_TUNING_MEMORY_ALL_CLOCKS_ON_ENTRY(ANY_SOCKET, ANY_CHANNEL, FALSE),
     MAKE_PTO_TEMPERATURE_CONTROLLED_REFRESH_ENABLE_ENTRY(ANY_SOCKET, ANY_CHANNEL, TRUE),
     MAKE_PTO_DATA_BUS_TMG_ENTRY(ANY_SOCKET, ANY_CHANNEL, 1, DDR1600, 0xFF, V1_2, DIMM_SR, NP, 1, 2, 3, 4, 5, 6),

     MAKE_PTO_ECC_SYMBOL_SIZE_ENTRY(ANY_SOCKET, ANY_CHANNEL, 1),
     MAKE_PTO_DDR4_UECC_RETRY_ENTRY(ANY_SOCKET, ANY_CHANNEL, TRUE),
#endif

   // Terminator
   MAKE_PTO_TERMINATE()
};

APCB_TYPE_DATA_END_SIGNATURE();
APCB_DUMMY_MAIN_FUNC();

