#!/bin/bash
APCB_TOOL_PATH=$WORKSPACE/$CHIPSET_REL_PATH/AgesaModulePkg/AMDTools/ApcbToolV3/Tools
APCB_PKG_PATH=$WORKSPACE/$CHIPSET_REL_PATH/AgesaPkg/Addendum/Apcb
APCB_INC_PATH=$APCB_PKG_PATH/Inc
APCB_BOARD_PKG_PATH=$APCB_PKG_PATH/RembrandtFp7r2

APCB_TEMP_PATH=$WORKSPACE/Build/$PROJECT_PKG/ApcbToolV3
APCB_TOOL_TEMP_PATH=$APCB_TEMP_PATH/Tools
APCB_INC_TEMP_PATH=$APCB_TEMP_PATH/Inc
APCB_BOARD_PKG_TEMP_PATH=$APCB_TEMP_PATH/External
export APCB_MULTI_BOARD_SUPPORT=1
export APCB_EXTERNAL_BUILD=1

#
# Clean up existing files
#
if [ -d $APCB_TEMP_PATH ]; then
  rm -rf $APCB_TEMP_PATH
fi
mkdir -p $APCB_TOOL_TEMP_PATH
mkdir -p $APCB_INC_TEMP_PATH
mkdir -p $APCB_BOARD_PKG_TEMP_PATH

cp -R $APCB_TOOL_PATH/*                      $APCB_TOOL_TEMP_PATH
cp -R $APCB_INC_PATH/*                       $APCB_INC_TEMP_PATH
cp -R $APCB_BOARD_PKG_PATH/*                 $APCB_BOARD_PKG_TEMP_PATH

#
# Override platform specific settings
#

cp $WORKSPACE/$PROJECT_REL_PATH/$PROJECT_PKG/ApcbV3Customization/ApcbCustomizedDefinitionsRmbFp7DDR5.h $APCB_BOARD_PKG_TEMP_PATH/Include/ApcbCustomizedDefinitions.h
cp $WORKSPACE/$PROJECT_REL_PATH/$PROJECT_PKG/ApcbV3Customization/ApcbDdr5SpdImages.h $APCB_BOARD_PKG_TEMP_PATH/Include/ApcbDdr5SpdImages.h
cp $WORKSPACE/$PROJECT_REL_PATH/$PROJECT_PKG/ApcbV3Customization/ApcbDdr5SpdMircon.h $APCB_BOARD_PKG_TEMP_PATH/Include/ApcbDdr5SpdMircon.h

cp $WORKSPACE/$PROJECT_REL_PATH/$PROJECT_PKG/ApcbV3Customization/ApcbCreatsRMB.py $APCB_BOARD_PKG_TEMP_PATH/ApcbGen.py
cp $WORKSPACE/$PROJECT_REL_PATH/$PROJECT_PKG/ApcbV3Customization/ApcbCreate.json $APCB_BOARD_PKG_TEMP_PATH/ApcbCreate.json

#
# Override autogenerated GBS settings
#
mkdir -p $APCB_BOARD_PKG_TEMP_PATH/Include
cp $WORKSPACE/$CHIPSET_REL_PATH/AmdCbsPkg/Build/ResourceRMB/ApcbAutoGenRMB.h $APCB_BOARD_PKG_TEMP_PATH/Include/ApcbAutoGen.h

pushd $APCB_BOARD_PKG_TEMP_PATH

#
# Customize the APCB tool directory
#
#TOOL_DIR=$APCB_TOOL_TEMP_PATH
#export TOOL_DIR
#
# Run ApcbCreate to generate APCB binary
#
echo $APCB_BOARD_PKG_TEMP_PATH/ApcbGen.py
python3 $APCB_BOARD_PKG_TEMP_PATH/ApcbGen.py CLEAN BUILD
#rem if %errorlevel% neq 0 exit

CUSTOM_APCB_PATH=$APCB_BOARD_PKG_TEMP_PATH/Release/

cp $CUSTOM_APCB_PATH/APCB_FP7r2_DefaultRecovery.bin $CUSTOM_APCB_PATH/APCB_FP7r2.bin

popd
