
@echo off

@set APCB_TOOL_PATH=%WORKSPACE%\%CHIPSET_REL_PATH%\AgesaModulePkg\AMDTools\ApcbToolV3\Tools
@set APCB_PKG_PATH=%WORKSPACE%\%CHIPSET_REL_PATH%\AgesaPkg\Addendum\Apcb
@set APCB_INC_PATH=%APCB_PKG_PATH%\Inc
@set APCB_BOARD_PKG_PATH=%APCB_PKG_PATH%\RembrandtFp7r2

@set APCB_TEMP_PATH=%WORKSPACE%\Build\%PROJECT_PKG%\ApcbToolV3
@set APCB_TOOL_TEMP_PATH=%APCB_TEMP_PATH%\Tools
@set APCB_INC_TEMP_PATH=%APCB_TEMP_PATH%\Inc
@set APCB_BOARD_PKG_TEMP_PATH=%APCB_TEMP_PATH%\External
@set APCB_BUILD_COMMAND=ApcbCreate.bat

@if %BUILD_TYPE% == INTERNAL (
  echo "APCB internal build"
  @set APCB_BOARD_PKG_PATH=%APCB_BOARD_PKG_PATH%
  @set APCB_BOARD_PKG_TEMP_PATH=%APCB_TEMP_PATH%\Internal
  @set APCB_BUILD_COMMAND=ApcbCreateInt.bat
)


::
:: Clean up existing files
::
@if exist %APCB_TEMP_PATH% (
  @rd %APCB_TEMP_PATH% /S /Q
)

@echo D | @xcopy %APCB_TOOL_PATH%\*.*                    %APCB_TOOL_TEMP_PATH% /S /Y
@echo D | @xcopy %APCB_INC_PATH%\*.*                     %APCB_INC_TEMP_PATH% /S /Y
@echo D | @xcopy %APCB_BOARD_PKG_PATH%\*.*               %APCB_BOARD_PKG_TEMP_PATH% /S /Y

::
:: Override platform specific settings
::

@copy %WORKSPACE%\%PROJECT_REL_PATH%\%PROJECT_PKG%\ApcbV3Customization\ApcbCustomizedDefinitionsRmbFp7DDR5.h %APCB_BOARD_PKG_TEMP_PATH%\Include\ApcbCustomizedDefinitions.h
@copy %WORKSPACE%\%PROJECT_REL_PATH%\%PROJECT_PKG%\ApcbV3Customization\ApcbDdr5SpdImages.h %APCB_BOARD_PKG_TEMP_PATH%\Include\ApcbDdr5SpdImages.h
@copy %WORKSPACE%\%PROJECT_REL_PATH%\%PROJECT_PKG%\ApcbV3Customization\ApcbDdr5SpdMircon.h %APCB_BOARD_PKG_TEMP_PATH%\Include\ApcbDdr5SpdMircon.h

@copy %WORKSPACE%\%PROJECT_REL_PATH%\%PROJECT_PKG%\ApcbV3Customization\%APCB_BUILD_COMMAND% %APCB_BOARD_PKG_TEMP_PATH%\%APCB_BUILD_COMMAND%

::
:: Override autogenerated GBS settings
::
REM @copy %WORKSPACE%\AmdCbsPkg\Build\ResourceRVFP5\ApcbAutoGenRV.h %APCB_BOARD_PKG_TEMP_PATH%\Include\ApcbAutoGen.h
@copy %WORKSPACE%\%CHIPSET_REL_PATH%\AmdCbsPkg\Build\ResourceRMB\ApcbAutoGenRMB.h %APCB_BOARD_PKG_TEMP_PATH%\Include\ApcbAutoGen.h
::@copy %WORKSPACE%\%PROJECT_PKG%\ApcbV3Customization\EmptyApcbAutoGen.h %APCB_BOARD_PKG_TEMP_PATH%\Include\ApcbAutoGen.h

@pushd %APCB_BOARD_PKG_TEMP_PATH%

::
:: Customize the APCB tool directory
::
SET TOOL_DIR=%APCB_TOOL_TEMP_PATH%
::
:: Run ApcbCreate to generate APCB binary
::
echo  %APCB_BOARD_PKG_TEMP_PATH%\%APCB_BUILD_COMMAND%
@call %APCB_BOARD_PKG_TEMP_PATH%\%APCB_BUILD_COMMAND% CLEAN BUILD
if %errorlevel% neq 0 exit

@set CUSTOM_APCB_PATH=%APCB_BOARD_PKG_TEMP_PATH%\Release\

@popd

@goto end

:end
