/*****************************************************************************
 *
 * Copyright (C) 2020-2022 Advanced Micro Devices, Inc. All rights reserved.
 *
 ******************************************************************************
 */
/*****************************************************************************
 *
 * This software package can be used to enable the Overclocking of certain
 * AMD processors and its use is subject to the terms and conditions of the
 * AMD Overclocking Waiver. Enabling overclocking through use of the low-level
 * routines included in this package and operating an AMD processor outside of
 * the applicable AMD product specifications will void any AMD warranty and can
 * result in damage to the processor or the system into which the processor has
 * been integrated. The user of this software assumes, and AMD disclaims, all
 * risk, liability, costs and damages relating to or arising from the overclocking
 * of AMD processors.
 *
 ******************************************************************************
 */
#ifndef __AOD_CMD_SMM_PROTOCOL_H__
#define __AOD_CMD_SMM_PROTOCOL_H__


#pragma pack(1)

typedef enum {

  ///
  /// Cmdid to AOD nvs, not sured if this always needed to update NVS
  /// when a set type cmdid is called. A get CmdId is necessary to report
  /// this interface, becasue RyMaster used 200 bytes NVS
  /// AOD_CMD_SMM_CALLBACK (CmdId, CmdData, Aod Nvs Buffer)
  ///
  AOD_SMM_CMD_TO_NVS            = 0x1,

  ///
  /// Cmdid to AOD variable, save the cmdid data into variable global data
  /// variable will been write
  /// AOD_CMD_SMM_CALLBACK (CmdId, CmdData, AOD_CONFIG buffer)
  ///
  AOD_SMM_CMD_TO_VARIABLE       = 0x2,

  ///
  /// sync AOD variable into APCB, this only been called when COMMAND_BUFFER_END
  /// is called which means this end for all wmi cmds, we need to sync some
  /// configurations such as mem into APCB for ABL
  /// AOD_CMD_SMM_CALLBACK (0, 0, AOD_CONFIG buffer)
  ///
  AOD_SMM_VARIABLE_TO_APCB      = 0x3,

  ///
  /// A particular cmdid may need for specical case. use this will allow
  /// register wmi cmd operation dynamiclly
  /// For example, if you want to add a WA for cmdid for specical cases
  /// CmdId = xxxx, CallbackPhase = AOD_SMM_CMD_SPECAIL , if cmdid is matched
  /// the callback rountine will been called.
  /// AOD_CMD_SMM_CALLBACK (CmdId, CmdData, AOD_CONFIG buffer)
  ///
  AOD_SMM_CMD_SPECAIL           = 0x4,

  ///
  /// sync AOD variable into something
  /// CmdId = xxxx, CallbackPhase = AOD_SMM_CMD_VARIABLE_HOOK ,
  /// AOD_CMD_SMM_CALLBACK (xxxx, xxxx, AOD_CONFIG buffer)
  ///
  AOD_SMM_CMD_VARIABLE_HOOK     = 0x5
} AOD_CMD_SMM_CALLBACKPHASE;

typedef struct {
  UINT8     CallbackPhase;
  //
  // CmdId equal to zero means always runed when phase is singaled
  //
  UINT32    CmdId;
} AOD_CMD_SMM_REGISTER_CONTEXT;
#pragma pack()

/*
  AOD_CMD_SMM_CALLBACK callback function. Input Context is different with different CallbackPhase

  AOD_SMM_CMD_SPECAIL:
    AOD_CMD_SMM_CALLBACK (0, 0, AOD_CONFIG buffer)
  AOD_SMM_CMD_TO_NVS:
    AOD_CMD_SMM_CALLBACK (CmdId, CmdData, Aod Nvs Buffer)
  AOD_SMM_CMD_TO_VARIABLE:
    AOD_CMD_SMM_CALLBACK (CmdId, CmdData, AOD_CONFIG buffer)
  AOD_SMM_VARIABLE_TO_APCB:
    AOD_CMD_SMM_CALLBACK (0, 0, AOD_CONFIG buffer)
*/
typedef
EFI_STATUS
(EFIAPI *AOD_CMD_SMM_CALLBACK) (
  IN    UINT32         CmdId,
  IN    UINT32         Data,
  IN    VOID           *Context
  );

typedef struct _AOD_CMD_SMM_DISPATCH_PROTOCOL   AOD_CMD_SMM_DISPATCH_PROTOCOL;

/**
  Register a child SMI source callback function for the WMI smi

  This service registers a function which will be called when the input WMI command ID
  and Phase is mathced. On return,  DispatchHandle contains a unique handle which may be used later
  to unregister the function using UnRegister().

  @param[in]  This                 Pointer to the AOD_CMD_SMM_DISPATCH_PROTOCOL instance.
  @param[in]  Context              Pointer to AOD_CMD_SMM_REGISTER_CONTEXT context.
                                   The caller fills this context in before calling
                                   the register function to indicate to the register
                                   function which callback function should be invoked for.
  @param[in]  Callback             Pointer to the AOD_CMD_SMM_CALLBACK callback function.
  @param[out] DispatchHandle       Handle generated by the dispatcher to track the
                                   function instance.

  @retval EFI_SUCCESS            The callback function has been successfully registered
  @retval EFI_INVALID_PARAMETER  Context is invalid.
  @retval EFI_OUT_OF_RESOURCES   There is not enough memory (system or SMM) to manage this
                                 child.
  @retval EFI_ACCESS_DENIED      SmmReadyToLock is signaled
**/
typedef
EFI_STATUS
(EFIAPI *AOD_CMD_SMM_REGISTER)(
  IN  CONST AOD_CMD_SMM_DISPATCH_PROTOCOL      *This,
  IN        AOD_CMD_SMM_REGISTER_CONTEXT       *Context,
  IN        AOD_CMD_SMM_CALLBACK               Callback,
  OUT       EFI_HANDLE                         *Handle
  );

/**
  Unregister a child SMI source callback function for the WMI smi

  @param[in] This                Pointer to the EFI_SMM_SW_DISPATCH2_PROTOCOL instance.
  @param[in] Handle              Handle of dispatch function to deregister.

  @retval EFI_SUCCESS            The dispatch function has been successfully unregistered.
  @retval EFI_INVALID_PARAMETER  The DispatchHandle was not valid.
  @retval EFI_ACCESS_DENIED      SmmReadyToLock is signaled
**/
typedef
EFI_STATUS
(EFIAPI *AOD_CMD_SMM_UNREGISTER)(
  IN CONST AOD_CMD_SMM_DISPATCH_PROTOCOL      *This,
  IN       EFI_HANDLE                         *Handle
);

///
/// Interface structure for the AOD CMD SMM Protocol.
///
/// The EFI_SMM_SW_DISPATCH2_PROTOCOL provides the ability to install child handlers for the
/// given context. These handlers will respond to RyMaster's cmd
///
struct _AOD_CMD_SMM_DISPATCH_PROTOCOL {
  AOD_CMD_SMM_REGISTER                  Register;
  AOD_CMD_SMM_UNREGISTER                UnRegister;
};


#endif
