/*****************************************************************************
 *
 * Copyright (C) 2008-2022 Advanced Micro Devices, Inc. All rights reserved.
 *
 *******************************************************************************
 */
//This file is auto generated, don't edit it manually

#ifndef _IDS_NV_ID_RMB_H_
#define _IDS_NV_ID_RMB_H_


#ifndef IDSNVID_CMN_CPU_GEN_W_A05
  #define IDSNVID_CMN_CPU_GEN_W_A05   (0xD000) //RedirectForReturnDis
#endif

#ifndef IDSNVID_CMN_CPU_CPB
  #define IDSNVID_CMN_CPU_CPB   (0xD001) //Core Performance Boost
#endif

#ifndef IDSNVID_CMN_CPU_GLOBAL_CSTATE_CTRL
  #define IDSNVID_CMN_CPU_GLOBAL_CSTATE_CTRL   (0xD002) //Global C-state Control
#endif

#ifndef IDSNVID_CMN_CPU_OPCACHE_GRAYOUT_FLAG
  #define IDSNVID_CMN_CPU_OPCACHE_GRAYOUT_FLAG   (0xD003) //Opcache grayout flag
#endif

#ifndef IDSNVID_CMN_CPU_OPCACHE_CTRL
  #define IDSNVID_CMN_CPU_OPCACHE_CTRL   (0xD004) //Opcache Control
#endif

#ifndef IDSNVID_CMN_CPU_SEV_ASID_COUNT
  #define IDSNVID_CMN_CPU_SEV_ASID_COUNT   (0xD005) //SEV ASID Count
#endif

#ifndef IDSNVID_CMN_CPU_SEV_ASID_SPACE_CTRL
  #define IDSNVID_CMN_CPU_SEV_ASID_SPACE_CTRL   (0xD006) //SEV-ES ASID Space Limit Control
#endif

#ifndef IDSNVID_CMN_CPU_SEV_ASID_SPACE_LIMIT
  #define IDSNVID_CMN_CPU_SEV_ASID_SPACE_LIMIT   (0xD007) //SEV-ES ASID Space Limit
#endif

#ifndef IDSNVID_CMN_CPU_STREAMING_STORES_CTRL
  #define IDSNVID_CMN_CPU_STREAMING_STORES_CTRL   (0xD008) //Streaming Stores Control
#endif

#ifndef IDSNVID_CPU_L_APIC_MODE
  #define IDSNVID_CPU_L_APIC_MODE   (0xD009) //Local APIC Mode
#endif

#ifndef IDSNVID_CMN_CPU_CST_C1_CTRL
  #define IDSNVID_CMN_CPU_CST_C1_CTRL   (0xD00A) //ACPI _CST C1 Declaration
#endif

#ifndef IDSNVID_CMN_CPU_PM_CTL_PSS
  #define IDSNVID_CMN_CPU_PM_CTL_PSS   (0xD00B) //ACPI _PSS
#endif

#ifndef IDSNVID_CMN_CPU_MCA_ERR_THRESH_EN
  #define IDSNVID_CMN_CPU_MCA_ERR_THRESH_EN   (0xD00C) //MCA error thresh enable
#endif

#ifndef IDSNVID_CMN_CPU_MCA_ERR_THRESH_COUNT
  #define IDSNVID_CMN_CPU_MCA_ERR_THRESH_COUNT   (0xD00D) //MCA error thresh count
#endif

#ifndef IDSNVID_CMN_CPU_SMU_PSP_DEBUG_MODE
  #define IDSNVID_CMN_CPU_SMU_PSP_DEBUG_MODE   (0xD00E) //SMU and PSP Debug Mode
#endif

#ifndef IDSNVID_CMN_CPU_PPIN_CTRL
  #define IDSNVID_CMN_CPU_PPIN_CTRL   (0xD00F) //PPIN Opt-in
#endif

#ifndef IDSNVID_CMN_CPU_FSRM
  #define IDSNVID_CMN_CPU_FSRM   (0xD010) //Fast Short REP MOVSB
#endif

#ifndef IDSNVID_CMN_CPU_ERMS
  #define IDSNVID_CMN_CPU_ERMS   (0xD011) //Enhanced REP MOVSB/STOSB
#endif

#ifndef IDSNVID_CMN_ACTION_ON_BIST_FAILURE
  #define IDSNVID_CMN_ACTION_ON_BIST_FAILURE   (0xD012) //Action on BIST Failure
#endif

#ifndef IDSNVID_CMN_CPU_IBS_HARDWARE_CTRL
  #define IDSNVID_CMN_CPU_IBS_HARDWARE_CTRL   (0xD013) //IBS hardware workaround
#endif

#ifndef IDSNVID_CMN_CPU_OC_MODE
  #define IDSNVID_CMN_CPU_OC_MODE   (0xD014) //OC Mode
#endif

#ifndef IDSNVID_CPU_LEGAL_DISCLAIMER
  #define IDSNVID_CPU_LEGAL_DISCLAIMER   (0xD015) //Pstates Disclaimer
#endif

#ifndef IDSNVID_CPU_LEGAL_DISCLAIMER1
  #define IDSNVID_CPU_LEGAL_DISCLAIMER1   (0xD016) //Pstates Disclaimer 1
#endif

#ifndef IDSNVID_CPU_PST_CUSTOM_P0
  #define IDSNVID_CPU_PST_CUSTOM_P0   (0xD017) //Custom Pstate0
#endif

#ifndef IDSNVID_CPU_PST0_FREQ
  #define IDSNVID_CPU_PST0_FREQ   (0xD018) //Pstate0 Freq (MHz)
#endif

#ifndef IDSNVID_CPU_PST0_VID
  #define IDSNVID_CPU_PST0_VID   (0xD019) //Pstate0 VID
#endif

#ifndef IDSNVID_CMN_CPU_L1_STREAM_HW_PREFETCHER
  #define IDSNVID_CMN_CPU_L1_STREAM_HW_PREFETCHER   (0xD01A) //L1 Stream HW Prefetcher
#endif

#ifndef IDSNVID_CMN_CPU_L2_STREAM_HW_PREFETCHER
  #define IDSNVID_CMN_CPU_L2_STREAM_HW_PREFETCHER   (0xD01B) //L2 Stream HW Prefetcher
#endif

#ifndef IDSNVID_DBG_CPU_GEN_CPU_WDT
  #define IDSNVID_DBG_CPU_GEN_CPU_WDT   (0xD01C) //Core Watchdog Timer Enable
#endif

#ifndef IDSNVID_DBG_CPU_GEN_CPU_WDT_TIMEOUT
  #define IDSNVID_DBG_CPU_GEN_CPU_WDT_TIMEOUT   (0xD01D) //Core Watchdog Timer Interval
#endif

#ifndef IDSNVID_CMN_CPU_WDT_SEV
  #define IDSNVID_CMN_CPU_WDT_SEV   (0xD01E) //Core Watchdog Timer Severity
#endif

#ifndef IDSNVID_CMN_CPU_CORE_CTRL_RMB
  #define IDSNVID_CMN_CPU_CORE_CTRL_RMB   (0xD01F) //Core control
#endif

#ifndef IDSNVID_CMN_CPU_SMT_CTRL
  #define IDSNVID_CMN_CPU_SMT_CTRL   (0xD020) //SMT Control
#endif

#ifndef IDSNVID_CMN_PERSISTENT_LOW
  #define IDSNVID_CMN_PERSISTENT_LOW   (0xD021) //Persistent memory Base Low
#endif

#ifndef IDSNVID_CMN_PERSISTENT_HIGH
  #define IDSNVID_CMN_PERSISTENT_HIGH   (0xD022) //Persistent memory Base High
#endif

#ifndef IDSNVID_CMN_PERSISTENT_SIZE_LOW
  #define IDSNVID_CMN_PERSISTENT_SIZE_LOW   (0xD023) //Persistent memory reserved size Low
#endif

#ifndef IDSNVID_CMN_PERSISTENT_SIZE_HIGH
  #define IDSNVID_CMN_PERSISTENT_SIZE_HIGH   (0xD024) //Persistent memory reserved size High
#endif

#ifndef IDSNVID_CMN_PERSISTENT_MEM_RETENTION
  #define IDSNVID_CMN_PERSISTENT_MEM_RETENTION   (0xD025) //Persistent memory Retention
#endif

#ifndef IDSNVID_DF_CMN_CC6_MEM_ENCRYPTION
  #define IDSNVID_DF_CMN_CC6_MEM_ENCRYPTION   (0xD026) //CC6 memory region encryption
#endif

#ifndef IDSNVID_DF_CMN_MEM_CLEAR
  #define IDSNVID_DF_CMN_MEM_CLEAR   (0xD027) //Memory Clear
#endif

#ifndef IDSNVID_DF_CMN_EXT_IP_SYNC_FLOOD_PROP
  #define IDSNVID_DF_CMN_EXT_IP_SYNC_FLOOD_PROP   (0xD028) //Disable DF to external downstream IP SyncFloodPropagation
#endif

#ifndef IDSNVID_DF_CMN_SYNC_FLOOD_PROP
  #define IDSNVID_DF_CMN_SYNC_FLOOD_PROP   (0xD029) //Disable DF sync flood propagation
#endif

#ifndef IDSNVID_DF_CMN_FREEZE_QUEUE_ERROR
  #define IDSNVID_DF_CMN_FREEZE_QUEUE_ERROR   (0xD02A) //Freeze DF module queues on error
#endif

#ifndef IDSNVID_DF_CMN_CSTATES
  #define IDSNVID_DF_CMN_CSTATES   (0xD02B) //DF Cstates
#endif

#ifndef IDSNVID_MP_EXCEP_RECOV_HANDLE
  #define IDSNVID_MP_EXCEP_RECOV_HANDLE   (0xD02C) //MP exception recovery handling
#endif

#ifndef IDSNVID_MEM_CLR_TIMEOUT
  #define IDSNVID_MEM_CLR_TIMEOUT   (0xD02D) //Memory clear timeout
#endif

#ifndef IDSNVID_DF_CMN_MEM_INTLV_SIZE
  #define IDSNVID_DF_CMN_MEM_INTLV_SIZE   (0xD02E) //Memory interleaving size
#endif

#ifndef IDSNVID_DF_CMN_DRAM_MAP_INVERSION
  #define IDSNVID_DF_CMN_DRAM_MAP_INVERSION   (0xD02F) //DRAM map inversion
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_LEGAL_DISCLAIMER_DDR
  #define IDSNVID_CMN_MEM_TIMING_LEGAL_DISCLAIMER_DDR   (0xD030) //DRAM Timing Configuration Legal Disclaimer
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_LEGAL_DISCLAIMER1_DDR
  #define IDSNVID_CMN_MEM_TIMING_LEGAL_DISCLAIMER1_DDR   (0xD031) //DRAM Timing Configuration Legal Disclaimer 1
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_SETTING_DDR
  #define IDSNVID_CMN_MEM_TIMING_SETTING_DDR   (0xD032) //Active Memory Timing Settings
#endif

#ifndef IDSNVID_CMN_MEM_TARGET_SPEED_DDR
  #define IDSNVID_CMN_MEM_TARGET_SPEED_DDR   (0xD033) //Memory Target Speed
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TCL_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TCL_CTRL_DDR   (0xD034) //Tcl Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TCL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TCL_DDR   (0xD035) //Tcl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRCD_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRCD_CTRL_DDR   (0xD036) //Trcd Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRCD_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRCD_DDR   (0xD037) //Trcd
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRP_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRP_CTRL_DDR   (0xD038) //Trp Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRP_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRP_DDR   (0xD039) //Trp
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRAS_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRAS_CTRL_DDR   (0xD03A) //Tras Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRAS_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRAS_DDR   (0xD03B) //Tras
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRC_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRC_CTRL_DDR   (0xD03C) //Trc Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRC_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRC_DDR   (0xD03D) //Trc
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWR_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TWR_CTRL_DDR   (0xD03E) //Twr Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWR_DDR
  #define IDSNVID_CMN_MEM_TIMING_TWR_DDR   (0xD03F) //Twr
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRFC1_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRFC1_CTRL_DDR   (0xD040) //Trfc1 Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRFC1_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRFC1_DDR   (0xD041) //Trfc1
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRFC2_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRFC2_CTRL_DDR   (0xD042) //Trfc2 Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRFC2_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRFC2_DDR   (0xD043) //Trfc2
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRFC_SB_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRFC_SB_CTRL_DDR   (0xD044) //TrfcSb Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRFC_SB_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRFC_SB_DDR   (0xD045) //TrfcSb
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRTP_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRTP_CTRL_DDR   (0xD046) //Trtp Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRTP_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRTP_DDR   (0xD047) //Trtp
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRRD_L_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRRD_L_CTRL_DDR   (0xD048) //TrrdL Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRRD_L_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRRD_L_DDR   (0xD049) //TrrdL
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRRD_S_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRRD_S_CTRL_DDR   (0xD04A) //TrrdS Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRRD_S_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRRD_S_DDR   (0xD04B) //TrrdS
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TFAW_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TFAW_CTRL_DDR   (0xD04C) //Tfaw Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TFAW_DDR
  #define IDSNVID_CMN_MEM_TIMING_TFAW_DDR   (0xD04D) //Tfaw
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWTR_L_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TWTR_L_CTRL_DDR   (0xD04E) //TwtrL Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWTR_L_DDR
  #define IDSNVID_CMN_MEM_TIMING_TWTR_L_DDR   (0xD04F) //TwtrL
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWTR_S_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TWTR_S_CTRL_DDR   (0xD050) //TwtrS Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWTR_S_DDR
  #define IDSNVID_CMN_MEM_TIMING_TWTR_S_DDR   (0xD051) //TwtrS
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRDRD_SC_L_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRDRD_SC_L_CTRL_DDR   (0xD052) //TrdrdScL Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRDRD_SC_L_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRDRD_SC_L_DDR   (0xD053) //TrdrdScL
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRDRD_SC_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRDRD_SC_CTRL_DDR   (0xD054) //TrdrdSc Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRDRD_SC_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRDRD_SC_DDR   (0xD055) //TrdrdSc
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRDRD_SD_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRDRD_SD_CTRL_DDR   (0xD056) //TrdrdSd Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRDRD_SD_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRDRD_SD_DDR   (0xD057) //TrdrdSd
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRDRD_DD_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRDRD_DD_CTRL_DDR   (0xD058) //TrdrdDd Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRDRD_DD_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRDRD_DD_DDR   (0xD059) //TrdrdDd
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWRWR_SC_L_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TWRWR_SC_L_CTRL_DDR   (0xD05A) //TwrwrScL Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWRWR_SC_L_DDR
  #define IDSNVID_CMN_MEM_TIMING_TWRWR_SC_L_DDR   (0xD05B) //TwrwrScL
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWRWR_SC_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TWRWR_SC_CTRL_DDR   (0xD05C) //TwrwrSc Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWRWR_SC_DDR
  #define IDSNVID_CMN_MEM_TIMING_TWRWR_SC_DDR   (0xD05D) //TwrwrSc
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWRWR_SD_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TWRWR_SD_CTRL_DDR   (0xD05E) //TwrwrSd Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWRWR_SD_DDR
  #define IDSNVID_CMN_MEM_TIMING_TWRWR_SD_DDR   (0xD05F) //TwrwrSd
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWRWR_DD_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TWRWR_DD_CTRL_DDR   (0xD060) //TwrwrDd Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWRWR_DD_DDR
  #define IDSNVID_CMN_MEM_TIMING_TWRWR_DD_DDR   (0xD061) //TwrwrDd
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWRRD_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TWRRD_CTRL_DDR   (0xD062) //Twrrd Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWRRD_DDR
  #define IDSNVID_CMN_MEM_TIMING_TWRRD_DDR   (0xD063) //Twrrd
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRDWR_CTRL_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRDWR_CTRL_DDR   (0xD064) //Trdwr Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRDWR_DDR
  #define IDSNVID_CMN_MEM_TIMING_TRDWR_DDR   (0xD065) //Trdwr
#endif

#ifndef IDSNVID_CMN_MEM_DRV_STREN_CA_DDR
  #define IDSNVID_CMN_MEM_DRV_STREN_CA_DDR   (0xD066) //Processor CA drive strengths
#endif

#ifndef IDSNVID_CMN_MEM_DRV_STREN_CS_DDR
  #define IDSNVID_CMN_MEM_DRV_STREN_CS_DDR   (0xD067) //Processor CS drive strengths
#endif

#ifndef IDSNVID_CMN_MEM_DRV_STREN_CK_DDR
  #define IDSNVID_CMN_MEM_DRV_STREN_CK_DDR   (0xD068) //Processor CK drive strengths
#endif

#ifndef IDSNVID_CMN_MEM_DRV_STREN_DQ_DDR
  #define IDSNVID_CMN_MEM_DRV_STREN_DQ_DDR   (0xD069) //Processor DQ drive strengths
#endif

#ifndef IDSNVID_CMN_MEM_ODT_IMPED_PROC_DDR
  #define IDSNVID_CMN_MEM_ODT_IMPED_PROC_DDR   (0xD06A) //Processor ODT impedance
#endif

#ifndef IDSNVID_CMN_MEM_DRAM_DRV_STREN_DQ_DDR
  #define IDSNVID_CMN_MEM_DRAM_DRV_STREN_DQ_DDR   (0xD06B) //Dram DQ drive strengths
#endif

#ifndef IDSNVID_CMN_MEM_DRAM_ODT_IMPED_RTT_NOM_WR_DDR
  #define IDSNVID_CMN_MEM_DRAM_ODT_IMPED_RTT_NOM_WR_DDR   (0xD06C) //Dram ODT impedance RTT_NOM_WR
#endif

#ifndef IDSNVID_CMN_MEM_DRAM_ODT_IMPED_RTT_NOM_RD_DDR
  #define IDSNVID_CMN_MEM_DRAM_ODT_IMPED_RTT_NOM_RD_DDR   (0xD06D) //Dram ODT impedance RTT_NOM_RD
#endif

#ifndef IDSNVID_CMN_MEM_DRAM_ODT_IMPED_RTT_WR_DDR
  #define IDSNVID_CMN_MEM_DRAM_ODT_IMPED_RTT_WR_DDR   (0xD06E) //Dram ODT impedance RTT_WR
#endif

#ifndef IDSNVID_CMN_MEM_DRAM_ODT_IMPED_RTT_PARK_DDR
  #define IDSNVID_CMN_MEM_DRAM_ODT_IMPED_RTT_PARK_DDR   (0xD06F) //Dram ODT impedance RTT_PARK
#endif

#ifndef IDSNVID_CMN_MEM_DRAM_ODT_IMPED_RTT_PARK_DQS_DDR
  #define IDSNVID_CMN_MEM_DRAM_ODT_IMPED_RTT_PARK_DQS_DDR   (0xD070) //Dram ODT impedance DQS_RTT_PARK
#endif

#ifndef IDSNVID_CMN_MEM_CTRLLER_POWER_DOWN_EN_DDR
  #define IDSNVID_CMN_MEM_CTRLLER_POWER_DOWN_EN_DDR   (0xD071) //Power Down Enable
#endif

#ifndef IDSNVID_CMN_MEM_CTRLLER_PD_PHY_POWER_SAVE_DIS_DDR
  #define IDSNVID_CMN_MEM_CTRLLER_PD_PHY_POWER_SAVE_DIS_DDR   (0xD072) //Phy Low Power Disable
#endif

#ifndef IDSNVID_CMN_MEM_ECC_DIS_ERR_INJECTION_DDR
  #define IDSNVID_CMN_MEM_ECC_DIS_ERR_INJECTION_DDR   (0xD073) //Disable Memory Error Injection
#endif

#ifndef IDSNVID_CMN_MEM_DATA_POISONING_DDR4
  #define IDSNVID_CMN_MEM_DATA_POISONING_DDR4   (0xD074) //Data Poisoning
#endif

#ifndef IDSNVID_CMN_MEM_ECC_EN_DDR
  #define IDSNVID_CMN_MEM_ECC_EN_DDR   (0xD075) //ECC
#endif

#ifndef IDSNVID_CMN_MEM_DRAM_REDIRECT_SCRUB_EN_DDR
  #define IDSNVID_CMN_MEM_DRAM_REDIRECT_SCRUB_EN_DDR   (0xD076) //DRAM Redirect Scrubber Enable
#endif

#ifndef IDSNVID_CMN_MEM_DRAM_REDIRECT_SCRUB_LIMIT_DDR
  #define IDSNVID_CMN_MEM_DRAM_REDIRECT_SCRUB_LIMIT_DDR   (0xD077) //DRAM Scrub Redirection Limit
#endif

#ifndef IDSNVID_CMN_MEM_DRAM_SCRUB_TIME
  #define IDSNVID_CMN_MEM_DRAM_SCRUB_TIME   (0xD078) //DRAM Scrub Time
#endif

#ifndef IDSNVID_CMN_MEM_TSME_ENABLE_DDR
  #define IDSNVID_CMN_MEM_TSME_ENABLE_DDR   (0xD079) //TSME
#endif

#ifndef IDSNVID_CMN_MEM_DATA_CTRL_DATA_SCRAMBLE_EN_DDR
  #define IDSNVID_CMN_MEM_DATA_CTRL_DATA_SCRAMBLE_EN_DDR   (0xD07A) //Data Scramble
#endif

#ifndef IDSNVID_CMN_MEM_SPD_CRC_VERIFY
  #define IDSNVID_CMN_MEM_SPD_CRC_VERIFY   (0xD07B) //Enable SPD CRC verification
#endif

#ifndef IDSNVID_CMN_MEM_SPD_READ_RETRY_COUNT_CRC
  #define IDSNVID_CMN_MEM_SPD_READ_RETRY_COUNT_CRC   (0xD07C) //SPD read retry count on CRC failure
#endif

#ifndef IDSNVID_CMN_MEM_MAPPING_BANK_INTERLEAVE_DDR
  #define IDSNVID_CMN_MEM_MAPPING_BANK_INTERLEAVE_DDR   (0xD07D) //Chipselect Interleaving
#endif

#ifndef IDSNVID_CMN_MEM_ADDRESS_HASH_BANK_DDR
  #define IDSNVID_CMN_MEM_ADDRESS_HASH_BANK_DDR   (0xD07E) //Address Hash Bank
#endif

#ifndef IDSNVID_CMN_MEM_ADDRESS_HASH_CS_DDR
  #define IDSNVID_CMN_MEM_ADDRESS_HASH_CS_DDR   (0xD07F) //Address Hash CS
#endif

#ifndef IDSNVID_CMN_MEM_CTRLLER_BANK_SWAP_MODE_DDR
  #define IDSNVID_CMN_MEM_CTRLLER_BANK_SWAP_MODE_DDR   (0xD080) //BankSwapMode
#endif

#ifndef IDSNVID_CMN_MEM_RESTORE_VALID_DAYS
  #define IDSNVID_CMN_MEM_RESTORE_VALID_DAYS   (0xD081) //Memory Restore valid days
#endif

#ifndef IDSNVID_CMN_MEM_CTRLLER_PMU_TRAIN_DFE_DDR
  #define IDSNVID_CMN_MEM_CTRLLER_PMU_TRAIN_DFE_DDR   (0xD082) //DFE Read Training
#endif

#ifndef IDSNVID_CMN_MEM_DRAM_PDA_ENUM_ID_PROG_MODE_DDR
  #define IDSNVID_CMN_MEM_DRAM_PDA_ENUM_ID_PROG_MODE_DDR   (0xD083) //DRAM PDA Enumerate ID Programming Mode
#endif

#ifndef IDSNVID_CMN_MEM_MBIST_EN_DDR
  #define IDSNVID_CMN_MEM_MBIST_EN_DDR   (0xD084) //MBIST Enable
#endif

#ifndef IDSNVID_CMN_MEM_MBIST_TESTMODE_DDR
  #define IDSNVID_CMN_MEM_MBIST_TESTMODE_DDR   (0xD085) //MBIST Test Mode
#endif

#ifndef IDSNVID_CMN_MEM_MBIST_AGGRESSORS_DDR
  #define IDSNVID_CMN_MEM_MBIST_AGGRESSORS_DDR   (0xD086) //MBIST Aggressors
#endif

#ifndef IDSNVID_CMN_MEM_MBIST_PER_BIT_SLAVE_DIE_REPORT_DDR
  #define IDSNVID_CMN_MEM_MBIST_PER_BIT_SLAVE_DIE_REPORT_DDR   (0xD087) //MBIST Per Bit Slave Die Reporting
#endif

#ifndef IDSNVID_CMN_MEM_MBIST_PATTERN_SELECT_DDR
  #define IDSNVID_CMN_MEM_MBIST_PATTERN_SELECT_DDR   (0xD088) //Pattern Select
#endif

#ifndef IDSNVID_CMN_MEM_MBIST_PATTERN_LENGTH_DDR
  #define IDSNVID_CMN_MEM_MBIST_PATTERN_LENGTH_DDR   (0xD089) //Pattern Length
#endif

#ifndef IDSNVID_CMN_MEM_MBIST_AGGRESSORS_CHNL_DDR
  #define IDSNVID_CMN_MEM_MBIST_AGGRESSORS_CHNL_DDR   (0xD08A) //Aggressor Channel
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_LEGAL_DISCLAIMER
  #define IDSNVID_CMN_MEM_TIMING_LEGAL_DISCLAIMER   (0xD08B) //DRAM Timing Configuration Legal Disclaimer
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_LEGAL_DISCLAIMER1
  #define IDSNVID_CMN_MEM_TIMING_LEGAL_DISCLAIMER1   (0xD08C) //DRAM Timing Configuration Legal Disclaimer 1
#endif

#ifndef IDSNVID_CMN_MEM_OVERCLOCK_LPDDR
  #define IDSNVID_CMN_MEM_OVERCLOCK_LPDDR   (0xD08D) //Active Memory Timing Settings
#endif

#ifndef IDSNVID_CMN_MEM_SPEED_LPDDR
  #define IDSNVID_CMN_MEM_SPEED_LPDDR   (0xD08E) //Maximum Memory Data Clock Speed
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRCPAGE_CTRL_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TRCPAGE_CTRL_LPDDR   (0xD08F) //Trcpage Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRCPAGE_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TRCPAGE_LPDDR   (0xD090) //Trcpage
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TCWL_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TCWL_LPDDR   (0xD091) //Tcwl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TCL_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TCL_LPDDR   (0xD092) //Tcl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRCDRD_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TRCDRD_LPDDR   (0xD093) //Trcdrd
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRCDWR_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TRCDWR_LPDDR   (0xD094) //Trcdwr
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRP_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TRP_LPDDR   (0xD095) //Trp
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRFC_CTRL_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TRFC_CTRL_LPDDR   (0xD096) //Trfc Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRFC_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TRFC_LPDDR   (0xD097) //Trfc
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRAS_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TRAS_LPDDR   (0xD098) //Tras
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRC_CTRL_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TRC_CTRL_LPDDR   (0xD099) //Trc Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRC_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TRC_LPDDR   (0xD09A) //Trc
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRRD_S_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TRRD_S_LPDDR   (0xD09B) //TrrdS
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRRD_L_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TRRD_L_LPDDR   (0xD09C) //TrrdL
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TFAW_CTRL_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TFAW_CTRL_LPDDR   (0xD09D) //Tfaw Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TFAW_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TFAW_LPDDR   (0xD09E) //Tfaw
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWTR_S_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TWTR_S_LPDDR   (0xD09F) //TwtrS
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWTR_L_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TWTR_L_LPDDR   (0xD0A0) //TwtrL
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWR_CTRL_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TWR_CTRL_LPDDR   (0xD0A1) //Twr Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWR_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TWR_LPDDR   (0xD0A2) //Twr
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRDRD_SC_L_CTRL_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TRDRD_SC_L_CTRL_LPDDR   (0xD0A3) //TrdrdScL Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRDRD_SC_L_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TRDRD_SC_L_LPDDR   (0xD0A4) //TrdrdScL
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWRWR_SC_L_CTRL_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TWRWR_SC_L_CTRL_LPDDR   (0xD0A5) //TwrwrScL Ctrl
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWRWR_SC_L_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TWRWR_SC_L_LPDDR   (0xD0A6) //TwrwrScL
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRTP_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TRTP_LPDDR   (0xD0A7) //Trtp
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TCKE_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TCKE_LPDDR   (0xD0A8) //Tcke
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRDRD_SC_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TRDRD_SC_LPDDR   (0xD0A9) //TrdrdSc
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRDRD_DD_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TRDRD_DD_LPDDR   (0xD0AA) //TrdrdDd
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRDRD_SD_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TRDRD_SD_LPDDR   (0xD0AB) //TrdrdSd
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWRWR_SC_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TWRWR_SC_LPDDR   (0xD0AC) //TwrwrSc
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWRWR_SD_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TWRWR_SD_LPDDR   (0xD0AD) //TwrwrSd
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWRWR_DD_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TWRWR_DD_LPDDR   (0xD0AE) //TwrwrDd
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TWRRD_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TWRRD_LPDDR   (0xD0AF) //Twrrd
#endif

#ifndef IDSNVID_CMN_MEM_TIMING_TRDWR_LPDDR
  #define IDSNVID_CMN_MEM_TIMING_TRDWR_LPDDR   (0xD0B0) //Trdwr
#endif

#ifndef IDSNVID_CMN_MEM_REF_MODE_LPDDR
  #define IDSNVID_CMN_MEM_REF_MODE_LPDDR   (0xD0B1) //LPDDR Refresh Mode
#endif

#ifndef IDSNVID_CMN_MEM_RFM_EN_LPDDR
  #define IDSNVID_CMN_MEM_RFM_EN_LPDDR   (0xD0B2) //LPDDR RFM
#endif

#ifndef IDSNVID_CMN_MEM_WCK_ALWAYS_ON_EN_LPDDR
  #define IDSNVID_CMN_MEM_WCK_ALWAYS_ON_EN_LPDDR   (0xD0B3) //WCK Always On
#endif

#ifndef IDSNVID_CMN_MEM_RRW_MEMTEST_CTRL_LPDDR
  #define IDSNVID_CMN_MEM_RRW_MEMTEST_CTRL_LPDDR   (0xD0B4) //RRW Memory Test Control
#endif

#ifndef IDSNVID_CMN_MEM_CTRLLER_PWR_DN_EN_LPDDR
  #define IDSNVID_CMN_MEM_CTRLLER_PWR_DN_EN_LPDDR   (0xD0B5) //Power Down Enable
#endif

#ifndef IDSNVID_CMN_MEM_CTRLLER_PD_PHY_POWER_SAVE_DIS_LPDDR
  #define IDSNVID_CMN_MEM_CTRLLER_PD_PHY_POWER_SAVE_DIS_LPDDR   (0xD0B6) //Phy Low Power Disable
#endif

#ifndef IDSNVID_CMN_MEM_CAD_BUS_TIMING_CTL_LPDDR
  #define IDSNVID_CMN_MEM_CAD_BUS_TIMING_CTL_LPDDR   (0xD0B7) //CAD Bus Timing User Controls
#endif

#ifndef IDSNVID_CMN_MEM_ADDR_CMD_SETUP_LPDDR
  #define IDSNVID_CMN_MEM_ADDR_CMD_SETUP_LPDDR   (0xD0B8) //AddrCmdSetup
#endif

#ifndef IDSNVID_CMN_MEM_CS_ODT_SETUP_LPDDR
  #define IDSNVID_CMN_MEM_CS_ODT_SETUP_LPDDR   (0xD0B9) //CsOdtSetup
#endif

#ifndef IDSNVID_CMN_MEM_PHY_IO_DRV_STREN_CA_LPDDR
  #define IDSNVID_CMN_MEM_PHY_IO_DRV_STREN_CA_LPDDR   (0xD0BA) //CA drive strengths
#endif

#ifndef IDSNVID_CMN_MEM_PHY_IO_DRV_STREN_CS_LPDDR
  #define IDSNVID_CMN_MEM_PHY_IO_DRV_STREN_CS_LPDDR   (0xD0BB) //CS drive strengths
#endif

#ifndef IDSNVID_CMN_MEM_PHY_IO_DRV_STREN_CK_LPDDR
  #define IDSNVID_CMN_MEM_PHY_IO_DRV_STREN_CK_LPDDR   (0xD0BC) //CK drive strengths
#endif

#ifndef IDSNVID_CMN_MEM_PHY_IO_DRV_STREN_WCK_LPDDR
  #define IDSNVID_CMN_MEM_PHY_IO_DRV_STREN_WCK_LPDDR   (0xD0BD) //WCK drive strengths
#endif

#ifndef IDSNVID_CMN_MEM_PHY_IO_DRV_STREN_DQ_LPDDR
  #define IDSNVID_CMN_MEM_PHY_IO_DRV_STREN_DQ_LPDDR   (0xD0BE) //DQ drive strengths
#endif

#ifndef IDSNVID_CMN_MEM_PHY_IO_DRV_STREN_DQS_LPDDR
  #define IDSNVID_CMN_MEM_PHY_IO_DRV_STREN_DQS_LPDDR   (0xD0BF) //DQS drive strengths
#endif

#ifndef IDSNVID_CMN_MEM_PHY_IO_ODT_STREN_PROC_LPDDR
  #define IDSNVID_CMN_MEM_PHY_IO_ODT_STREN_PROC_LPDDR   (0xD0C0) //Processor ODT impedance
#endif

#ifndef IDSNVID_CMN_MEM_PHY_IO_ODT_STREN_PROC_CA_LPDDR
  #define IDSNVID_CMN_MEM_PHY_IO_ODT_STREN_PROC_CA_LPDDR   (0xD0C1) //Processor CA ODT impedance
#endif

#ifndef IDSNVID_CMN_MEM_PHY_IO_ODT_STREN_PROC_CK_LPDDR
  #define IDSNVID_CMN_MEM_PHY_IO_ODT_STREN_PROC_CK_LPDDR   (0xD0C2) //Processor CK ODT impedance
#endif

#ifndef IDSNVID_CMN_MEM_PHY_IO_ODT_STREN_PROC_WCK_LPDDR
  #define IDSNVID_CMN_MEM_PHY_IO_ODT_STREN_PROC_WCK_LPDDR   (0xD0C3) //Processor WCK ODT impedance
#endif

#ifndef IDSNVID_CMN_MEM_DRAM_IO_ODT_STREN_CA_LPDDR
  #define IDSNVID_CMN_MEM_DRAM_IO_ODT_STREN_CA_LPDDR   (0xD0C4) //Dram CA ODT impedance
#endif

#ifndef IDSNVID_CMN_MEM_DRAM_IO_ODT_STREN_DQ_LPDDR
  #define IDSNVID_CMN_MEM_DRAM_IO_ODT_STREN_DQ_LPDDR   (0xD0C5) //Dram DQ ODT impedance
#endif

#ifndef IDSNVID_CMN_MEM_DRAM_IO_ODT_STREN_WCK_LPDDR
  #define IDSNVID_CMN_MEM_DRAM_IO_ODT_STREN_WCK_LPDDR   (0xD0C6) //Dram WCK ODT impedance
#endif

#ifndef IDSNVID_CMN_MEM_DRAM_IO_ODT_STREN_NTDQ
  #define IDSNVID_CMN_MEM_DRAM_IO_ODT_STREN_NTDQ   (0xD0C7) //Dram Non-Target ODT impedance
#endif

#ifndef IDSNVID_CMN_MEM_DRAM_IO_DRV_STREN_PDDS
  #define IDSNVID_CMN_MEM_DRAM_IO_DRV_STREN_PDDS   (0xD0C8) //Dram Pull-Down drive strengths
#endif

#ifndef IDSNVID_CMN_MEM_CTRLLER_DRAM_RD_LINK_ECC_EN_LPDDR
  #define IDSNVID_CMN_MEM_CTRLLER_DRAM_RD_LINK_ECC_EN_LPDDR   (0xD0C9) //DRAM Read Link ECC Enable
#endif

#ifndef IDSNVID_CMN_MEM_CTRLLER_DRAM_WR_LINK_ECC_EN_LPDDR
  #define IDSNVID_CMN_MEM_CTRLLER_DRAM_WR_LINK_ECC_EN_LPDDR   (0xD0CA) //DRAM Write Link ECC Enable
#endif

#ifndef IDSNVID_CMN_MEM_DIS_MEM_ERR_INJ_LPDDR
  #define IDSNVID_CMN_MEM_DIS_MEM_ERR_INJ_LPDDR   (0xD0CB) //Disable Memory Error Injection
#endif

#ifndef IDSNVID_CMN_MEM_TSME_LPDDR
  #define IDSNVID_CMN_MEM_TSME_LPDDR   (0xD0CC) //TSME
#endif

#ifndef IDSNVID_CMN_MEM_CTRLLER_DATA_SCRAMBLE_LPDDR
  #define IDSNVID_CMN_MEM_CTRLLER_DATA_SCRAMBLE_LPDDR   (0xD0CD) //Data Scramble
#endif

#ifndef IDSNVID_CMN_MEM_MAPPING_BANK_INTERLEAVE_LPDDR
  #define IDSNVID_CMN_MEM_MAPPING_BANK_INTERLEAVE_LPDDR   (0xD0CE) //Chip Select Interleaving
#endif

#ifndef IDSNVID_CMN_MEM_CTRLLER_BANK_SWAP_LPDDR
  #define IDSNVID_CMN_MEM_CTRLLER_BANK_SWAP_LPDDR   (0xD0CF) //Bank Swap
#endif

#ifndef IDSNVID_CMN_MEM_CTRLLER_BANK_GROUP_SWAP_LPDDR
  #define IDSNVID_CMN_MEM_CTRLLER_BANK_GROUP_SWAP_LPDDR   (0xD0D0) //BankGroup Swap
#endif

#ifndef IDSNVID_CMN_MEM_ADDRESS_HASH_BANK_LPDDR
  #define IDSNVID_CMN_MEM_ADDRESS_HASH_BANK_LPDDR   (0xD0D1) //Address Hash Bank
#endif

#ifndef IDSNVID_CMN_MEM_ADDRESS_HASH_CS_LPDDR
  #define IDSNVID_CMN_MEM_ADDRESS_HASH_CS_LPDDR   (0xD0D2) //Address Hash CS
#endif

#ifndef IDSNVID_CMN_MEM_CTRLLER_PMU_TRAIN_DFE_LPDDR
  #define IDSNVID_CMN_MEM_CTRLLER_PMU_TRAIN_DFE_LPDDR   (0xD0D3) //DFE Read Training
#endif

#ifndef IDSNVID_CMN_MEM_MBIST_EN_LPDDR
  #define IDSNVID_CMN_MEM_MBIST_EN_LPDDR   (0xD0D4) //MBIST Enable
#endif

#ifndef IDSNVID_CMN_MEM_MBIST_TESTMODE_LPDDR
  #define IDSNVID_CMN_MEM_MBIST_TESTMODE_LPDDR   (0xD0D5) //MBIST Test Mode
#endif

#ifndef IDSNVID_CMN_MEM_MBIST_AGGRESSORS_LPDDR
  #define IDSNVID_CMN_MEM_MBIST_AGGRESSORS_LPDDR   (0xD0D6) //MBIST Aggressors
#endif

#ifndef IDSNVID_CMN_MEM_MBIST_PATTERN_SELECT_LPDDR
  #define IDSNVID_CMN_MEM_MBIST_PATTERN_SELECT_LPDDR   (0xD0D7) //Pattern Select
#endif

#ifndef IDSNVID_CMN_MEM_MBIST_PATTERN_LENGTH_LPDDR
  #define IDSNVID_CMN_MEM_MBIST_PATTERN_LENGTH_LPDDR   (0xD0D8) //Pattern Length
#endif

#ifndef IDSNVID_CMN_MEM_MBIST_AGGRESSORS_CHNL_LPDDR
  #define IDSNVID_CMN_MEM_MBIST_AGGRESSORS_CHNL_LPDDR   (0xD0D9) //Aggressor Channel
#endif

#ifndef IDSNVID_CMN_MEM_MBIST_READ_DATA_EYE_VOLTAGE_STEP_LPDDR
  #define IDSNVID_CMN_MEM_MBIST_READ_DATA_EYE_VOLTAGE_STEP_LPDDR   (0xD0DA) //Read Voltage Sweep Step Size
#endif

#ifndef IDSNVID_CMN_MEM_MBIST_READ_DATA_EYE_TIMING_STEP_LPDDR
  #define IDSNVID_CMN_MEM_MBIST_READ_DATA_EYE_TIMING_STEP_LPDDR   (0xD0DB) //Read Timing Sweep Step Size
#endif

#ifndef IDSNVID_CMN_MEM_MBIST_WRITE_DATA_EYE_VOLTAGE_STEP_LPDDR
  #define IDSNVID_CMN_MEM_MBIST_WRITE_DATA_EYE_VOLTAGE_STEP_LPDDR   (0xD0DC) //Write Voltage Sweep Step Size
#endif

#ifndef IDSNVID_CMN_MEM_MBIST_WRITE_DATA_EYE_TIMING_STEP_LPDDR
  #define IDSNVID_CMN_MEM_MBIST_WRITE_DATA_EYE_TIMING_STEP_LPDDR   (0xD0DD) //Write Timing Sweep Step Size
#endif

#ifndef IDSNVID_CMN_GNB_NB_IOMMU
  #define IDSNVID_CMN_GNB_NB_IOMMU   (0xD0DE) //IOMMU
#endif

#ifndef IDSNVID_CMN_DMAR_SUPPORT
  #define IDSNVID_CMN_DMAR_SUPPORT   (0xD0DF) //DMAr Support
#endif

#ifndef IDSNVID_CMN_DMA_PROTECTION
  #define IDSNVID_CMN_DMA_PROTECTION   (0xD0E0) //DMA Protection
#endif

#ifndef IDSNVID_CMN_SCPC_ATTR_CNTL
  #define IDSNVID_CMN_SCPC_ATTR_CNTL   (0xD0E1) //SCPC attribute control
#endif

#ifndef IDSNVID_CMN_GNB_PCIE_ARI_SUPPORT
  #define IDSNVID_CMN_GNB_PCIE_ARI_SUPPORT   (0xD0E2) //PCIe ARI Support
#endif

#ifndef IDSNVID_GNB_CMN_PCIE_ARI_ENUMERATION
  #define IDSNVID_GNB_CMN_PCIE_ARI_ENUMERATION   (0xD0E3) //PCIe ARI Enumeration
#endif

#ifndef IDSNVID_DBG_GNB_DBG_AERCAP_ENABLE
  #define IDSNVID_DBG_GNB_DBG_AERCAP_ENABLE   (0xD0E4) //Enable AER Cap
#endif

#ifndef IDSNVID_DBG_GNB_DBG_ACS_ENABLE
  #define IDSNVID_DBG_GNB_DBG_ACS_ENABLE   (0xD0E5) //ACS Enable
#endif

#ifndef IDSNVID_CMN_GNB_PCIE_PSPP_POLICY
  #define IDSNVID_CMN_GNB_PCIE_PSPP_POLICY   (0xD0E6) //PSPP Policy
#endif

#ifndef IDSNVID_CMN_PCIE_PORT_ALL_PORTS
  #define IDSNVID_CMN_PCIE_PORT_ALL_PORTS   (0xD0E7) //PCIe All Ports Settings
#endif

#ifndef IDSNVID_CMN_RAS_CONTROL
  #define IDSNVID_CMN_RAS_CONTROL   (0xD0E8) //NBIO RAS Control
#endif

#ifndef IDSNVID_PCD_EGRESS_POISON_SEVERITY_HI
  #define IDSNVID_PCD_EGRESS_POISON_SEVERITY_HI   (0xD0E9) //Egress Poison Severity High
#endif

#ifndef IDSNVID_PCD_EGRESS_POISON_SEVERITY_LO
  #define IDSNVID_PCD_EGRESS_POISON_SEVERITY_LO   (0xD0EA) //Egress Poison Severity Low
#endif

#ifndef IDSNVID_CMN_NBIO_SYNC_FLOOD_GEN
  #define IDSNVID_CMN_NBIO_SYNC_FLOOD_GEN   (0xD0EB) //NBIO SyncFlood Generation
#endif

#ifndef IDSNVID_PCD_SYNC_FLOOD_TO_APML
  #define IDSNVID_PCD_SYNC_FLOOD_TO_APML   (0xD0EC) //NBIO SyncFlood Reporting
#endif

#ifndef IDSNVID_PCD_AMD_NBIO_EGRESS_POISON_MASK_HI
  #define IDSNVID_PCD_AMD_NBIO_EGRESS_POISON_MASK_HI   (0xD0ED) //Egress Poison Mask High
#endif

#ifndef IDSNVID_PCD_AMD_NBIO_EGRESS_POISON_MASK_LO
  #define IDSNVID_PCD_AMD_NBIO_EGRESS_POISON_MASK_LO   (0xD0EE) //Egress Poison Mask Low
#endif

#ifndef IDSNVID_PCD_AMD_NBIO_RAS_UCP_MASK_HI
  #define IDSNVID_PCD_AMD_NBIO_RAS_UCP_MASK_HI   (0xD0EF) //Uncorrected Converted to Poison Enable Mask High
#endif

#ifndef IDSNVID_PCD_AMD_NBIO_RAS_UCP_MASK_LO
  #define IDSNVID_PCD_AMD_NBIO_RAS_UCP_MASK_LO   (0xD0F0) //Uncorrected Converted to Poison Enable Mask Low
#endif

#ifndef IDSNVID_PCD_SYSHUB_WDT_TIMER_INTERVAL
  #define IDSNVID_PCD_SYSHUB_WDT_TIMER_INTERVAL   (0xD0F1) //System Hub Watchdog Timer
#endif

#ifndef IDSNVID_DBG_POISON_CONSUMPTION
  #define IDSNVID_DBG_POISON_CONSUMPTION   (0xD0F2) //NBIO Poison Consumption
#endif

#ifndef IDSNVID_CMN_GNB_GFX_UMA_MODE
  #define IDSNVID_CMN_GNB_GFX_UMA_MODE   (0xD0F3) //iGPU Configuration
#endif

#ifndef IDSNVID_CMN_GNB_GFX_UMA_VERSION
  #define IDSNVID_CMN_GNB_GFX_UMA_VERSION   (0xD0F4) //UMA Version
#endif

#ifndef IDSNVID_CMN_GNB_GFX_UMA_FRAME_BUFFER_SIZE
  #define IDSNVID_CMN_GNB_GFX_UMA_FRAME_BUFFER_SIZE   (0xD0F5) //UMA Frame buffer Size
#endif

#ifndef IDSNVID_CMN_GPU_HOST_TRANSLATION
  #define IDSNVID_CMN_GPU_HOST_TRANSLATION   (0xD0F6) //GPU Host Translation Cache
#endif

#ifndef IDSNVID_CMN_GNB_GFX_NB_AZALIA
  #define IDSNVID_CMN_GNB_GFX_NB_AZALIA   (0xD0F7) //NB Azalia
#endif

#ifndef IDSNVID_DBG_GNB_AUDIO_I_OS
  #define IDSNVID_DBG_GNB_AUDIO_I_OS   (0xD0F8) //Audio IOs
#endif

#ifndef IDSNVID_CMN_PCIE_ALL_PORTS_CAPASPM
  #define IDSNVID_CMN_PCIE_ALL_PORTS_CAPASPM   (0xD0F9) //ASPM
#endif

#ifndef IDSNVID_CMN_PCIE_ALL_PORTS_CAPPM_L1_SS
  #define IDSNVID_CMN_PCIE_ALL_PORTS_CAPPM_L1_SS   (0xD0FA) //L1 PM SubState
#endif

#ifndef IDSNVID_CMN_PCIE_ALL_PORTS_CAPLTR
  #define IDSNVID_CMN_PCIE_ALL_PORTS_CAPLTR   (0xD0FB) //LTR Support
#endif

#ifndef IDSNVID_CMN_PCIE_ALL_PORTS_PM_LINK_ASPM
  #define IDSNVID_CMN_PCIE_ALL_PORTS_PM_LINK_ASPM   (0xD0FC) //ASPM
#endif

#ifndef IDSNVID_CMN_PCIE_ALL_PORTS_PM_L1_SS
  #define IDSNVID_CMN_PCIE_ALL_PORTS_PM_L1_SS   (0xD0FD) //L1 PM SubState
#endif

#ifndef IDSNVID_CMN_PCIE_CORE_LCLK_GATING
  #define IDSNVID_CMN_PCIE_CORE_LCLK_GATING   (0xD0FE) //LCLK Gating
#endif

#ifndef IDSNVID_CMN_PCIE_CORE_DYNAMIC_POWER_GATING
  #define IDSNVID_CMN_PCIE_CORE_DYNAMIC_POWER_GATING   (0xD0FF) //PCIe Dynamic PG
#endif

#ifndef IDSNVID_CMN_NBIO_GLOBAL_CG_OVERRIDE
  #define IDSNVID_CMN_NBIO_GLOBAL_CG_OVERRIDE   (0xD100) //NBIO Global CG Override
#endif

#ifndef IDSNVID_CMN_GNB_PMM_IOHC_LCLK_GATING
  #define IDSNVID_CMN_GNB_PMM_IOHC_LCLK_GATING   (0xD101) //IOHC LCLK Clock Gating
#endif

#ifndef IDSNVID_CMN_GNB_NB_IOHC_POWER_GATING
  #define IDSNVID_CMN_GNB_NB_IOHC_POWER_GATING   (0xD102) //IOHC Power Gating
#endif

#ifndef IDSNVID_CMN_GNB_NB_IOMMU_L1_CLOCK_GATING
  #define IDSNVID_CMN_GNB_NB_IOMMU_L1_CLOCK_GATING   (0xD103) //IOMMU L1 Clock Gating
#endif

#ifndef IDSNVID_CMN_GNB_NB_IOMMU_L2_CLOCK_GATING
  #define IDSNVID_CMN_GNB_NB_IOMMU_L2_CLOCK_GATING   (0xD104) //IOMMU L2 Clock Gating
#endif

#ifndef IDSNVID_CMN_GNB_NB_IOMMU_DYNAMIC_PG
  #define IDSNVID_CMN_GNB_NB_IOMMU_DYNAMIC_PG   (0xD105) //IOMMU Dynamic Power Gating
#endif

#ifndef IDSNVID_CMN_GNB_NB_IOMMU_L2_MEMORY_PG
  #define IDSNVID_CMN_GNB_NB_IOMMU_L2_MEMORY_PG   (0xD106) //IOMMU L2 Memory Power Gating
#endif

#ifndef IDSNVID_CMN_NBIO_NBIF_PG
  #define IDSNVID_CMN_NBIO_NBIF_PG   (0xD107) //NBIF PG
#endif

#ifndef IDSNVID_CMN_NBIO_SHUB_PG
  #define IDSNVID_CMN_NBIO_SHUB_PG   (0xD108) //SHUB PG
#endif

#ifndef IDSNVID_CMN_PMM_MMHUB_SRAM_LS
  #define IDSNVID_CMN_PMM_MMHUB_SRAM_LS   (0xD109) //MMHUB SRAM Light Sleep
#endif

#ifndef IDSNVID_CMN_PMM_NBIF_INTR_OBFF
  #define IDSNVID_CMN_PMM_NBIF_INTR_OBFF   (0xD10A) //NBIF INTR OBFF
#endif

#ifndef IDSNVID_CMN_PMM_NBIF_DMA_OBFF
  #define IDSNVID_CMN_PMM_NBIF_DMA_OBFF   (0xD10B) //NBIF DMA OBFF
#endif

#ifndef IDSNVID_CMN_FCH_I3_C0_CONFIG
  #define IDSNVID_CMN_FCH_I3_C0_CONFIG   (0xD10C) //I3C/I2C 0 Enable
#endif

#ifndef IDSNVID_CMN_FCH_I3_C0_MODE
  #define IDSNVID_CMN_FCH_I3_C0_MODE   (0xD10D) //I3C 0 Mode
#endif

#ifndef IDSNVID_CMN_FCH_I3_C1_CONFIG
  #define IDSNVID_CMN_FCH_I3_C1_CONFIG   (0xD10E) //I3C/I2C 1 Enable
#endif

#ifndef IDSNVID_CMN_FCH_I3_C1_MODE
  #define IDSNVID_CMN_FCH_I3_C1_MODE   (0xD10F) //I3C 1 Mode
#endif

#ifndef IDSNVID_CMN_FCH_I3_C2_CONFIG
  #define IDSNVID_CMN_FCH_I3_C2_CONFIG   (0xD110) //I3C/I2C 2 Enable
#endif

#ifndef IDSNVID_CMN_FCH_I3_C2_MODE
  #define IDSNVID_CMN_FCH_I3_C2_MODE   (0xD111) //I3C 2 Mode
#endif

#ifndef IDSNVID_CMN_FCH_I3_C3_CONFIG
  #define IDSNVID_CMN_FCH_I3_C3_CONFIG   (0xD112) //I3C/I2C 3 Enable
#endif

#ifndef IDSNVID_CMN_FCH_I3_C3_MODE
  #define IDSNVID_CMN_FCH_I3_C3_MODE   (0xD113) //I3C 3 Mode
#endif

#ifndef IDSNVID_CMN_FCH_SATA_ENABLE
  #define IDSNVID_CMN_FCH_SATA_ENABLE   (0xD114) //SATA Controller
#endif

#ifndef IDSNVID_CMN_FCH_SATA_AUTO_SHUT_DOWN
  #define IDSNVID_CMN_FCH_SATA_AUTO_SHUT_DOWN   (0xD115) //SATA Auto Shutdown
#endif

#ifndef IDSNVID_CMN_FCH_SATA_CLASS
  #define IDSNVID_CMN_FCH_SATA_CLASS   (0xD116) //SATA Mode
#endif

#ifndef IDSNVID_CMN_FCH_SATA_RAS_SUPPORT
  #define IDSNVID_CMN_FCH_SATA_RAS_SUPPORT   (0xD117) //Sata RAS Support
#endif

#ifndef IDSNVID_CMN_FCH_SATA_AHCI_DIS_PREFETCH_FUNCTION
  #define IDSNVID_CMN_FCH_SATA_AHCI_DIS_PREFETCH_FUNCTION   (0xD118) //Sata Disabled AHCI Prefetch Function
#endif

#ifndef IDSNVID_DBG_FCH_SATA_AGGRESIVE_DEV_SLP_P0
  #define IDSNVID_DBG_FCH_SATA_AGGRESIVE_DEV_SLP_P0   (0xD119) //Aggresive SATA Device Sleep Port 0
#endif

#ifndef IDSNVID_DBG_FCH_SATA_DEV_SLP_PORT0_NUM
  #define IDSNVID_DBG_FCH_SATA_DEV_SLP_PORT0_NUM   (0xD11A) //DevSleep0 Port Number
#endif

#ifndef IDSNVID_DBG_FCH_SATA_AGGRESIVE_DEV_SLP_P1
  #define IDSNVID_DBG_FCH_SATA_AGGRESIVE_DEV_SLP_P1   (0xD11B) //Aggresive SATA Device Sleep Port 1
#endif

#ifndef IDSNVID_DBG_FCH_SATA_DEV_SLP_PORT1_NUM
  #define IDSNVID_DBG_FCH_SATA_DEV_SLP_PORT1_NUM   (0xD11C) //DevSleep1 Port Number
#endif

#ifndef IDSNVID_CMN_FCH_USB_XHC_I0_ENABLE
  #define IDSNVID_CMN_FCH_USB_XHC_I0_ENABLE   (0xD11D) //USB0 controller enable
#endif

#ifndef IDSNVID_CMN_FCH_USB_XHC_I1_ENABLE
  #define IDSNVID_CMN_FCH_USB_XHC_I1_ENABLE   (0xD11E) //USB1 controller enable
#endif

#ifndef IDSNVID_CMN_FCH_USB_XHC_I2_ENABLE
  #define IDSNVID_CMN_FCH_USB_XHC_I2_ENABLE   (0xD11F) //USB2 controller enable
#endif

#ifndef IDSNVID_CMN_FCH_USB_XHC_I0_HS_PORT0
  #define IDSNVID_CMN_FCH_USB_XHC_I0_HS_PORT0   (0xD120) //USB0 2.0 Port 0
#endif

#ifndef IDSNVID_CMN_FCH_USB_XHC_I0_HS_PORT1
  #define IDSNVID_CMN_FCH_USB_XHC_I0_HS_PORT1   (0xD121) //USB0 2.0 Port 1
#endif

#ifndef IDSNVID_CMN_FCH_USB_XHC_I0_HS_PORT2
  #define IDSNVID_CMN_FCH_USB_XHC_I0_HS_PORT2   (0xD122) //USB0 2.0 Port 2
#endif

#ifndef IDSNVID_CMN_FCH_USB_XHC_I0_HS_PORT3
  #define IDSNVID_CMN_FCH_USB_XHC_I0_HS_PORT3   (0xD123) //USB0 2.0 Port 3
#endif

#ifndef IDSNVID_CMN_FCH_USB_XHC_I1_HS_PORT0
  #define IDSNVID_CMN_FCH_USB_XHC_I1_HS_PORT0   (0xD124) //USB1 2.0 Port 0
#endif

#ifndef IDSNVID_CMN_FCH_USB_XHC_I1_HS_PORT1
  #define IDSNVID_CMN_FCH_USB_XHC_I1_HS_PORT1   (0xD125) //USB1 2.0 Port 1
#endif

#ifndef IDSNVID_CMN_FCH_USB_XHC_I1_HS_PORT2
  #define IDSNVID_CMN_FCH_USB_XHC_I1_HS_PORT2   (0xD126) //USB1 2.0 Port 2
#endif

#ifndef IDSNVID_CMN_FCH_USB_XHC_I2_HS_PORT0
  #define IDSNVID_CMN_FCH_USB_XHC_I2_HS_PORT0   (0xD127) //USB2 2.0 Port 0
#endif

#ifndef IDSNVID_CMN_FCH_USB_XHC_I3_HS_PORT0
  #define IDSNVID_CMN_FCH_USB_XHC_I3_HS_PORT0   (0xD128) //USB3 2.0 port 0
#endif

#ifndef IDSNVID_CMN_FCH_USB_XHC_I4_HS_PORT0
  #define IDSNVID_CMN_FCH_USB_XHC_I4_HS_PORT0   (0xD129) //USB4 2.0 port0
#endif

#ifndef IDSNVID_CMN_FCH_USB_XHC_I0_SS_PORT0
  #define IDSNVID_CMN_FCH_USB_XHC_I0_SS_PORT0   (0xD12A) //USB0 3.1 Port 0
#endif

#ifndef IDSNVID_CMN_FCH_USB_XHC_I0_SS_PORT1
  #define IDSNVID_CMN_FCH_USB_XHC_I0_SS_PORT1   (0xD12B) //USB0 3.1 Port 1
#endif

#ifndef IDSNVID_CMN_FCH_USB_XHC_I1_SS_PORT0
  #define IDSNVID_CMN_FCH_USB_XHC_I1_SS_PORT0   (0xD12C) //USB1 3.1 Port 0
#endif

#ifndef IDSNVID_CMN_FCH_USB_XHC_I1_SS_PORT1
  #define IDSNVID_CMN_FCH_USB_XHC_I1_SS_PORT1   (0xD12D) //USB1 3.1 Port 1
#endif

#ifndef IDSNVID_CMN_FCH_USB_XHC_I3_SS_PORT0
  #define IDSNVID_CMN_FCH_USB_XHC_I3_SS_PORT0   (0xD12E) //USB3 3.1 Port 0
#endif

#ifndef IDSNVID_CMN_FCH_USB_XHC_I4_SS_PORT0
  #define IDSNVID_CMN_FCH_USB_XHC_I4_SS_PORT0   (0xD12F) //USB4 3.1 Port 0
#endif

#ifndef IDSNVID_CMN_FCH_SYSTEM_PWR_FAIL_SHADOW
  #define IDSNVID_CMN_FCH_SYSTEM_PWR_FAIL_SHADOW   (0xD130) //Ac Loss Control
#endif

#ifndef IDSNVID_CMN_FCH_UART0_CONFIG
  #define IDSNVID_CMN_FCH_UART0_CONFIG   (0xD131) //Uart 0 Enable
#endif

#ifndef IDSNVID_CMN_FCH_UART0_LEGACY_CONFIG
  #define IDSNVID_CMN_FCH_UART0_LEGACY_CONFIG   (0xD132) //Uart 0 Legacy Options
#endif

#ifndef IDSNVID_CMN_FCH_UART1_CONFIG
  #define IDSNVID_CMN_FCH_UART1_CONFIG   (0xD133) //Uart 1 Enable (no HW FC)
#endif

#ifndef IDSNVID_CMN_FCH_UART1_LEGACY_CONFIG
  #define IDSNVID_CMN_FCH_UART1_LEGACY_CONFIG   (0xD134) //Uart 1 Legacy Options
#endif

#ifndef IDSNVID_CMN_FCH_UART2_CONFIG
  #define IDSNVID_CMN_FCH_UART2_CONFIG   (0xD135) //Uart 2 Enable
#endif

#ifndef IDSNVID_CMN_FCH_UART2_LEGACY_CONFIG
  #define IDSNVID_CMN_FCH_UART2_LEGACY_CONFIG   (0xD136) //Uart 2 Legacy Options
#endif

#ifndef IDSNVID_CMN_FCH_UART3_CONFIG
  #define IDSNVID_CMN_FCH_UART3_CONFIG   (0xD137) //Uart 3 Enable (no HW FC)
#endif

#ifndef IDSNVID_CMN_FCH_UART3_LEGACY_CONFIG
  #define IDSNVID_CMN_FCH_UART3_LEGACY_CONFIG   (0xD138) //Uart 3 Legacy Options
#endif

#ifndef IDSNVID_CMN_FCH_UART4_CONFIG
  #define IDSNVID_CMN_FCH_UART4_CONFIG   (0xD139) //Uart 4 Enable
#endif

#ifndef IDSNVID_CMN_FCH_ESPI_CONFIG
  #define IDSNVID_CMN_FCH_ESPI_CONFIG   (0xD13A) //ESPI Enable
#endif

#ifndef IDSNVID_CMN_FCH_ESPI_CRC
  #define IDSNVID_CMN_FCH_ESPI_CRC   (0xD13B) //ESPI CRC Enable
#endif

#ifndef IDSNVID_CMN_FCH_XGBE0_ENABLE
  #define IDSNVID_CMN_FCH_XGBE0_ENABLE   (0xD13C) //XGBE0 enable
#endif

#ifndef IDSNVID_CMN_FCH_XGBE1_ENABLE
  #define IDSNVID_CMN_FCH_XGBE1_ENABLE   (0xD13D) //XGBE1 enable
#endif

#ifndef IDSNVID_CMN_FCH_XGBE_PORT0_LED1_GPIO
  #define IDSNVID_CMN_FCH_XGBE_PORT0_LED1_GPIO   (0xD13E) //XGBE Port0 LED1 GPIO
#endif

#ifndef IDSNVID_CMN_FCH_XGBE_PORT0_LED2_GPIO
  #define IDSNVID_CMN_FCH_XGBE_PORT0_LED2_GPIO   (0xD13F) //XGBE Port0 LED2 GPIO
#endif

#ifndef IDSNVID_CMN_FCH_XGBE_PORT1_LED1_GPIO
  #define IDSNVID_CMN_FCH_XGBE_PORT1_LED1_GPIO   (0xD140) //XGBE Port1 LED1 GPIO
#endif

#ifndef IDSNVID_CMN_FCH_XGBE_PORT1_LED2_GPIO
  #define IDSNVID_CMN_FCH_XGBE_PORT1_LED2_GPIO   (0xD141) //XGBE Port1 LED2 GPIO
#endif

#ifndef IDSNVID_CMN_FCH_CIO_PRE_CM_ENABLE
  #define IDSNVID_CMN_FCH_CIO_PRE_CM_ENABLE   (0xD142) //USB4 pre-CM Enable
#endif

#ifndef IDSNVID_CMN_FCH_CIO_RT0_ENABLE
  #define IDSNVID_CMN_FCH_CIO_RT0_ENABLE   (0xD143) //RT0 Router Enable
#endif

#ifndef IDSNVID_CMN_FCH_CIO_RT0_PCIE_TUNNEL
  #define IDSNVID_CMN_FCH_CIO_RT0_PCIE_TUNNEL   (0xD144) //RT0 PCIe Tunnel
#endif

#ifndef IDSNVID_CMN_FCH_CIO_RT1_ENABLE
  #define IDSNVID_CMN_FCH_CIO_RT1_ENABLE   (0xD145) //RT1 Router Enable
#endif

#ifndef IDSNVID_CMN_FCH_CIO_RT1_PCIE_TUNNEL
  #define IDSNVID_CMN_FCH_CIO_RT1_PCIE_TUNNEL   (0xD146) //RT1 PCIe Tunnel
#endif

#ifndef IDSNVID_CMN_FCH_HFP_CONFIG
  #define IDSNVID_CMN_FCH_HFP_CONFIG   (0xD147) //HFP Enable
#endif

#ifndef IDSNVID_CMN_FCH_HID_CONFIG
  #define IDSNVID_CMN_FCH_HID_CONFIG   (0xD148) //HID Enable
#endif

#ifndef IDSNVID_CMN_FCH_HID_SPI_READ_MODE
  #define IDSNVID_CMN_FCH_HID_SPI_READ_MODE   (0xD149) //HID Spi Read Mode
#endif

#ifndef IDSNVID_CMN_FCH_HID_SPEED
  #define IDSNVID_CMN_FCH_HID_SPEED   (0xD14A) //HID Spi Speed
#endif

#ifndef IDSNVID_CMN_FCH_HID_SPI_SPEED6_N
  #define IDSNVID_CMN_FCH_HID_SPI_SPEED6_N   (0xD14B) //HID Spi Speed6 N
#endif

#ifndef IDSNVID_CMN_FCH_HID_SPI_SPEED7_N
  #define IDSNVID_CMN_FCH_HID_SPI_SPEED7_N   (0xD14C) //HID Spi Speed7 N
#endif

#ifndef IDSNVID_CMN_FCH_HID2_CONFIG
  #define IDSNVID_CMN_FCH_HID2_CONFIG   (0xD14D) //HID2 Enable
#endif

#ifndef IDSNVID_CMN_FCH_HID2_SPI_READ_MODE
  #define IDSNVID_CMN_FCH_HID2_SPI_READ_MODE   (0xD14E) //HID2 Spi Read Mode
#endif

#ifndef IDSNVID_CMN_FCH_HID2_SPEED
  #define IDSNVID_CMN_FCH_HID2_SPEED   (0xD14F) //HID2 Spi Speed
#endif

#ifndef IDSNVID_CMN_FCH_HID2_SPI_SPEED6_N
  #define IDSNVID_CMN_FCH_HID2_SPI_SPEED6_N   (0xD150) //HID2 Spi Speed6 N
#endif

#ifndef IDSNVID_CMN_FCH_HID2_SPI_SPEED7_N
  #define IDSNVID_CMN_FCH_HID2_SPI_SPEED7_N   (0xD151) //HID2 Spi Speed7 N
#endif

#ifndef IDSNVID_CMN_FCH_SYNCFLOOD_ENABLE
  #define IDSNVID_CMN_FCH_SYNCFLOOD_ENABLE   (0xD152) //Reset after sync flood
#endif

#ifndef IDSNVID_CMN_GNB_SMU_SYSTEM_CONFIG
  #define IDSNVID_CMN_GNB_SMU_SYSTEM_CONFIG   (0xD153) //System Configuration
#endif

#ifndef IDSNVID_DBG_SUSTAINED_POWER_LIMIT
  #define IDSNVID_DBG_SUSTAINED_POWER_LIMIT   (0xD154) //Sustained Power Limit
#endif

#ifndef IDSNVID_DBG_PPT_CTL
  #define IDSNVID_DBG_PPT_CTL   (0xD155) //PPT Control
#endif

#ifndef IDSNVID_DBG_FAST_PPT_LIMIT
  #define IDSNVID_DBG_FAST_PPT_LIMIT   (0xD156) //Fast PPT Limit
#endif

#ifndef IDSNVID_DBG_SLOW_PPT_LIMIT
  #define IDSNVID_DBG_SLOW_PPT_LIMIT   (0xD157) //Slow PPT Limit
#endif

#ifndef IDSNVID_DBG_SLOW_PPT_TIME_CONSTANT
  #define IDSNVID_DBG_SLOW_PPT_TIME_CONSTANT   (0xD158) //Slow PPT Time Constant
#endif

#ifndef IDSNVID_DBG_STAPM_CTL
  #define IDSNVID_DBG_STAPM_CTL   (0xD159) //STAPM Control
#endif

#ifndef IDSNVID_DBG_SYSTEM_TEMPERATURE_TRACKING
  #define IDSNVID_DBG_SYSTEM_TEMPERATURE_TRACKING   (0xD15A) //System Temperature Tracking
#endif

#ifndef IDSNVID_DBG_STAPM_BOOST_OVERRIDE
  #define IDSNVID_DBG_STAPM_BOOST_OVERRIDE   (0xD15B) //STAPM Boost Override
#endif

#ifndef IDSNVID_DBG_STAPM_BOOST
  #define IDSNVID_DBG_STAPM_BOOST   (0xD15C) //STAPM Boost
#endif

#ifndef IDSNVID_DBG_TSKIN_TIME_CONSTANT
  #define IDSNVID_DBG_TSKIN_TIME_CONSTANT   (0xD15D) //Tskin Time Constant
#endif

#ifndef IDSNVID_DBG_THM_CTL
  #define IDSNVID_DBG_THM_CTL   (0xD15E) //Thermal Control
#endif

#ifndef IDSNVID_DBG_TJ_MAX_LIMIT
  #define IDSNVID_DBG_TJ_MAX_LIMIT   (0xD15F) //TjMax
#endif

#ifndef IDSNVID_DBG_TDC_CTL
  #define IDSNVID_DBG_TDC_CTL   (0xD160) //TDC Control
#endif

#ifndef IDSNVID_DBG_TDCVDD_LIMIT
  #define IDSNVID_DBG_TDCVDD_LIMIT   (0xD161) //TDC_VDDCR_VDD
#endif

#ifndef IDSNVID_DBG_TDCSOC_LIMIT
  #define IDSNVID_DBG_TDCSOC_LIMIT   (0xD162) //TDC_VDDCR_SOC
#endif

#ifndef IDSNVID_DBG_TDCGFX_LIMIT
  #define IDSNVID_DBG_TDCGFX_LIMIT   (0xD163) //TDC_VDDCR_GFX
#endif

#ifndef IDSNVID_DBG_TDCCVIP_LIMIT
  #define IDSNVID_DBG_TDCCVIP_LIMIT   (0xD164) //TDC_VDDCR_CVIP
#endif

#ifndef IDSNVID_DBG_EDC_CTL
  #define IDSNVID_DBG_EDC_CTL   (0xD165) //EDC Control
#endif

#ifndef IDSNVID_DBG_EDCVDD_LIMIT
  #define IDSNVID_DBG_EDCVDD_LIMIT   (0xD166) //EDC_VDDCR_VDD
#endif

#ifndef IDSNVID_DBG_EDCSOC_LIMIT
  #define IDSNVID_DBG_EDCSOC_LIMIT   (0xD167) //EDC_VDDCR_SOC
#endif

#ifndef IDSNVID_DBG_EDCGFX_LIMIT
  #define IDSNVID_DBG_EDCGFX_LIMIT   (0xD168) //EDC_VDDCR_GFX
#endif

#ifndef IDSNVID_DBG_PS_I3_CTL
  #define IDSNVID_DBG_PS_I3_CTL   (0xD169) //PSI3 Control
#endif

#ifndef IDSNVID_DBG_PS_I3_VDD_LIMIT
  #define IDSNVID_DBG_PS_I3_VDD_LIMIT   (0xD16A) //PSI3_VDDCR_VDD
#endif

#ifndef IDSNVID_DBG_PS_I3_GFX_LIMIT
  #define IDSNVID_DBG_PS_I3_GFX_LIMIT   (0xD16B) //PSI3_VDDCR_GFX
#endif

#ifndef IDSNVID_DBG_PROCHOT_CTL
  #define IDSNVID_DBG_PROCHOT_CTL   (0xD16C) //PROCHOT Control
#endif

#ifndef IDSNVID_DBG_PROCHOT_RAMP_TIME
  #define IDSNVID_DBG_PROCHOT_RAMP_TIME   (0xD16D) //PROCHOT Deassertion Ramp Time
#endif

#ifndef IDSNVID_DBG_STT_CTL
  #define IDSNVID_DBG_STT_CTL   (0xD16E) //STT Control
#endif

#ifndef IDSNVID_CMN_STT_PCB_SENSOR_COUNT
  #define IDSNVID_CMN_STT_PCB_SENSOR_COUNT   (0xD16F) //STT_PCB_SENSOR_COUNT
#endif

#ifndef IDSNVID_CMN_STT_MIN_LIMIT
  #define IDSNVID_CMN_STT_MIN_LIMIT   (0xD170) //STT_MIN_POWER_LIMIT
#endif

#ifndef IDSNVID_CMN_STT_M1
  #define IDSNVID_CMN_STT_M1   (0xD171) //STT_M1
#endif

#ifndef IDSNVID_CMN_STT_M2
  #define IDSNVID_CMN_STT_M2   (0xD172) //STT_M2
#endif

#ifndef IDSNVID_CMN_STT_M3
  #define IDSNVID_CMN_STT_M3   (0xD173) //STT_M3
#endif

#ifndef IDSNVID_CMN_STT_M4
  #define IDSNVID_CMN_STT_M4   (0xD174) //STT_M4
#endif

#ifndef IDSNVID_CMN_STT_M5
  #define IDSNVID_CMN_STT_M5   (0xD175) //STT_M5
#endif

#ifndef IDSNVID_CMN_STT_M6
  #define IDSNVID_CMN_STT_M6   (0xD176) //STT_M6
#endif

#ifndef IDSNVID_CMN_STTCAPU
  #define IDSNVID_CMN_STTCAPU   (0xD177) //STT_C_APU
#endif

#ifndef IDSNVID_CMN_STTC_HS2
  #define IDSNVID_CMN_STTC_HS2   (0xD178) //STT_C_HS2
#endif

#ifndef IDSNVID_CMN_STT_ALPHA_APU
  #define IDSNVID_CMN_STT_ALPHA_APU   (0xD179) //STT_ALPHA_APU
#endif

#ifndef IDSNVID_CMN_STT_ALPHA_H_S2
  #define IDSNVID_CMN_STT_ALPHA_H_S2   (0xD17A) //STT_ALPHA_HS2
#endif

#ifndef IDSNVID_CMN_STT_SKIN_TEMPERATURE_LIMIT_APU
  #define IDSNVID_CMN_STT_SKIN_TEMPERATURE_LIMIT_APU   (0xD17B) //STT_SKIN_TEMPERATURE_LIMIT_APU
#endif

#ifndef IDSNVID_CMN_STT_SKIN_TEMPERATURE_LIMIT_HS2
  #define IDSNVID_CMN_STT_SKIN_TEMPERATURE_LIMIT_HS2   (0xD17C) //STT_SKIN_TEMPERATURE_LIMIT_HS2
#endif

#ifndef IDSNVID_CMN_STT_ERROR_COEFF
  #define IDSNVID_CMN_STT_ERROR_COEFF   (0xD17D) //STT_ERROR_COEFF
#endif

#ifndef IDSNVID_CMN_STT_ERROR_RATE_COEFF
  #define IDSNVID_CMN_STT_ERROR_RATE_COEFF   (0xD17E) //STT_ERROR_RATE_COEFF
#endif

#ifndef IDSNVID_DBG_FAN_CTL
  #define IDSNVID_DBG_FAN_CTL   (0xD17F) //Fan Control
#endif

#ifndef IDSNVID_DBG_FORCE_PWM_CTL
  #define IDSNVID_DBG_FORCE_PWM_CTL   (0xD180) //Force PWM Control
#endif

#ifndef IDSNVID_DBG_FORCE_PWM
  #define IDSNVID_DBG_FORCE_PWM   (0xD181) //Force PWM
#endif

#ifndef IDSNVID_DBG_FAN_TABLE_CTL
  #define IDSNVID_DBG_FAN_TABLE_CTL   (0xD182) //Fan Table Control
#endif

#ifndef IDSNVID_DBG_FAN_TABLE_TEMP_LOW
  #define IDSNVID_DBG_FAN_TABLE_TEMP_LOW   (0xD183) //Low Temperature
#endif

#ifndef IDSNVID_DBG_FAN_TABLE_TEMP_MED
  #define IDSNVID_DBG_FAN_TABLE_TEMP_MED   (0xD184) //Medium Temperature
#endif

#ifndef IDSNVID_DBG_FAN_TABLE_TEMP_HIGH
  #define IDSNVID_DBG_FAN_TABLE_TEMP_HIGH   (0xD185) //High Temperature
#endif

#ifndef IDSNVID_DBG_FAN_TABLE_TEMP_CRITICAL
  #define IDSNVID_DBG_FAN_TABLE_TEMP_CRITICAL   (0xD186) //Critical Temperature
#endif

#ifndef IDSNVID_DBG_FAN_TABLE_T_PWM_LOW
  #define IDSNVID_DBG_FAN_TABLE_T_PWM_LOW   (0xD187) //Low Pwm
#endif

#ifndef IDSNVID_DBG_FAN_TABLE_PWM_MED
  #define IDSNVID_DBG_FAN_TABLE_PWM_MED   (0xD188) //Medium Pwm
#endif

#ifndef IDSNVID_DBG_FAN_TABLE_PWM_HIGH
  #define IDSNVID_DBG_FAN_TABLE_PWM_HIGH   (0xD189) //High Pwm
#endif

#ifndef IDSNVID_DBG_FAN_TABLE_HYST
  #define IDSNVID_DBG_FAN_TABLE_HYST   (0xD18A) //Temperature Hysteresis
#endif

#ifndef IDSNVID_DBG_FAN_TABLE_PWM_FREQ
  #define IDSNVID_DBG_FAN_TABLE_PWM_FREQ   (0xD18B) //Pwm Frequency
#endif

#ifndef IDSNVID_DBG_FAN_POLARITY
  #define IDSNVID_DBG_FAN_POLARITY   (0xD18C) //Fan polarity
#endif

#ifndef IDSNVID_DBG_VDDP_VOLTAGE_CTL
  #define IDSNVID_DBG_VDDP_VOLTAGE_CTL   (0xD18D) //VDDP Voltage Control
#endif

#ifndef IDSNVID_DBG_VDDP_VOLTAGE
  #define IDSNVID_DBG_VDDP_VOLTAGE   (0xD18E) //VDDP Voltage
#endif

#ifndef IDSNVID_DBG_VDDM_VOLTAGE_CTL
  #define IDSNVID_DBG_VDDM_VOLTAGE_CTL   (0xD18F) //VDDM Voltage Control
#endif

#ifndef IDSNVID_DBG_VDDM_VOLTAGE
  #define IDSNVID_DBG_VDDM_VOLTAGE   (0xD190) //VDDM Voltage
#endif

#ifndef IDSNVID_CMN_GNB_SMU_ZSTATES
  #define IDSNVID_CMN_GNB_SMU_ZSTATES   (0xD191) //Zstates (Z9 and Z10)
#endif

#ifndef IDSNVID_CMN_CCLK_FMAX_CTL
  #define IDSNVID_CMN_CCLK_FMAX_CTL   (0xD192) //CclkFmaxOverride Control
#endif

#ifndef IDSNVID_CMN_CCLK_FMAX_OVERRIDE
  #define IDSNVID_CMN_CCLK_FMAX_OVERRIDE   (0xD193) //CclkFmaxOverride
#endif

#ifndef IDSNVID_CMN_DF_PSTATE_P0_CTL
  #define IDSNVID_CMN_DF_PSTATE_P0_CTL   (0xD194) //DF Pstate P0 Ctl
#endif

#ifndef IDSNVID_CMN_DF_PSTATE_FCLK_P0
  #define IDSNVID_CMN_DF_PSTATE_FCLK_P0   (0xD195) //DF Pstate Fclk P0
#endif

#ifndef IDSNVID_CMN_DF_PSTATE_MEM_CLK_P0
  #define IDSNVID_CMN_DF_PSTATE_MEM_CLK_P0   (0xD196) //DF Pstate MemClk P0
#endif

#ifndef IDSNVID_CMN_FCLK_VALUE
  #define IDSNVID_CMN_FCLK_VALUE   (0xD197) //Fixed FCLK
#endif

#ifndef IDSNVID_CMN_LCLK_FREQ
  #define IDSNVID_CMN_LCLK_FREQ   (0xD198) //Fixed LCLK
#endif

#ifndef IDSNVID_CMN_RST_ON_MP1_SMN_TIMEOUT
  #define IDSNVID_CMN_RST_ON_MP1_SMN_TIMEOUT   (0xD199) //Reset on MP1 SMN Timeout
#endif

#ifndef IDSNVID_CMN_AA_CTL
  #define IDSNVID_CMN_AA_CTL   (0xD19A) //SmartShift Control
#endif

#ifndef IDSNVID_CMN_AA_EN
  #define IDSNVID_CMN_AA_EN   (0xD19B) //SmartShift Enable
#endif

#ifndef IDSNVID_CMN_APU_ONLY_SPPT_LIMIT
  #define IDSNVID_CMN_APU_ONLY_SPPT_LIMIT   (0xD19C) //APU Only sPPT Limit
#endif

#ifndef IDSNVID_CMN_MSG_SET_SUSTAINED_POWER_LIMIT
  #define IDSNVID_CMN_MSG_SET_SUSTAINED_POWER_LIMIT   (0xD19D) //Sustained PowerLimit
#endif

#ifndef IDSNVID_CMN_MSG_SET_FAST_PPT_LIMIT
  #define IDSNVID_CMN_MSG_SET_FAST_PPT_LIMIT   (0xD19E) //Fast PPT Limit
#endif

#ifndef IDSNVID_CMN_MSG_SE_SLOW_PPT_LIMIT
  #define IDSNVID_CMN_MSG_SE_SLOW_PPT_LIMIT   (0xD19F) //Slow PPT Limit
#endif

#ifndef IDSNVID_CMN_PSP_RPMC_SWITCH
  #define IDSNVID_CMN_PSP_RPMC_SWITCH   (0xD1A0) //PSP RPMC Switch
#endif

#ifndef IDSNVID_CMN_ROM_ARMOR_SUPPORT
  #define IDSNVID_CMN_ROM_ARMOR_SUPPORT   (0xD1A1) //Rom Armor support
#endif

#ifndef IDSNVID_CMN_ROM_ARMOR_SPI_CONFIG_REG_LOCK
  #define IDSNVID_CMN_ROM_ARMOR_SPI_CONFIG_REG_LOCK   (0xD1A2) //Rom Armor Spi Config Reg Lock
#endif

#ifndef IDSNVID_CMN_SOC_ABL_CON_OUT
  #define IDSNVID_CMN_SOC_ABL_CON_OUT   (0xD1A3) //ABL Console Out Control
#endif

#ifndef IDSNVID_CMN_SOC_ABL_CON_OUT_SERIAL_PORT
  #define IDSNVID_CMN_SOC_ABL_CON_OUT_SERIAL_PORT   (0xD1A4) //ABL Console Out Serial Port
#endif

#ifndef IDSNVID_CMN_SOC_ABL_CON_OUT_SERIAL_PORT_IO
  #define IDSNVID_CMN_SOC_ABL_CON_OUT_SERIAL_PORT_IO   (0xD1A5) //ABL Console Out Serial Port IO
#endif

#ifndef IDSNVID_CMN_SOC_ABL_CON_OUT_BOOT_MODE
  #define IDSNVID_CMN_SOC_ABL_CON_OUT_BOOT_MODE   (0xD1A6) //ABL Console Out Boot Mode Select
#endif

#ifndef IDSNVID_CMN_SOC_ABL_PMU_MSG_CTRL
  #define IDSNVID_CMN_SOC_ABL_PMU_MSG_CTRL   (0xD1A7) //ABL PMU message Control
#endif

#ifndef IDSNVID_CMN_SOC_SCPC_AUTO_ENABLEMENT
  #define IDSNVID_CMN_SOC_SCPC_AUTO_ENABLEMENT   (0xD1A8) //Secured-core Auto enablement
#endif

#ifndef IDSNVID_CMN_MIXED_DIMM_CONFIG_NUMA_DOMAIN
  #define IDSNVID_CMN_MIXED_DIMM_CONFIG_NUMA_DOMAIN   (0xD1A9) //Mixed DIMM config extended NUMA domain
#endif

#ifndef IDSNVID_CMN_SOC_FAR_ENFORCED
  #define IDSNVID_CMN_SOC_FAR_ENFORCED   (0xD1AA) //FAR enforcement state
#endif

#ifndef IDSNVID_CMN_SOC_SPL_FUSE
  #define IDSNVID_CMN_SOC_SPL_FUSE   (0xD1AB) //SPL value in the CPU fuse
#endif

#ifndef IDSNVID_CMN_SOC_SPL_VALUE_IN_TBL
  #define IDSNVID_CMN_SOC_SPL_VALUE_IN_TBL   (0xD1AC) //SPL value in the SPL table
#endif

#ifndef IDSNVID_CMN_SOC_INIT_SPL_FOR_FAR
  #define IDSNVID_CMN_SOC_INIT_SPL_FOR_FAR   (0xD1AD) //Initial SPL value for FAR
#endif

#ifndef IDSNVID_CMN_SOC_FAR_SWITCH
  #define IDSNVID_CMN_SOC_FAR_SWITCH   (0xD1AE) //FAR Switch
#endif

#ifndef IDSNVID_CMN_SO_C_MISC_X86_FW_SUPPORT
  #define IDSNVID_CMN_SO_C_MISC_X86_FW_SUPPORT   (0xD1AF) //Pluton (HSP) X86 Firmware Support
#endif

#ifndef IDSNVID_CMN_SO_C_MISC_HSP_UART
  #define IDSNVID_CMN_SO_C_MISC_HSP_UART   (0xD1B0) //Pluton (HSP) UART
#endif

#ifndef IDSNVID_CMN_SO_C_MISC_HSP_UART_PORT
  #define IDSNVID_CMN_SO_C_MISC_HSP_UART_PORT   (0xD1B1) //Pluton (HSP) UART Port
#endif

#ifndef IDSNVID_CMN_SO_C_MISC_HSP_FIPS
  #define IDSNVID_CMN_SO_C_MISC_HSP_FIPS   (0xD1B2) //Pluton (HSP) FIPS
#endif

#ifndef IDSNVID_CMN_SO_C_MISC_HSP_FIPS_ZEROIZATION
  #define IDSNVID_CMN_SO_C_MISC_HSP_FIPS_ZEROIZATION   (0xD1B3) //Pluton (HSP) FIPS zeroization
#endif

#ifndef IDSNVID_CMN_SO_C_MISC_HSP_ACPI_FENCE_ENABLE
  #define IDSNVID_CMN_SO_C_MISC_HSP_ACPI_FENCE_ENABLE   (0xD1B4) //Pluton (HSP) ACPI Fence Enable
#endif

#ifndef IDSNVID_CMN_SO_C_MISC_MPM_SUPPORT
  #define IDSNVID_CMN_SO_C_MISC_MPM_SUPPORT   (0xD1B5) //AGESA MPM support
#endif

#ifndef IDSNVID_CMN_SO_C_MISC_WIRED_KVM
  #define IDSNVID_CMN_SO_C_MISC_WIRED_KVM   (0xD1B6) //KVM for Wired Manageability
#endif

#ifndef IDSNVID_CMN_SO_C_MISC_WIRELESS_MANAGEABILITY
  #define IDSNVID_CMN_SO_C_MISC_WIRELESS_MANAGEABILITY   (0xD1B7) //Wireless Manageability
#endif

#ifndef IDSNVID_CMN_SO_C_MISC_WIRELESS_KVM
  #define IDSNVID_CMN_SO_C_MISC_WIRELESS_KVM   (0xD1B8) //KVM for Wireless Manageability
#endif

#ifndef IDSNVID_CMN_SOC_MISC_MPM_ATTR_CNTL
  #define IDSNVID_CMN_SOC_MISC_MPM_ATTR_CNTL   (0xD1B9) //MPM attribute control
#endif

#ifndef IDSNVID_CMN_SO_C_MISC_WIRELESS_TCR
  #define IDSNVID_CMN_SO_C_MISC_WIRELESS_TCR   (0xD1BA) //TCR for Wireless Manageability
#endif

#ifndef IDSNVID_CMN_INTRUSION_DETECTION_CTL
  #define IDSNVID_CMN_INTRUSION_DETECTION_CTL   (0xD1BB) //Intrusion Detection Control
#endif

#ifndef IDSNVID_CMN_INTRUSION_DETECTION_ENABLE
  #define IDSNVID_CMN_INTRUSION_DETECTION_ENABLE   (0xD1BC) //Intrusion Detection Enable
#endif

#ifndef IDSNVID_CMN_INTRUSION_LOG_EVENT
  #define IDSNVID_CMN_INTRUSION_LOG_EVENT   (0xD1BD) //Log Intrusion Event
#endif

#ifndef IDSNVID_CMN_INTRUSION_CLEAR_TPM
  #define IDSNVID_CMN_INTRUSION_CLEAR_TPM   (0xD1BE) //Clear TPM
#endif

#ifndef IDSNVID_CMN_INTRUSION_POWER_OFF
  #define IDSNVID_CMN_INTRUSION_POWER_OFF   (0xD1BF) //Power Off System
#endif

#ifndef IDSNVID_CMN_P_T21_PCIE_P0
  #define IDSNVID_CMN_P_T21_PCIE_P0   (0xD1C0) //PCIe Port 0
#endif

#ifndef IDSNVID_CMN_P_T21_PCIE_P1
  #define IDSNVID_CMN_P_T21_PCIE_P1   (0xD1C1) //PCIe Port 1
#endif

#ifndef IDSNVID_CMN_P_T21_PCIE_P2
  #define IDSNVID_CMN_P_T21_PCIE_P2   (0xD1C2) //PCIe Port 2
#endif

#ifndef IDSNVID_CMN_P_T21_PCIE_P3
  #define IDSNVID_CMN_P_T21_PCIE_P3   (0xD1C3) //PCIe Port 3
#endif

#ifndef IDSNVID_CMN_P_T21_PCIE_P4
  #define IDSNVID_CMN_P_T21_PCIE_P4   (0xD1C4) //PCIe Port 4
#endif

#ifndef IDSNVID_CMN_P_T21_PCIE_P5
  #define IDSNVID_CMN_P_T21_PCIE_P5   (0xD1C5) //PCIe Port 5
#endif

#ifndef IDSNVID_CMN_P_T21_PCIE_P6
  #define IDSNVID_CMN_P_T21_PCIE_P6   (0xD1C6) //PCIe Port 6
#endif

#ifndef IDSNVID_CMN_P_T21_PCIE_P7
  #define IDSNVID_CMN_P_T21_PCIE_P7   (0xD1C7) //PCIe Port 7
#endif

#ifndef IDSNVID_CMN_P_T21_PCIE_P8
  #define IDSNVID_CMN_P_T21_PCIE_P8   (0xD1C8) //PCIe Port 8
#endif

#ifndef IDSNVID_CMN_P_T21_PCIE_P9
  #define IDSNVID_CMN_P_T21_PCIE_P9   (0xD1C9) //PCIe Port 9
#endif

#ifndef IDSNVID_CMN_P_T21_PCIE_P10
  #define IDSNVID_CMN_P_T21_PCIE_P10   (0xD1CA) //PCIe Port 10
#endif

#ifndef IDSNVID_CMN_P_T21_PCIE_P11
  #define IDSNVID_CMN_P_T21_PCIE_P11   (0xD1CB) //PCIe Port 11
#endif

#ifndef IDSNVID_CMN_P_T21_PCIE_P12
  #define IDSNVID_CMN_P_T21_PCIE_P12   (0xD1CC) //PCIe Port 12
#endif

#ifndef IDSNVID_CMN_P_T21_PCIE_P13
  #define IDSNVID_CMN_P_T21_PCIE_P13   (0xD1CD) //PCIe Port 13
#endif

#ifndef IDSNVID_CMN_P_T21_SATA_CLASS
  #define IDSNVID_CMN_P_T21_SATA_CLASS   (0xD1CE) //SATA Mode
#endif

#ifndef IDSNVID_CMN_P_T21_SATA_PORT0
  #define IDSNVID_CMN_P_T21_SATA_PORT0   (0xD1CF) //SATA Port 0
#endif

#ifndef IDSNVID_CMN_P_T21_SATA_PORT1
  #define IDSNVID_CMN_P_T21_SATA_PORT1   (0xD1D0) //SATA Port 1
#endif

#ifndef IDSNVID_CMN_P_T21_SATA_PORT2
  #define IDSNVID_CMN_P_T21_SATA_PORT2   (0xD1D1) //SATA Port 2
#endif

#ifndef IDSNVID_CMN_P_T21_SATA_PORT3
  #define IDSNVID_CMN_P_T21_SATA_PORT3   (0xD1D2) //SATA Port 3
#endif

#ifndef IDSNVID_DBG_P_T21_SATA_AGGRESSIVE_DEV_SLP_P0
  #define IDSNVID_DBG_P_T21_SATA_AGGRESSIVE_DEV_SLP_P0   (0xD1D3) //Device Sleep for AHCI Port 0
#endif

#ifndef IDSNVID_DBG_P_T21_SATA_AGGRESSIVE_DEV_SLP_P1
  #define IDSNVID_DBG_P_T21_SATA_AGGRESSIVE_DEV_SLP_P1   (0xD1D4) //Device Sleep for AHCI Port 1
#endif

#ifndef IDSNVID_DBG_P_T21_SATA_AGGRESSIVE_DEV_SLP_P2
  #define IDSNVID_DBG_P_T21_SATA_AGGRESSIVE_DEV_SLP_P2   (0xD1D5) //Device Sleep for AHCI Port 2
#endif

#ifndef IDSNVID_DBG_P_T21_SATA_AGGRESSIVE_DEV_SLP_P3
  #define IDSNVID_DBG_P_T21_SATA_AGGRESSIVE_DEV_SLP_P3   (0xD1D6) //Device Sleep for AHCI Port 3
#endif

#ifndef IDSNVID_DBG_P_T21_XHCI_P0_GEN
  #define IDSNVID_DBG_P_T21_XHCI_P0_GEN   (0xD1D7) //USB3 Port 0
#endif

#ifndef IDSNVID_DBG_P_T21_XHCI_P1_GEN
  #define IDSNVID_DBG_P_T21_XHCI_P1_GEN   (0xD1D8) //USB3 Port 1
#endif

#ifndef IDSNVID_DBG_P_T21_XHCI_P2_GEN
  #define IDSNVID_DBG_P_T21_XHCI_P2_GEN   (0xD1D9) //USB3 Port 2
#endif

#ifndef IDSNVID_DBG_P_T21_XHCI_P3_GEN
  #define IDSNVID_DBG_P_T21_XHCI_P3_GEN   (0xD1DA) //USB3 Port 3
#endif

#ifndef IDSNVID_DBG_P_T21_XHCI_P4_GEN
  #define IDSNVID_DBG_P_T21_XHCI_P4_GEN   (0xD1DB) //USB3 Port 4
#endif

#ifndef IDSNVID_DBG_P_T21_XHCI_P5_GEN
  #define IDSNVID_DBG_P_T21_XHCI_P5_GEN   (0xD1DC) //USB3 Port 5
#endif

#ifndef IDSNVID_CMN_P_T21_USB3_P0
  #define IDSNVID_CMN_P_T21_USB3_P0   (0xD1DD) //USB3 Port 0
#endif

#ifndef IDSNVID_CMN_P_T21_USB3_P1
  #define IDSNVID_CMN_P_T21_USB3_P1   (0xD1DE) //USB3 Port 1
#endif

#ifndef IDSNVID_CMN_P_T21_USB3_P2
  #define IDSNVID_CMN_P_T21_USB3_P2   (0xD1DF) //USB3 Port 2
#endif

#ifndef IDSNVID_CMN_P_T21_USB3_P3
  #define IDSNVID_CMN_P_T21_USB3_P3   (0xD1E0) //USB3 Port 3
#endif

#ifndef IDSNVID_CMN_P_T21_USB3_P4
  #define IDSNVID_CMN_P_T21_USB3_P4   (0xD1E1) //USB3 Port 4
#endif

#ifndef IDSNVID_CMN_P_T21_USB3_P5
  #define IDSNVID_CMN_P_T21_USB3_P5   (0xD1E2) //USB3 Port 5
#endif

#ifndef IDSNVID_CMN_P_T21_USB2_P0
  #define IDSNVID_CMN_P_T21_USB2_P0   (0xD1E3) //USB2 Port 0
#endif

#ifndef IDSNVID_CMN_P_T21_USB2_P1
  #define IDSNVID_CMN_P_T21_USB2_P1   (0xD1E4) //USB2 Port 1
#endif

#ifndef IDSNVID_CMN_P_T21_USB2_P2
  #define IDSNVID_CMN_P_T21_USB2_P2   (0xD1E5) //USB2 Port 2
#endif

#ifndef IDSNVID_CMN_P_T21_USB2_P3
  #define IDSNVID_CMN_P_T21_USB2_P3   (0xD1E6) //USB2 Port 3
#endif

#ifndef IDSNVID_CMN_P_T21_USB2_P4
  #define IDSNVID_CMN_P_T21_USB2_P4   (0xD1E7) //USB2 Port 4
#endif

#ifndef IDSNVID_CMN_P_T21_USB2_P5
  #define IDSNVID_CMN_P_T21_USB2_P5   (0xD1E8) //USB2 Port 5
#endif

#ifndef IDSNVID_CMN_P_T21_USB2_P6
  #define IDSNVID_CMN_P_T21_USB2_P6   (0xD1E9) //USB2 Port 6
#endif

#ifndef IDSNVID_CMN_P_T21_USB2_P7
  #define IDSNVID_CMN_P_T21_USB2_P7   (0xD1EA) //USB2 Port 7
#endif

#ifndef IDSNVID_CMN_P_T21_USB2_P8
  #define IDSNVID_CMN_P_T21_USB2_P8   (0xD1EB) //USB2 Port 8
#endif

#ifndef IDSNVID_CMN_P_T21_USB2_P9
  #define IDSNVID_CMN_P_T21_USB2_P9   (0xD1EC) //USB2 Port 9
#endif

#ifndef IDSNVID_CMN_P_T21_USB2_P10
  #define IDSNVID_CMN_P_T21_USB2_P10   (0xD1ED) //USB2 Port 10
#endif

#ifndef IDSNVID_CMN_P_T21_USB2_P11
  #define IDSNVID_CMN_P_T21_USB2_P11   (0xD1EE) //USB2 Port 11
#endif

#ifndef IDSNVID_CMN_P_T21_L4_USB3_P0
  #define IDSNVID_CMN_P_T21_L4_USB3_P0   (0xD1EF) //USB3 Port 0
#endif

#ifndef IDSNVID_CMN_P_T21_L4_USB3_P1
  #define IDSNVID_CMN_P_T21_L4_USB3_P1   (0xD1F0) //USB3 Port 1
#endif

#ifndef IDSNVID_CMN_P_T21_L4_USB3_P2
  #define IDSNVID_CMN_P_T21_L4_USB3_P2   (0xD1F1) //USB3 Port 2
#endif

#ifndef IDSNVID_CMN_P_T21_L4_USB3_P3
  #define IDSNVID_CMN_P_T21_L4_USB3_P3   (0xD1F2) //USB3 Port 3
#endif

#ifndef IDSNVID_CMN_P_T21_L4_USB2_P0
  #define IDSNVID_CMN_P_T21_L4_USB2_P0   (0xD1F3) //USB2 Port 0
#endif

#ifndef IDSNVID_CMN_P_T21_L4_USB2_P1
  #define IDSNVID_CMN_P_T21_L4_USB2_P1   (0xD1F4) //USB2 Port 1
#endif

#ifndef IDSNVID_CMN_P_T21_L4_USB2_P2
  #define IDSNVID_CMN_P_T21_L4_USB2_P2   (0xD1F5) //USB2 Port 2
#endif

#ifndef IDSNVID_CMN_P_T21_L4_USB2_P3
  #define IDSNVID_CMN_P_T21_L4_USB2_P3   (0xD1F6) //USB2 Port 3
#endif

#ifndef IDSNVID_CMN_P_T21_L4_USB2_P4
  #define IDSNVID_CMN_P_T21_L4_USB2_P4   (0xD1F7) //USB2 Port 4
#endif

#ifndef IDSNVID_CMN_P_T21_L4_USB2_P5
  #define IDSNVID_CMN_P_T21_L4_USB2_P5   (0xD1F8) //USB2 Port 5
#endif

#ifndef IDSNVID_CMN_P_T21_L4_USB2_P6
  #define IDSNVID_CMN_P_T21_L4_USB2_P6   (0xD1F9) //USB2 Port 6
#endif

#ifndef IDSNVID_CMN_P_T21_L4_USB2_P7
  #define IDSNVID_CMN_P_T21_L4_USB2_P7   (0xD1FA) //USB2 Port 7
#endif

#ifndef IDSNVID_CMN_P_T21_L4_USB2_P8
  #define IDSNVID_CMN_P_T21_L4_USB2_P8   (0xD1FB) //USB2 Port 8
#endif

#ifndef IDSNVID_CMN_P_T21_L4_USB2_P9
  #define IDSNVID_CMN_P_T21_L4_USB2_P9   (0xD1FC) //USB2 Port 9
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_PCIE_P0
  #define IDSNVID_CMN_SEC_P_T21_PCIE_P0   (0xD1FD) //PCIe Port 0
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_PCIE_P1
  #define IDSNVID_CMN_SEC_P_T21_PCIE_P1   (0xD1FE) //PCIe Port 1
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_PCIE_P2
  #define IDSNVID_CMN_SEC_P_T21_PCIE_P2   (0xD1FF) //PCIe Port 2
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_PCIE_P3
  #define IDSNVID_CMN_SEC_P_T21_PCIE_P3   (0xD200) //PCIe Port 3
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_PCIE_P4
  #define IDSNVID_CMN_SEC_P_T21_PCIE_P4   (0xD201) //PCIe Port 4
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_PCIE_P5
  #define IDSNVID_CMN_SEC_P_T21_PCIE_P5   (0xD202) //PCIe Port 5
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_PCIE_P6
  #define IDSNVID_CMN_SEC_P_T21_PCIE_P6   (0xD203) //PCIe Port 6
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_PCIE_P7
  #define IDSNVID_CMN_SEC_P_T21_PCIE_P7   (0xD204) //PCIe Port 7
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_PCIE_P8
  #define IDSNVID_CMN_SEC_P_T21_PCIE_P8   (0xD205) //PCIe Port 8
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_PCIE_P9
  #define IDSNVID_CMN_SEC_P_T21_PCIE_P9   (0xD206) //PCIe Port 9
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_PCIE_P10
  #define IDSNVID_CMN_SEC_P_T21_PCIE_P10   (0xD207) //PCIe Port 10
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_PCIE_P11
  #define IDSNVID_CMN_SEC_P_T21_PCIE_P11   (0xD208) //PCIe Port 11
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_PCIE_P12
  #define IDSNVID_CMN_SEC_P_T21_PCIE_P12   (0xD209) //PCIe Port 12
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_PCIE_P13
  #define IDSNVID_CMN_SEC_P_T21_PCIE_P13   (0xD20A) //PCIe Port 13
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_SATA_CLASS
  #define IDSNVID_CMN_SEC_P_T21_SATA_CLASS   (0xD20B) //SATA Mode
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_SATA_PORT0
  #define IDSNVID_CMN_SEC_P_T21_SATA_PORT0   (0xD20C) //SATA Port 0
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_SATA_PORT1
  #define IDSNVID_CMN_SEC_P_T21_SATA_PORT1   (0xD20D) //SATA Port 1
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_SATA_PORT2
  #define IDSNVID_CMN_SEC_P_T21_SATA_PORT2   (0xD20E) //SATA Port 2
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_SATA_PORT3
  #define IDSNVID_CMN_SEC_P_T21_SATA_PORT3   (0xD20F) //SATA Port 3
#endif

#ifndef IDSNVID_DBG_SEC_P_T21_SATA_AGGRESIVE_DEV_SLP_P0
  #define IDSNVID_DBG_SEC_P_T21_SATA_AGGRESIVE_DEV_SLP_P0   (0xD210) //Device Sleep for AHCI Port 0
#endif

#ifndef IDSNVID_DBG_SEC_P_T21_SATA_AGGRESIVE_DEV_SLP_P1
  #define IDSNVID_DBG_SEC_P_T21_SATA_AGGRESIVE_DEV_SLP_P1   (0xD211) //Device Sleep for AHCI Port 1
#endif

#ifndef IDSNVID_DBG_SEC_P_T21_SATA_AGGRESIVE_DEV_SLP_P2
  #define IDSNVID_DBG_SEC_P_T21_SATA_AGGRESIVE_DEV_SLP_P2   (0xD212) //Device Sleep for AHCI Port 2
#endif

#ifndef IDSNVID_DBG_SEC_P_T21_SATA_AGGRESIVE_DEV_SLP_P3
  #define IDSNVID_DBG_SEC_P_T21_SATA_AGGRESIVE_DEV_SLP_P3   (0xD213) //Device Sleep for AHCI Port 3
#endif

#ifndef IDSNVID_DBG_SEC_P_T21_XHCI_P0_GEN
  #define IDSNVID_DBG_SEC_P_T21_XHCI_P0_GEN   (0xD214) //USB3 Port 0
#endif

#ifndef IDSNVID_DBG_SEC_P_T21_XHCI_P1_GEN
  #define IDSNVID_DBG_SEC_P_T21_XHCI_P1_GEN   (0xD215) //USB3 Port 1
#endif

#ifndef IDSNVID_DBG_SEC_P_T21_XHCI_P2_GEN
  #define IDSNVID_DBG_SEC_P_T21_XHCI_P2_GEN   (0xD216) //USB3 Port 2
#endif

#ifndef IDSNVID_DBG_SEC_P_T21_XHCI_P3_GEN
  #define IDSNVID_DBG_SEC_P_T21_XHCI_P3_GEN   (0xD217) //USB3 Port 3
#endif

#ifndef IDSNVID_DBG_SEC_P_T21_XHCI_P4_GEN
  #define IDSNVID_DBG_SEC_P_T21_XHCI_P4_GEN   (0xD218) //USB3 Port 4
#endif

#ifndef IDSNVID_DBG_SEC_P_T21_XHCI_P5_GEN
  #define IDSNVID_DBG_SEC_P_T21_XHCI_P5_GEN   (0xD219) //USB3 Port 5
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_USB3_P0
  #define IDSNVID_CMN_SEC_P_T21_USB3_P0   (0xD21A) //USB3 Port 0
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_USB3_P1
  #define IDSNVID_CMN_SEC_P_T21_USB3_P1   (0xD21B) //USB3 Port 1
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_USB3_P2
  #define IDSNVID_CMN_SEC_P_T21_USB3_P2   (0xD21C) //USB3 Port 2
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_USB3_P3
  #define IDSNVID_CMN_SEC_P_T21_USB3_P3   (0xD21D) //USB3 Port 3
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_USB3_P4
  #define IDSNVID_CMN_SEC_P_T21_USB3_P4   (0xD21E) //USB3 Port 4
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_USB3_P5
  #define IDSNVID_CMN_SEC_P_T21_USB3_P5   (0xD21F) //USB3 Port 5
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_USB2_P0
  #define IDSNVID_CMN_SEC_P_T21_USB2_P0   (0xD220) //USB2 Port 0
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_USB2_P1
  #define IDSNVID_CMN_SEC_P_T21_USB2_P1   (0xD221) //USB2 Port 1
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_USB2_P2
  #define IDSNVID_CMN_SEC_P_T21_USB2_P2   (0xD222) //USB2 Port 2
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_USB2_P3
  #define IDSNVID_CMN_SEC_P_T21_USB2_P3   (0xD223) //USB2 Port 3
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_USB2_P4
  #define IDSNVID_CMN_SEC_P_T21_USB2_P4   (0xD224) //USB2 Port 4
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_USB2_P5
  #define IDSNVID_CMN_SEC_P_T21_USB2_P5   (0xD225) //USB2 Port 5
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_USB2_P6
  #define IDSNVID_CMN_SEC_P_T21_USB2_P6   (0xD226) //USB2 Port 6
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_USB2_P7
  #define IDSNVID_CMN_SEC_P_T21_USB2_P7   (0xD227) //USB2 Port 7
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_USB2_P8
  #define IDSNVID_CMN_SEC_P_T21_USB2_P8   (0xD228) //USB2 Port 8
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_USB2_P9
  #define IDSNVID_CMN_SEC_P_T21_USB2_P9   (0xD229) //USB2 Port 9
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_USB2_P10
  #define IDSNVID_CMN_SEC_P_T21_USB2_P10   (0xD22A) //USB2 Port 10
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_USB2_P11
  #define IDSNVID_CMN_SEC_P_T21_USB2_P11   (0xD22B) //USB2 Port 11
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_L4_USB3_P0
  #define IDSNVID_CMN_SEC_P_T21_L4_USB3_P0   (0xD22C) //USB3 Port 0
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_L4_USB3_P1
  #define IDSNVID_CMN_SEC_P_T21_L4_USB3_P1   (0xD22D) //USB3 Port 1
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_L4_USB3_P2
  #define IDSNVID_CMN_SEC_P_T21_L4_USB3_P2   (0xD22E) //USB3 Port 2
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_L4_USB3_P3
  #define IDSNVID_CMN_SEC_P_T21_L4_USB3_P3   (0xD22F) //USB3 Port 3
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_L4_USB2_P0
  #define IDSNVID_CMN_SEC_P_T21_L4_USB2_P0   (0xD230) //USB2 Port 0
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_L4_USB2_P1
  #define IDSNVID_CMN_SEC_P_T21_L4_USB2_P1   (0xD231) //USB2 Port 1
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_L4_USB2_P2
  #define IDSNVID_CMN_SEC_P_T21_L4_USB2_P2   (0xD232) //USB2 Port 2
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_L4_USB2_P3
  #define IDSNVID_CMN_SEC_P_T21_L4_USB2_P3   (0xD233) //USB2 Port 3
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_L4_USB2_P4
  #define IDSNVID_CMN_SEC_P_T21_L4_USB2_P4   (0xD234) //USB2 Port 4
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_L4_USB2_P5
  #define IDSNVID_CMN_SEC_P_T21_L4_USB2_P5   (0xD235) //USB2 Port 5
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_L4_USB2_P6
  #define IDSNVID_CMN_SEC_P_T21_L4_USB2_P6   (0xD236) //USB2 Port 6
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_L4_USB2_P7
  #define IDSNVID_CMN_SEC_P_T21_L4_USB2_P7   (0xD237) //USB2 Port 7
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_L4_USB2_P8
  #define IDSNVID_CMN_SEC_P_T21_L4_USB2_P8   (0xD238) //USB2 Port 8
#endif

#ifndef IDSNVID_CMN_SEC_P_T21_L4_USB2_P9
  #define IDSNVID_CMN_SEC_P_T21_L4_USB2_P9   (0xD239) //USB2 Port 9
#endif

#ifndef IDSNVID_CMN_TNR_PM_WAKE_EN
  #define IDSNVID_CMN_TNR_PM_WAKE_EN   (0xD23A) //PM Wake Enable
#endif

#ifndef IDSNVID_CMN_TNR_PCIE_CHANNEL_EN_ONCE
  #define IDSNVID_CMN_TNR_PCIE_CHANNEL_EN_ONCE   (0xD23B) //PCIe Channel
#endif

#ifndef IDSNVID_CMN_TNR_PCIE_GEN4_EN
  #define IDSNVID_CMN_TNR_PCIE_GEN4_EN   (0xD23C) //PCIe Gen4
#endif

#ifndef IDSNVID_CMN_TNR_USB4_PORT0_EN
  #define IDSNVID_CMN_TNR_USB4_PORT0_EN   (0xD23D) //USB4 Port0
#endif

#ifndef IDSNVID_CMN_TNR_USB4_PORT1_EN
  #define IDSNVID_CMN_TNR_USB4_PORT1_EN   (0xD23E) //USB4 Port1
#endif

#endif //_IDS_NV_ID_RMB_H_
